### ISSUE TITLE
Cannot send native token value with gasless transaction

### ISSUE THREAD

**Issue by StephanGerbeth** [thirdweb-dev/js#1007]
Hi,

is it possible that the user pays for a NFT (msg.value) but the relayer takes over the gasfee?
How could this be realized?
Currently i only resolve the message "Cannot send native token value with gasless transaction" by the sdk.
https://github.com/thirdweb-dev/js/blob/9886c858d9c8d0f677aba6572dbf5cc6c876edf2/packages/sdk/src/evm/core/classes/contract-wrapper.ts#L573

Thanks for your reply.
Cheers
Stephan

**Comment by joaquim-verges** [comment]
Hi @StephanGerbeth this is expected and a limitation of gasless relayers and a security measure.

The thing is that if you're passing msg.value in your transaction, you usually have enough to pay the gas fee as well. So its usually not an issue.

Let me know if that helps
