### ISSUE TITLE
Missing import of FormatTypes

### ISSUE THREAD

**Issue by mahapo** [thirdweb-dev/js#1009]
Importing of FormatTypes is not possible with

"@thirdweb-dev/sdk": "^3.10.14",
"ethers": "5.7.2",

![image](https://github.com/thirdweb-dev/js/assets/28730855/613d2ee0-e53e-4a9b-a85d-fabcd1e8d5b8)
![image](https://github.com/thirdweb-dev/js/assets/28730855/960c2e0c-e590-4445-82fe-2bdd60f0494c)
![image](https://github.com/thirdweb-dev/js/assets/28730855/e617b3d6-5ac8-4f45-a166-f2840a92d1e2)

**Comment by mahapo** [comment]
Works with 
"@thirdweb-dev/auth": "3.0.15",
"@thirdweb-dev/sdk": "^3.10.14",
"@thirdweb-dev/wallets": "0.2.16",

**Comment by joaquim-verges** [comment]
does it work if you explicitely add @ethersproject/units as a dependency in your package.json?

**Comment by mahapo** [comment]
@joaquim-verges I tried with @ethersproject/units and with ethers. Both version 5.7.0 and still the error is still there.

Also with new version 1.0.2

**Comment by joaquim-verges** [comment]
@mahapo removed the dependency in this file altogether here https://github.com/thirdweb-dev/js/pull/1277

once its merged you can pull it from `@thirdweb-dev/sdk@nigthly`

**Comment by joaquim-verges** [comment]
The fix is now on latest stable. Let us know if that works for you @mahapo
