### ISSUE TITLE
Failed to auto connect to the wallet

### ISSUE THREAD

**Issue by CWhits** [thirdweb-dev/js#1018]
# Project Name

thirdweb_connect_error

## Description

This project is a minimal reproduction of a problem experienced when the provider tries to connect.
https://github.com/CWhits/thirdweb_connect_error

## Reproducing the error

Follow these steps to reproduce the error:

1. Clone the project: `git clone https://github.com/CWhits/thirdweb_connect_error`
2. Navigate into the project directory: `cd thirdweb_connect_error`
3. Install the dependencies: `npm install`
4. Start the project: `npm run dev`
5. Make sure no other Chrome window is open.
6. Open a new Chrome window and navigate to `localhost:3000`
7. Connect the wallet and log into MetaMask.
8. Quit Chrome completely from the system menu.
9. Launch Chrome again and navigate to `localhost:3000`
10. If the button is showing the loading indicator, refresh/reload the page.

At this point, you should see the error.

## Error Details

Unhandled Runtime Error
Error: Failed to auto connect to the wallet.

Call Stack
MetaMaskWallet.\_connect2
node_modules/@thirdweb-dev/wallets/dist/base-901ad5ac.browser.esm.js (141:0)
async eval
node_modules/@thirdweb-dev/react-core/dist/useTransactions-3346bed6.browser.esm.js (538:0)

## Environment

Provide any relevant details about the environment where the problem occurs, like:

- OS: 13.3.1 (a) (22E772610a)
- Node.js version: v18.15.0
- npm version: 9.6.3
- Chrome version: Version 113.0.5672.92 (Official Build) (x86_64)
- MetaMask version: 10.29.0

**Comment by MananTank** [comment]
@CWhits 

This is expected - when you close the browser - MetaMask is locked and requires password to unlock, a locked MetaMask can not be auto-connected

**Comment by CWhits** [comment]
Good, but it should not crash the app.

**Comment by MananTank** [comment]
@CWhits It doesn't crash the app - it is just logging out an error

**Comment by CWhits** [comment]
It is crashing in mine.

**Comment by MananTank** [comment]
@CWhits If it is crashing, you can let me what stops working?

**Comment by CWhits** [comment]
Hi @MananTank, were you able to run the sample project that I attached? You should be  experiencing the error being logged in the console, the error overlay and/or the small error window on the bottom left. Have you seen it happen on your side?

**Comment by MananTank** [comment]
The error overlay can be ignored - it's only shown in dev and does not break the app. 

To avoid this, we have stopped throwing the error in https://github.com/thirdweb-dev/js/commit/a5e509438dad551f757db55e8300f79bcf523952 and just logging it out instead.

**Comment by CWhits** [comment]
@MananTank the Wallet now stays in a loading state. Update the project to the latest Thirdweb version and perform the same steps as before. You will see it happen. After refreshing then it logs the "Failed to auto connect to the wallet" error.

**Comment by MananTank** [comment]
@CWhits "Failed to auto connect" error log is expected if wallet can not be auto connected. For example if Metamask is locked - wallet will not be auto connected. This does not break the app - user just needs to connect the app again manually

**Comment by CWhits** [comment]
@MananTank the example I included allows you to replicate the issue with the wallet. I don’t think that the Wallet button displaying a loading state helps with the user experience. If you follow the original 10 steps to reproduce you will easily encounter the issue.

**Comment by CWhits** [comment]
<img width="197" alt="Screenshot 2023-06-03 at 5 48 09 PM" src="https://github.com/thirdweb-dev/js/assets/99901039/9dbd492c-051e-4c34-a5ba-a211199ac5cf">
That is how the wallet looks after quitting Chrome and coming back again to the app.
The steps to reproduce are exactly the same.

**Comment by MananTank** [comment]
@CWhits So It's stuck on loading state?

**Comment by CWhits** [comment]
@MananTank Here is exactly what I am experiencing. This video was recorded using the latest versions    
"@thirdweb-dev/react": "^3.13.0",
"@thirdweb-dev/sdk": "^3.10.20",


https://github.com/thirdweb-dev/js/assets/99901039/ef80c39b-19e6-4ccb-b6bd-e0d1adb2ad94

**Comment by MananTank** [comment]
@CWhits Thanks for this, Can you check if any Network requests are being blocked in Network panel?

**Comment by CWhits** [comment]
@MananTank narrowing down I can see that the issue can arise from the Local Storage. When the button remains in a spinning state the __TW__/coordinatorStorage/lastConnectedWallet object is {"walletId":"metamask","connectParams":{}}. In this case  if (!walletObj) {...} in line 308 of thirdweb-wallet-provider.tsx will think that you have a valid object and the code will continue until it gets stuck in the try that starts in line 358. Certainly the setConnectionStatus("connecting"); will be triggered but it seems that the code will be stuck in await wallet.autoConnect(walletInfo.connectParams); As I can see you add and remove the __TW__/coordinatorStorage/lastConnectedWallet when connecting and disconnecting but that key pair could persist when quitting the browser thus the next time the user opens the browser, that key pair could be available and wallet.autoConnect might not return. Hope it helps.

**Comment by CWhits** [comment]
Maybe checking that the lastConnectedWallet exist in Local Storage and then checking if some specific parameter exist as well after checking walletObj and set the setConnectionStatus("disconnected"); if the object or parameter is empty. Not the best thing but maybe can patch this thing for the moment.

**Comment by rashi293** [comment]
![image](https://github.com/thirdweb-dev/js/assets/109426175/e92586d6-192c-493c-a16f-1283c38d3bdf)

**Comment by rashi293** [comment]
I'm facing this issue in mine. What to do, please suggest?

**Comment by MananTank** [comment]
@rashi293 Looks like the error in your case is thrown - Can you update to latest version so that the error is not thrown and just logged

**Comment by CWhits** [comment]
Hello @MananTank any update on this issue?

**Comment by MananTank** [comment]
@CWhits Can you update to latest version of thirdweb packages and check if the issue still persists?

**Comment by MananTank** [comment]
Hey @CWhits 
I've added autoconnect timeout in the latest nightly version. So that ConnectWallet button does not remain stuck indefinitely

The default is 15 seconds. If you want to configure the timeout - You can set time in milliseconds in `autoConnectTimeout` prop in `<ThirdwebProvider />` 

Please use below version to test this: 

```
@thirdweb-dev/react@3.14.7-nightly-edcd22d6-20230629122835
@thirdweb-dev/sdk@3.10.26
```

Let me know if this fixes the autoconnect stuck on loading state for you

**Comment by tejajustin** [comment]
![169029230906729671595629972624](https://github.com/thirdweb-dev/js/assets/132671606/4c37404e-c55e-45e7-92cc-9bab13cc5a0e) 
How 
![Uploading 1690292377978863428603215022575.jpg…]()
exactly to resolve this?

**Comment by jayavardhan3112** [comment]
Anyone still facing the issue ?, Any solution ?
