### ISSUE TITLE
SSL Error: The thirdwebcdn.com IPFS gateway has SSL error affecting @thirdweb-dev/react-core

### ISSUE THREAD

**Issue by donfrancisco** [thirdweb-dev/js#1028]
**Issue:**

The **_thirdwebcdn.com_** gateway has an SSL error.
[https://ipfs.thirdwebcdn.com/ipfs/QmV4HC9fNrPJQeYpbW55NLLuSBMyzE11zS1L4HmL6Lbk7X](https://ipfs.thirdwebcdn.com/ipfs/QmV4HC9fNrPJQeYpbW55NLLuSBMyzE11zS1L4HmL6Lbk7X
)

Getting the following error:

> Failed to load resource: An SSL error has occurred and a secure connection to the server cannot be made.

**Example IPFS CID working in other gateways:**
https://ipfs.io/ipfs/QmV4HC9fNrPJQeYpbW55NLLuSBMyzE11zS1L4HmL6Lbk7X
https://gateway.ipfscdn.io/ipfs/QmV4HC9fNrPJQeYpbW55NLLuSBMyzE11zS1L4HmL6Lbk7X/

**The following portal pages are broken as a result:**
https://portal.thirdweb.com/react/react.mediarenderer
https://portal.thirdweb.com/react/react.thirdwebnftmedia

**Affects the following packages:**
react, react-core, react-native, cli and storage.

**Version tested:** 
@thirdweb-dev/react-core "version": "3.11.11"

**Browsers tested:**
Safari and Chrome on Mac with all Ad blockers turned off.

![SSL_Error](https://github.com/thirdweb-dev/js/assets/306284/8bd25352-2024-4439-a0ca-b811e9b61367)

**Comment by jakeloo** [comment]
Hey, we've opened a ticket with our SSL provider.

**Comment by joaquim-verges** [comment]
@donfrancisco can you try with the latest version of the react package?

**Comment by jiayuxiaochaoren** [comment]
does it work? i have the following questions：
![image](https://github.com/thirdweb-dev/js/assets/12232001/1ed966c1-47b5-4489-b909-d669b2861885)
my wallet cannot show logo,anyone has encountered this problem?

**Comment by joaquim-verges** [comment]
@jiayuxiaochaoren make sure you're on the latest @thirdweb-dev/react version

**Comment by larron** [comment]
Seeing similar. I'm on `"@thirdweb-dev/react": "^3.14.36",`
<img width="988" alt="Screenshot 2023-08-24 at 1 50 45 AM" src="https://github.com/thirdweb-dev/js/assets/1730829/b6a0e7cc-64b3-4c11-a554-320d0d5667c1">

**Comment by MananTank** [comment]
@larron @jiayuxiaochaoren  

Make sure you are using the latest version of @thirdweb-dev/react, @thirdweb-dev/sdk, and have set the correct domains and services for your clientId in [settings](https://thirdweb.com/dashboard/settings)

**Comment by LionsHabitat** [comment]
That was it, for anyone struggling with this, don't forget to edit your "allowed domains" in the thirdweb panel when you move from localhost to deploy. *face-palm*

Thanks for the quick response @MananTank

**Comment by larron** [comment]
That was it, for anyone struggling with this, don't forget to edit your "allowed domains" in the thirdweb panel when you move from localhost to deploy. face-palm

Thanks for the quick response @MananTank
