### ISSUE TITLE
Update Marketplace V3 embed to display correct number of bids on English Auction listing

### ISSUE THREAD

**Issue by lakgarg** [thirdweb-dev/js#1039]
After creating a Marketplace V3 contract using the dashboard and submitting bids, it appears that the bids placed are not being reflected in the embedded English Auction section.

In the provided image within the embed, it clearly states that there are no bids in the auctions yet, which is not accurate:

![image](https://github-production-user-asset-6210df.s3.amazonaws.com/33596961/239648027-b8b65899-f509-4519-9017-a645a68baf7f.png)

Therefore, it is necessary to update the embed for Marketplace V3, ensuring that the number of bids on the English Auction listing is correctly updated and displayed.

**Comment by joaquim-verges** [comment]
thanks for the report! we'll look into this

**Comment by lakgarg** [comment]
hey @joaquim-verges @nachoiacovino, following up on this one!

**Comment by nachoiacovino** [comment]
hey @lakgarg, this is fixed now, you'll need to get the new embed URL from dashboard, thanks for the patience!
