### ISSUE TITLE
ThirdwebProvider doesn't support passing Base Goerli chainId or slug

### ISSUE THREAD

**Issue by taycaldwell** [thirdweb-dev/js#1082]
Hello,

I tried modifying the [thirdweb NFT Gallery template](https://portal.thirdweb.com/templates) to use a NFT collection on Base Goerli.
During this process, I set the `activeChain` of the `ThirdwebProvider` to be `base-goerli`, but got the following error:

`Error: Invalid chain: "base-goerli". It is not one of supportedChains`

I also get a similar error when providing the chainId `84531`.

However, importing and using `BaseGoerli` directly from `@thirdweb-dev/chains` works as expected.

`import { BaseGoerli } from "@thirdweb-dev/chains";`

----------------------------

Expected behavior: Base Goerli is detected as a supportedChain, even when only providing the `slug` or `chainId` to the `ThirdwebProvider`, as works with other supported chains.

**Comment by MananTank** [comment]
@taycaldwell you can only specify a `string` or `number` to `activeChain` if it's one of the thirdweb's default supported chains. Otherwise you need to pass the full Chain object as mentioned in docs: https://portal.thirdweb.com/react/react.thirdwebprovider

```ts 
import { BaseGoerli } from "@thirdweb-dev/chains";

<ThirdwebProvider activeChain={BaseGoerli} />
```
