### ISSUE TITLE
Can not get const contractType = await sdk.resolveContractType(contractId) if login magicLink. I try login magic link , but it not get singer.

### ISSUE THREAD

**Issue by legiarung** [thirdweb-dev/js#112]
<img width="1440" alt="Screen Shot 2022-09-13 at 1 58 54 PM" src="https://user-images.githubusercontent.com/28915036/189832110-58998372-8b06-4df9-a24c-fb7b5f1fd9a3.png">

**Comment by legiarung** [comment]
<img width="1439" alt="Screen Shot 2022-09-13 at 3 42 17 PM" src="https://user-images.githubusercontent.com/28915036/189854964-1cba4eb2-81f7-44fd-a54e-10f2cad04233.png">

And i use useSinger but it work not well

**Comment by joaquim-verges** [comment]
could you share the code that you're calling that throws these errors? From looking at them it looks like you're not connected to the correct chain or passing a wrong address

**Comment by jarrodwatts** [comment]
Any updates on this @legiarung?
