### ISSUE TITLE
unable to switch networks from walletConnectV2

### ISSUE THREAD

**Issue by bridgette-swr** [thirdweb-dev/js#1148]
While switching any network and reload or transition to any page `walletConnect` resets to the Ethereum network. 
This even happening in the [demo page](https://portal.thirdweb.com/react/react.connectwallet) of the Connect Wallet Button.

Initially I thought this is problem with `walletConnectV1` as default `supportedWallets` in `ThirdWebProvider` includes walletConnectV1, which is mentioned in [docs](https://portal.thirdweb.com/react/connecting-wallets#:~:text=If%20no%20supportedWallets%20prop%20is%20passed%2C%20the%20default%20is%20to%20support%20metamaskWallet%2C%20coinbaseWallet%2C%20and%20walletConnectV1).

So I added walletConnectV2  explicitly to the `supportedWallets`, but there is a whole new problem with walletConnectV2 is while switching any network, it's showing me this error message in UI:

![image](https://github.com/thirdweb-dev/js/assets/132783368/cfbc4592-0eb2-4bb2-89f5-3547ce604290)

and in console it throws this error:

![image](https://github.com/thirdweb-dev/js/assets/132783368/824360eb-4351-4ce8-a818-445217cd3e6f)

Is this issue with `thirdweb` or `Wallet Connect`?

**Comment by MananTank** [comment]
Hi @bridgette-swr - Currently walletConnectV2 does not support switching chains. we are looking into the issue you mentioned with walletConnectV1 and will fix on high priority.

**Comment by MananTank** [comment]
Hi @bridgette-swr - Currently walletConnectV2 does not support switching chains. We will disable chain switching for walletConnectV2.

We are looking into the auto connect issue with walletConnect v1

**Comment by bridgette-swr** [comment]
Hey, @MananTank  thanks for the reply. I'm actually using Rainbow wallet for Wallet Connect.

**Comment by MananTank** [comment]
@bridgette-swr - and you are still not able to switch chains?

**Comment by bridgette-swr** [comment]
these are the versions I'm using 
```
    "@thirdweb-dev/chains": "^0.1.15",
    "@thirdweb-dev/react": "^3.11.11",
    "@thirdweb-dev/sdk": "^3.10.14",
```

I verified the `walletConnecctV2` now it switching it properly, I'm not getting the error the I mentioned above.
