### ISSUE TITLE
[SDK] Duplicated codes that can potentially be abstracted

### ISSUE THREAD

**Issue by kienngo98** [thirdweb-dev/js#1174]
1. Between these 2 files: [`normalizedAmount.ts`](https://github.com/thirdweb-dev/js/blob/main/packages/sdk/src/evm/common/currency/normalizeAmount.ts) and [`erc-20.ts`](https://github.com/thirdweb-dev/js/blob/main/packages/sdk/src/evm/core/classes/erc-20.ts)

![image](https://github.com/thirdweb-dev/js/assets/26052673/5f4dd791-1e74-4663-acca-0f2eb8917b82)

2. And these:
![image](https://github.com/thirdweb-dev/js/assets/26052673/a476e0e3-be17-4693-827e-8671dd70b8c0)

I can work on these if you guys deem they fit to change @joaquim-verges @MananTank

**Comment by joaquim-verges** [comment]
any cleanup like that is super useful! appreciate your help on this @kienngo98

**Comment by kienngo98** [comment]
@joaquim-verges Thanks! I'm on it. In the mean time would you be able to take a look at this issue? https://github.com/thirdweb-dev/js/issues/1179
