### ISSUE TITLE
Cannot run either `pnpm build` or `pnpm test` in my local machine

### ISSUE THREAD

**Issue by kienngo98** [thirdweb-dev/js#1179]
Hi, is someone having this issue? I have to postpone my PR because I can't test or build the changes. It happens to a freshly cloned repo as well.

OS: Both Windows 10 and Ubuntu 20.04 (tried on both)
Versions (same on both Windows and Ubuntu):
```
Node: v18.16.0
pnpm: 8.6.2
npm: 8.18.0
```

Steps to reproduce:
1. Clone the main repo: https://github.com/thirdweb-dev/js (forking has the same results)
2. Run pnpm install
3. Run either pnpm build or pnpm test
4. Get error: 
```
🎁 error @thirdweb-dev/storage browser field is invalid, found {"./dist/thirdweb-dev-storage.esm.js":"./dist/thirdweb-dev-storage.browser.esm.js"}, expected {"./dist/thirdweb-dev-storage.cjs.js":"./dist/thirdweb-dev-storage.browser.cjs.js","./dist/thirdweb-dev-storage.esm.js":"./dist/thirdweb-dev-storage.browser.esm.js"}``
```

Screenshot attached:

![image](https://github.com/thirdweb-dev/js/assets/26052673/0bfbafc7-0b8b-45be-9f1e-3bdba874e8ae)

-------

![image](https://github.com/thirdweb-dev/js/assets/26052673/8cf04868-3660-44ca-a8df-2d30e41bbe54)

The root `package.json` has not been edited. It's exactly the same as in the main repo.

**Comment by joaquim-verges** [comment]
That's odd. Can you try `pnpm precontruct fix`  from /packages/storage ?

**Comment by kienngo98** [comment]
@joaquim-verges  Thanks. The issue with @storage seems to be gone now _HOWEVER_ now I have other issues coming from the @chain package, when re-try running`pnpm build` (see image)
![image](https://github.com/thirdweb-dev/js/assets/26052673/a15e9254-7667-473d-98ff-ccdb21cdb4ad)

I have also run `pnpm preconstruct fix` inside the `./packages/chains` but it didn't help

**Comment by joaquim-verges** [comment]
I wonder if this is a node 18 thing. Can you try with node 16 just to confirm that's the issue?

**Comment by kienngo98** [comment]
Roger that!

**Comment by kienngo98** [comment]
@joaquim-verges I downgraded to `v16.16` and it's not helping. May I ask which version of node are you using? Here's what I did:

1. Remove node v18.16
2. Reboot the machine
3. Install node v16.16
4. Clone the repo to a new location
5. `pnpm install`
6. `cd packages/sdk && pnpm preconstruct fix`
7. `pnpm build`

-> The build has issue with @chains (`error TS1005: ';' expected` just like mentioned in the image above.

**Comment by MananTank** [comment]
@kienngo98 - Are you doing `pnpm install` and `pnpm build` at root first?

**Comment by kienngo98** [comment]
@MananTank Yes I'm running `install` and `build` from the root. And your suggestion (`pnpm install --ignore-scripts`) seems to be the solution! I no longer have that issue!
![image](https://github.com/thirdweb-dev/js/assets/26052673/a82560fb-7567-4859-8d82-6522bed1cf24)

Thanks again @joaquim-verges @MananTank
