### ISSUE TITLE
Bug: React Native app is crashing when handling deeplink

### ISSUE THREAD

**Issue by upacyxou** [thirdweb-dev/js#1195]
**Issue**: The application crashes when handling a deeplink if Coinbase is not initialized.

**Expected behavior**: The application should not crash, and the Coinbase listener should not process the link if Coinbase is not initialized.

**Description**: I have discovered that our React Native application crashes when trying to handle a deeplink if the `coinbase-sdk` is not initialized (we do not use Coinbase in our app). Initially, I thought the issue was related to the `coinbase-sdk` itself (https://github.com/coinbase/wallet-mobile-sdk/issues/227), but it turns out that it is not. My assumption is that the problem is caused by the Coinbase listener being processed even if Coinbase is not being used. This can be found here: https://github.com/thirdweb-dev/js/blob/main/packages/react-native/src/evm/wallets/hooks/useCoinbaseWalletListener.ts. In our project, we have created a patch for thirdweb by commenting out the `handleResponse(url)` line.

**Reproducible example**:
```
import '@thirdweb-dev/react-native-compat'
import { Mumbai, Polygon } from '@thirdweb-dev/chains'
import { ThirdwebProvider } from '@thirdweb-dev/react-native'

export const authConfig = {
  authUrl: '',
  domain: '',
}

export const appMetadata = {
  name: 'Ketl',
  description: 'Ketl',
  logoUrl: 'https://ketl.xyz/favicon/apple-touch-icon.png',
  url: 'https://ketl.xyz',
}

export const supportedChains = [Polygon, Mumbai]

function App() {
  return (
    <ThirdwebProvider dAppMeta={appMetadata} supportedChains={supportedChains}>
      <></>
    </ThirdwebProvider>
  )
}

const WrapperApp = App

export default WrapperApp
```
And the deeplink to the application, in our case, is "ketl://email?domain=domain&token=very-long-token". The crash always occurs. Tested on iOS.

**Comment by dalmendray** [comment]
@upacyxou thanks for reporting this, which version of the SDK are you using?

**Comment by iketw** [comment]
@upacyxou , fix is merging: https://github.com/thirdweb-dev/js/pull/1270

**Comment by iketw** [comment]
@upacyxou , please, use the nightly build, we'll ship the fixes this week:

`yarn add @thirdweb-dev/react-native@nightly`
