### ISSUE TITLE
Relax MediaRenderer HTML MimeType Check

### ISSUE THREAD

**Issue by mpeyfuss** [thirdweb-dev/js#1201]
Currently the NFT Renderer is broke for all HTML NFTs hosted on Arweave. This is because of the `MediaRenderer` strict mimeType check: `videoOrImageSrc.mimeType === "text/html"`

Arweave mimeType returns `text/html; charset=utf-8` from the `useResolvedMediaType` function. 

This check in `MediaRenderer` should be relaxed to `videoOrImageSrc.mimeType.startsWith("text/html")`

**Comment by nachoiacovino** [comment]
hey @mpeyfuss! thanks for reporting this to us! Feel free to open a PR yourself with the fix, otherwise we'll get to is as soon as possible.

**Comment by mpeyfuss** [comment]
woo hoo! Thanks!!
