### ISSUE TITLE
Uncaught Error: Must be used within Provider when using an external provider such as wagmi

### ISSUE THREAD

**Issue by AngelofPc** [thirdweb-dev/js#121]
<img width="1597" alt="image" src="https://user-images.githubusercontent.com/24842161/190238378-f4b5cdfc-556c-4b1e-8bdc-599b06c63d58.png">

**Comment by joaquim-verges** [comment]
@AngelofPc can you share how you're passing the external provider? here's a working example in our portal: https://portal.thirdweb.com/sdk/set-up-the-sdk/frontend#from-a-signer--provider

**Comment by AngelofPc** [comment]
![image](https://user-images.githubusercontent.com/24842161/190867676-50d6d607-da70-483e-a2f0-f58d9ca40a9b.png)

Here @joaquim-verges

**Comment by joaquim-verges** [comment]
@AngelofPc looking at your stack trace, you're using the `ConnectWallet` component. That's only usable with the `ThirdwebProvider` which manages the wallet connection for you.

If you want to pass your own wagmi signer/provider using the `ThirdwebSDKProvider`, then you need to implement the wallet connection logic some other way. Here's an example using rainbowkit https://blog.avneesh.tech/how-to-use-rainbowkit-with-thirdweb

**Comment by AngelofPc** [comment]
Tried it with Connectkit and Rainbow Wallet before switching things up, But will try this and let you know. @joaquim-verges

**Comment by AngelofPc** [comment]
Not working, same as before. 

I think it's the now deprecated "useNftCollection" causing it. 

I see that we are supposed to now use useContract() but there is no documentation for it or how to do a signature mint with it? @joaquim-verges

**Comment by joaquim-verges** [comment]
@AngelofPc but are you still using the `ConnectWallet` component from `@thirdweb-dev/react` in your code? 

Btw curious why you need to pass the provider externally? Wonder if you can just use the normal thirdweb react setup to achieve what you want.

**Comment by AngelofPc** [comment]
No, i'm no longer using the `ConnectWallet` component. 

Want to pass the use either `ConnectKit` or `RainbowKit` because of their UI especially.

Worked better before `@thirdweb-dev/react 3.0.0` though.
@joaquim-verges

**Comment by joaquim-verges** [comment]
Got it. I think i see what the problem is. We'll get that fixed this week.

Thanks for reporting this 🙏

cc @jnsdls

**Comment by AngelofPc** [comment]
Thanks @joaquim-verges, Really appreciate.

Could you please let me know when it's done? 

I'm present in the discord as well if it's easier.

**Comment by joaquim-verges** [comment]
@AngelofPc can you try this build and let me know if everything works for you? 
```
npm install @thirdweb-dev/sdk@3.0.3-dev-4520f81 @thirdweb-dev/react@3.0.3-dev-4520f81
```

**Comment by AngelofPc** [comment]
Works so far, thanks @joaquim-verges.

However, I noticed DevTools getting disconnected every time since i installed the update

<img width="457" alt="image" src="https://user-images.githubusercontent.com/24842161/190933421-bb52b2ba-1d71-4037-a7db-48b940d1aa39.png">



Also, can you help with your email or twitter handle, I'd like your answer/feedback on something. 

Thanks

**Comment by Sense** [comment]
I still have the error `Must be within Provider`, I don't understand why my `_app` is pretty simple :

```tsx
<WagmiConfig client={wagmiClient}>
        <SessionProvider refetchInterval={0} session={pageProps.session}>
          <RainbowKitSiweNextAuthProviderCustom>
            <RainbowKitProvider chains={chains}>
              <ThirdwebProvider wagmiClient={wagmiClient}>
                <AnimatePresence exitBeforeEnter>
                  {getLayout(<Component {...pageProps} />)}
                </AnimatePresence>
              </ThirdwebProvider>
            </RainbowKitProvider>
          </RainbowKitSiweNextAuthProviderCustom>
        </SessionProvider>
      </WagmiConfig>
```

Here is the trace. @joaquim-verges any idea?

![Screenshot 2022-09-19 at 09 00 59](https://user-images.githubusercontent.com/1511275/190964902-2dfea93e-885c-4cb5-a71c-a5387340fb89.png)

**Comment by joaquim-verges** [comment]
@Sense thanks for reporting this.

What's inside your `Claim` component? Looks like the error is coming from there.

In general the thing to keep in mind when using an external wallet connector is that you can't use the thirdweb hooks related to wallet connection (like useAddress, useChainId etc) - those require the standard `ThirdwebProvider` since that's what would normally handle the wallet connection internally.

Instead for these wallet related hooks, you should use the ones from the library you're using (wagmi in your case).

All the contract related hooks should be usable though, that's what the dev build fixes (will ship it to stable today)

**Comment by Sense** [comment]
Thanks @joaquim-verges my Claim page looks like :

```tsx
const Claim = dynamic(() => import('../../components/Claim'), {
  ssr: false
})

const NftClaimPage = () => {
  return (
    <div className="flex flex-col">
      <Claim contractAddress={process.env.editionDropAddress} />
    </div>
  )
}
```

The thing that Thirdweb hooks are working great using the v2 of `@thirdweb-dev/react` and `@thirdweb-dev/sdk` so it's probably related to the v3 ? There is an opened thread on it on [this Discord thread].
(https://discord.com/channels/834227967404146718/1020660790296072242)
I made it work with the `magicLinkWalletConnector` as an external connector, but still with the v2.

**Comment by joaquim-verges** [comment]
@Sense and it still happens with the latest releases? (v3.0.4)

we might have missed another hook that uses the wallet connection hooks internally. The stacktrace shows that something inside that `/components/Claim` is causing the issue. Likely one of our hooks. If you can help me pin point which one I can get a fix out very quickly.

**Comment by joaquim-verges** [comment]
@Sense also - unrelated, but if you want to ping me on discord about that `Disable SSR as thirdweb SDK only working on browser` - i'm curious why you think that. We use our SDK in SSR on our dashboard so it's definitely possible!

**Comment by Sense** [comment]
Let's continue the discussion on Discord then @joaquim-verges, thank you.
