### ISSUE TITLE
error with i i try npx thirdweb release

### ISSUE THREAD

**Issue by JoseMariani** [thirdweb-dev/js#1231]
Please help me, this is the recreation: 

1- I download this: https://github.com/sonnysangha/lottery-smart-contract  
2-I install thirdweb cli. 
3. I login in thirdweb, connect my wallet on mumbai test network. 
4. i run npx thirdweb release 

and get: 
 Error uploading metadata 

 
what am I doing wrong?

**Comment by joaquim-verges** [comment]
@JoseMariani can you make sure you're on the latest CLI version? you can run it with npx:
`npx thirdweb@latest publish`

**Comment by JoseMariani** [comment]
Thank bro, the support of ThirdWeb, help me days ago, and yes!! that was what caused the error, always try to run the command with the latest version of thirdweb. and it will be solved.

Thanks for watching, it's wonderful.
