### ISSUE TITLE
[REACT] Issue trying to overwrite default RPC Urls in `<ThirdwebProvider />`

### ISSUE THREAD

**Issue by kienngo98** [thirdweb-dev/js#1242]
Describe issue: I'm trying to add a custom rpc url from LlamaNodes ***on top*** of the default RPCs from Thirdweb and it's not working.

Code:
```
import { Ethereum} from '@thirdweb-dev/chains';

const LLAMA_NODE_RPC_URL = 'https://eth.llamarpc.com/rpc/<MY_KEY_HERE>';
const activeChain = { ...Ethereum, rpc: [LLAMA_NODE_RPC_URL, ...Ethereum.rpc] };

<ThirdwebProvider
  activeChain={activeChain}
>
  {children}
</ThirdwebProvider>
```

> console.log(activeChain.rpc) will return:
```
[
    "https://eth.llamarpc.com/rpc/<MY_KEY_HERE>",
    "https://ethereum.rpc.thirdweb.com/${THIRDWEB_API_KEY}",
    "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}",
    "https://mainnet.infura.io/v3/${INFURA_API_KEY}",
    "wss://mainnet.infura.io/ws/v3/${INFURA_API_KEY}",
    "https://api.mycryptoapi.com/eth",
    "https://cloudflare-eth.com",
    "https://ethereum.publicnode.com"
]
```

However in the Network tab, Thirdweb is still using the default RPC Url (`https://ethereum.rpc.thirdweb.com`) - check image
![image](https://github.com/thirdweb-dev/js/assets/26052673/48fbc230-1548-4e26-940f-7880c42c407c)

Note: Using only the custom RPC will work, but not the other way around.
```
const activeChain = { ...Ethereum, rpc: [LLAMA_NODE_RPC_URL] }; // <---- this works
```

Versions:
```
"@thirdweb-dev/react": "^3.14.3",
"@thirdweb-dev/sdk": "^3.10.25",
```

**Comment by MananTank** [comment]
Hi @kienngo98 Thanks for reporting this issue. We are working on fixing this issue and will let you when the fix is available on @nightly ASAP

**Comment by MananTank** [comment]
Hey @kienngo98 - This issue is fixed and is available on latest nightly version!
