### ISSUE TITLE
Disconnect broken in @thirdweb-dev/react-native (version 0.2.23)

### ISSUE THREAD

**Issue by hixus** [thirdweb-dev/js#1260]
Can't disconnect Metamask on 0.2.23 in  `<ConnectWallet />` component or with useDisconnect hook. Works fine with 0.2.22.

With `<ConnectWallet />` the loading state gets stuck. With useDisconnect promise never returns. `disconnect().finally(() => {console.log('never called')})`

With 0.2.22 I manually created WalletConnectV2 based MetaMask wallet  so should not be related to WC1 vs WC2 difference.

Device: Pixel 6, Android 13

**Comment by hixus** [comment]
Seems to be broken in 0.2.24 too

**Comment by jnsdls** [comment]
hey @hixus thanks for the report, just confirming this is happening in a react native environment or is it a web app?

**Comment by iketw** [comment]
@jnsdls , it's in react native. @hixus which chain are you on? I believe this is an issue with the network call not resolving. Can you try mainnet just to check that it connects/disconnects?

**Comment by hixus** [comment]
Was actually some weird dependency issue in our repo. Removing our yarn.lock and running yarn install again seemed to resolve this.
