### ISSUE TITLE
[React Native] [Android] No redirect back to the app with rainbow wallet after signing in

### ISSUE THREAD

**Issue by T-Damer** [thirdweb-dev/js#1290]
What I am doing:
1) Wrapping my app in `ThirdWebProvider` with proper config (in `url` section of config I tried both web-site url and deeplink, nothing worked)
2) Making a `Connect wallet` button, that connects rainbow wallet and requests a sign message, callback looks like this:
```TS
  const connectRainbow = useRainbowWallet()
...
  const ownerWallet = await walletProcessor[type].connectWallet()
  const ownerAddress = await ownerWallet?.getAddress()
  if (!ownerAddress || !ownerWallet) return
  const ownershipSignature = await ownerWallet.signMessage('message')
```
I tried separating connect and sign logic, it didn't help

---

`pacakge.json`:

```JSON
    "@thirdweb-dev/react-native": "^0.2.25",
    "@thirdweb-dev/react-native-compat": "^0.2.25",
```

---
Related issue and answer (already tried, not working):
https://github.com/rainbow-me/rainbowkit/issues/521#issuecomment-1208774456

**Comment by dalmendray** [comment]
@T-Damer could you test with the latest version of the SDK? version: `0.2.39`

**Comment by iketw** [comment]
> @dalmendray I tested with `0.2.50`, it doesn't redirect from any wallet now on iOS (Android works partly, not consistent), I have proper `clientId` set

@T-Damer thanks for reporting, I'll try to repro on my end and reply here with what I find.

**Comment by iketw** [comment]
@T-Damer any progress on this? Are you still getting the same behavior?

Could you please share your `ThirdwebProvider` setup and the code behind:

```
const ownerWallet = await walletProcessor[type].connectWallet()
```
