### ISSUE TITLE
Not injecting our api keys into the chains' RPCs when using the SDK + Wallets packages directly.

### ISSUE THREAD

**Issue by 0xFirekeeper** [thirdweb-dev/js#1296]
In react-core we do inject the api key: [https://github.com/thirdweb-dev/js/commit/e2ea5a716fe686c76e833048e6fb1125e2dc5f61#diff-d3dcbbb591129ef12e6c5e21da[…]04f223658c36163e6f06d36ddfcR121](https://github.com/thirdweb-dev/js/commit/e2ea5a716fe686c76e833048e6fb1125e2dc5f61#diff-d3dcbbb591129ef12e6c5e21da2244bf66d0d04f223658c36163e6f06d36ddfcR121).

Solutions for this:
At wallet construction, when all the chains are passed we need to overwrite the chains rpcs by calling `getChainRPC` : https://github.com/thirdweb-dev/js/blob/2221f97ddc997d864db3a5f00e82862ece574922/packages/chains/src/utils.ts#L95, which injects the correct api key
OR
Call `getChainRPC` to inject the api key at connection/switching chains time if possible

**Comment by wuichen** [comment]
Ditto seeing same issue

**Comment by MananTank** [comment]
This has been fixed in latest version. You can now pass `clientId` to Wallet to inject apiKeys in chains
