### ISSUE TITLE
error when i run deploy

### ISSUE THREAD

**Issue by muizzthaqif10** [thirdweb-dev/js#1325]
hello, i got an error said require stack when i npm run deploy. before this there is no error but suddenly got this. my react version already ^18.  

node:internal/modules/cjs/loader:1042
  throw err;
  ^

Error: Cannot find module 'explain-error'
Require stack:
- C:\Users\muizz\AppData\Local\npm-cache\_npx\86fd6f984ad48a35\node_modules\cid-tool\src\core\base32.js
- C:\Users\muizz\AppData\Local\npm-cache\_npx\86fd6f984ad48a35\node_modules\cid-tool\src\core\index.js
- C:\Users\muizz\AppData\Local\npm-cache\_npx\86fd6f984ad48a35\node_modules\cid-tool\src\index.js
- C:\Users\muizz\AppData\Local\npm-cache\_npx\86fd6f984ad48a35\node_modules\@thirdweb-dev\storage\dist\thirdweb-dev-storage.cjs.dev.js
- C:\Users\muizz\AppData\Local\npm-cache\_npx\86fd6f984ad48a35\node_modules\@thirdweb-dev\storage\dist\thirdweb-dev-storage.cjs.js
- C:\Users\muizz\AppData\Local\npm-cache\_npx\86fd6f984ad48a35\node_modules\@thirdweb-dev\sdk\dist\contract-publisher-2edb2c9e.cjs.dev.js
- C:\Users\muizz\AppData\Local\npm-cache\_npx\86fd6f984ad48a35\node_modules\@thirdweb-dev\sdk\evm\dist\thirdweb-dev-sdk-evm.cjs.dev.js
- C:\Users\muizz\AppData\Local\npm-cache\_npx\86fd6f984ad48a35\node_modules\@thirdweb-dev\sdk\evm\dist\thirdweb-dev-sdk-evm.cjs.js
- C:\Users\muizz\AppData\Local\npm-cache\_npx\86fd6f984ad48a35\node_modules\thirdweb\dist\cli\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Users\muizz\AppData\Local\npm-cache\_npx\86fd6f984ad48a35\node_modules\cid-tool\src\core\base32.js:5:17)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\muizz\\AppData\\Local\\npm-cache\\_npx\\86fd6f984ad48a35\\node_modules\\cid-tool\\src\\core\\base32.js',
    'C:\\Users\\muizz\\AppData\\Local\\npm-cache\\_npx\\86fd6f984ad48a35\\node_modules\\cid-tool\\src\\core\\index.js',
    'C:\\Users\\muizz\\AppData\\Local\\npm-cache\\_npx\\86fd6f984ad48a35\\node_modules\\cid-tool\\src\\index.js',
    'C:\\Users\\muizz\\AppData\\Local\\npm-cache\\_npx\\86fd6f984ad48a35\\node_modules\\@thirdweb-dev\\storage\\dist\\thirdweb-dev-storage.cjs.dev.js',
    'C:\\Users\\muizz\\AppData\\Local\\npm-cache\\_npx\\86fd6f984ad48a35\\node_modules\\@thirdweb-dev\\storage\\dist\\thirdweb-dev-storage.cjs.js',
    'C:\\Users\\muizz\\AppData\\Local\\npm-cache\\_npx\\86fd6f984ad48a35\\node_modules\\@thirdweb-dev\\sdk\\dist\\contract-publisher-2edb2c9e.cjs.dev.js',
    'C:\\Users\\muizz\\AppData\\Local\\npm-cache\\_npx\\86fd6f984ad48a35\\node_modules\\@thirdweb-dev\\sdk\\evm\\dist\\thirdweb-dev-sdk-evm.cjs.dev.js',
    'C:\\Users\\muizz\\AppData\\Local\\npm-cache\\_npx\\86fd6f984ad48a35\\node_modules\\@thirdweb-dev\\sdk\\evm\\dist\\thirdweb-dev-sdk-evm.cjs.js',
    'C:\\Users\\m

**Comment by Marfuen** [comment]
Hello, is this still an issue?
