### ISSUE TITLE
3rd party wallet chain change bug and feature request

### ISSUE THREAD

**Issue by NathanFrank285** [thirdweb-dev/js#1348]
Hello, was told to add this here from discord team:

I came across a bug when using the <ConnectWallet /> component with multiple supported chains. When a user connects, then goes into their 3rd party wallet and changes the chain, the ThirdwebProvider will error as the user is now on an unsupported chain.

My suggestion for this was that keeping the wallet chain and dapp chain in sync similar to how wagmi does it could reduce a lot of confusion and avoids have to set up a chain context, per this [blog post](https://blog.thirdweb.com/guides/how-to-support-multiple-chains-in-your-dapp/) 

If possible, adding a prop on <ConnectWallet chainMismatch={chainMismatch} />, where chainMismatch is the boolean received from the useNetworkMismatch hook, that when there is a chain mismatch and the chain is not a supported chain, that it blocks the chain switch, then opens the ConnectWallet modal to the select chain tab which has all of the supported chains on it, would be a big help! thanks!

**Comment by MananTank** [comment]
@NathanFrank285 We are already keeping the chain in wallet and app in sync - when chain is changed from wallet, it changes the chain in app ( sometimes this takes a while ). 

Can you share for which wallet this did not work for you?

**Comment by NathanFrank285** [comment]
@MananTank The error occurs when lets say I have 2 chains set up as supported chains, Ethereum and Polygon. Then if I go into my metamask wallet, and change it to Arbitrum, Provider will error saying "Arbitrum is not a supported chain"

**Comment by MananTank** [comment]
@NathanFrank285 I'm not able to replicate the error you have mentioned, see the attached video: 


https://github.com/thirdweb-dev/js/assets/22043396/fe4e60f2-b747-4467-a2e3-82a7cd8d37a9


If you are able to replicate it, can you send a screen recording?

**Comment by NathanFrank285** [comment]
@MananTank, thanks for sharing, let me show you my setup and a video of what occurs, I've also upgraded all of the thirdweb packages:

We are multichain so we set up switching according to this blog post: https://blog.thirdweb.com/guides/how-to-support-multiple-chains-in-your-dapp/

SUPPORTED_CHAINS  looks like this, all values are imported from @thirdweb-dev/chains: 
```
const SUPPORTED_CHAINS = [
  Celo,
  Ethereum,
  CeloAlfajoresTestnet,
];
```
![Screenshot 2023-07-27 at 11 36 03 AM](https://github.com/thirdweb-dev/js/assets/70776780/9b5cd307-eaf5-4ff5-90c0-a6e1da86e209)

The error occurs in one of two scenarios, a user comes to our site, connects and the chain that is in their wallet is not one of the supported chains. Or, a user connects their wallet while on one of the supported chains, then goes into metamask switches to a non supported chain, and then it errors out. I realize if I were to remove the supported chains array, then I would get the array of default chains, but unfortunately that does not include "celo" so we would run into this error as we are building on celo right now. See video example:


https://github.com/thirdweb-dev/js/assets/70776780/2e2f6fd0-80af-4f7e-bcc7-0f3ee958c60b

So it seems if I limit my app to only a few chains, then I will encounter this, are you able to recreate?

**Comment by MananTank** [comment]
Hmm, I'll have to look into your code to see what's the root cause here. 

Can you share how you are setting up the `<ThirdwebProvider />`?

**Comment by NathanFrank285** [comment]
@MananTank Hey yah I am following this blog post: https://blog.thirdweb.com/guides/how-to-support-multiple-chains-in-your-dapp/

See below for the full shot of how we have it set up

![Screenshot 2023-07-27 at 1 25 55 PM](https://github.com/thirdweb-dev/js/assets/70776780/59319668-d737-4e2e-8656-55fab81709b2)

**Comment by MananTank** [comment]
Hmm, that won't work - you can't just pass a string `"celo"` because it's not one of the default supported chains - you need to pass the entire chain object from `@thirdweb-dev/chains` package 

```ts
import { Celo } from '@thirdweb-dev/chains';
```

**Comment by NathanFrank285** [comment]
@MananTank I'll go ahead and change this, but it is what I got from your blog post showing the recommended way to make the app multichain. Either way, the issue still persists whether I use the string or the entire chain object. See screenshot from this [blog post ](https://blog.thirdweb.com/guides/how-to-support-multiple-chains-in-your-dapp/)where it says to use the chain slug:
<img width="785" alt="Screenshot 2023-07-28 at 2 53 52 PM" src="https://github.com/thirdweb-dev/js/assets/70776780/079edcd2-14b6-4611-b346-e569bc5876ad">

**Comment by NathanFrank285** [comment]
Hey @MananTank thanks for putting this together, I'll be sure to switch it around on my frontend. It seems though in the sandbox when I switch my wallets chain to avalanche, it crashes, do you get this same error? This is what I was referring to above having some functionality to handle that error

**Comment by MananTank** [comment]
Hey @NathanFrank285 - No, I'm not able to replicate that.  For me, the app is not crashing when switching to avalanche. See below video: 

https://github.com/thirdweb-dev/js/assets/22043396/7a969d5b-0176-4895-8923-cc9b774322fa
