### ISSUE TITLE
Events reading error 

### ISSUE THREAD

**Issue by Raziur306** [thirdweb-dev/js#1381]
I have deployed my contract on sepola test net. And at the time when I put code to observe event this error is showing in my React app. And at the same time others function not fetching data from Blockchain Network.

![image](https://github.com/thirdweb-dev/js/assets/75040026/34b07b21-5386-4495-ac54-ad9f98aa5309)

**Comment by joaquim-verges** [comment]
@Raziur306 could you share the code that produces that error?

Also for events, try reducing the block range, you can for example fetch events from the last 20,000 blocks by passing

`fromBlock: -20000` 

In the filter param

**Comment by Raziur306** [comment]
//voter registration event
    const { data: event } = useContractEvents(contract, "EventName");

**Comment by joaquim-verges** [comment]
Try

```const { data: event } = useContractEvents(contract, "EventName", {
  fromBlock: -20000
});
```
