### ISSUE TITLE
fatal: not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by engelzero** [thirdweb-dev/js#141]
When trying to install @thirdweb-dev/react in NextJS project

**Comment by joaquim-verges** [comment]
Do you have git installed on your machine?

**Comment by engelzero** [comment]
Yes - I think the migration to the monorepo has caused this.

**Comment by engelzero** [comment]
I have no issue installing the sdk and etherjs they install fine, just thirdweb react

**Comment by engelzero** [comment]
Not sure if it's a caching issue could it be that yarn is trying to install it from https://github.com/thirdweb-dev/react and not the new repo? It been archived

**Comment by engelzero** [comment]
`yarn cache clean` fixed it. Was a caching issue! Sneaky. Old reference to old repo. Closing this issue.

**Comment by joaquim-verges** [comment]
Thanks for sharing the solution! Might be useful to others 👍
