### ISSUE TITLE
[React] issue using wallet connect

### ISSUE THREAD

**Issue by Wagalidoom** [thirdweb-dev/js#1459]
I deployed my smart contract on Goerli Testnet and all the dApp work smooth using metamask from browser. But when connect through walletconnect on phone with metamask i face lot of errors such as
![image](https://github.com/thirdweb-dev/js/assets/43578243/f9365b09-e7ea-48e4-8ea4-27e43e5e143b)

or now
![image](https://github.com/thirdweb-dev/js/assets/43578243/12dcca6e-f9a2-4d6b-b57e-ef29a51c9a14)

but i not even used zerion with thirdweb

Here the code of my connect button component
![image](https://github.com/thirdweb-dev/js/assets/43578243/4c90ca89-5113-4590-bb00-9e78b3d6ea87)

and the ThirdWeb Provider:
![image](https://github.com/thirdweb-dev/js/assets/43578243/ab643da3-eb2d-434e-bbd8-192a9054fee2)

**Comment by MananTank** [comment]
@Wagalidoom - I can't replicate the error. Can you clear the cache and retest? Are you still facing this issue?

**Comment by MananTank** [comment]
Hi @Wagalidoom  Can you try connecting to Metamask with WalletConnect in https://vite-typescript-starter-git-mnn-goerli-test.thirdweb-preview.com/ - Are you able to replicate the issue there?
