### ISSUE TITLE
useNFTs hook not returning all NFTs for the contract

### ISSUE THREAD

**Issue by nagrawal3** [thirdweb-dev/js#1485]
I am using useNFTs hook from thirdweb to get all the nfts issued on the polygon mainnet chain. Total NFTs returned doesn't contain all NFTs issued by the contract.

NFT Contract: `0x95e6603e219e6D08A9AE46f29201fA1610FA76B4`

Total NFT count on contract is 70 with id between 0-69, and I am only receiving 68 with id between 0-67.
Above contract has 2 NFTs burned/transferred to zero address.

```js
import { useNFTs, useContract } from '@thirdweb-dev/react';
import { useState, useEffect } from 'react';
import { zeroAddress } from 'viem';

export type UserType = {
  address: string,
  name: string,
  id?: string,
  uri?: string,
}

export function useBadgeUsers(addressOrName: string, {
  filterZeroAddress = false,
  startIndex = 0,
  addressCount = 100
}) {
  const [users, setUsers] = useState<UserType[]>([]);
  const { contract } = useContract(addressOrName);
  const { data: nfts, error } = useNFTs(contract, { start: startIndex, count: addressCount });

  if (error) {
    console.log('Error fetching NFTs from given address', error);
  }

  useEffect(() => {
    let usersArray = nfts?.map(nft => ({
      address: nft.owner as string,
      name: nft.metadata.name as string,
      id: nft.metadata.id as string,
      uri: nft.metadata.uri as string
    }));

    if (filterZeroAddress) usersArray = usersArray?.filter((user) => user.address != zeroAddress)
    if (usersArray) setUsers(usersArray as []);
  }, [nfts, filterZeroAddress]);

  return users;
}
```

Verified the results by running Alchemy curl command to received all NFTs issued by the contract:

```curl
curl --request GET \
     --url 'https://polygon-mainnet.g.alchemy.com/nft/v2/<Alchemy API Key>/getNFTsForCollection?contractAddress=0x95e6603e219e6D08A9AE46f29201fA1610FA76B4&withMetadata=true&startToken=0&limit=100' \
     --header 'accept: application/json'
```

Let me know if anyone else faced similar issue, or have some solution

**Comment by nagrawal3** [comment]
> https://thirdweb.com/polygon/0x95e6603e219e6D08A9AE46f29201fA1610FA76B4/explorer

@joaquim-verges that is correct, is there a way using the thirdweb library to fetch NFTs not assigned to `zeroAddress`?

**Comment by joaquim-verges** [comment]
@nagrawal3 the way you're filtering makes sense, but the problem is on the contract - you would need a way to tell how many total nfts have been minted regardless of burned.

Another option would be to use events, filtered by `from` as the zero address https://portal.thirdweb.com/typescript/sdk.contractevents.getevents
