### ISSUE TITLE
Bad performance: getClaimIneligibilityReasons

### ISSUE THREAD

**Issue by ifelsedeveloper** [thirdweb-dev/js#1510]
We are in the process of validating whether a specific user is eligible for claiming before the minting process is initiated. This validation involves utilizing the "getClaimIneligibilityReasons" function. It appears that during its current implementation, the function waits for all relevant data to be received before proceeding with the eligibility checks.

Is it possible to divide this process into separate steps? The proposed approach involves the function initially verifying the claim quantity and promptly returning the corresponding reason if the threshold is exceeded. I have successfully implemented this streamlined check, resulting in significantly improved performance. Unlike the current situation where "getClaimIneligibilityReasons" takes up to 18 seconds to complete and involves numerous requests to the backend.

Hence, kindly consider the following sequence for validation:

Verify Whitelist Status
Check Claim Quantity
Evaluate Balance
Address Other Potential Ineligibility Reasons
It is important to note that there is no requirement to await the completion of all checks before proceeding. This approach ensures a more efficient and responsive validation process.

**Comment by joaquim-verges** [comment]
Thanks for the report @ifelsedeveloper - agree that this method has room to improve. Do you want to do a PR with your changes? otherwise i can take it

**Comment by joaquim-verges** [comment]
would you be able to share a test case? as a quick win I've opened #1516
