### ISSUE TITLE
Error Initialise SDK via fromSigner / fromPrivateKey: "Must call super constructor"

### ISSUE THREAD

**Issue by regina-c** [thirdweb-dev/js#1519]
I am getting a reference error when initialising the ThirdwebSDK - "Must call super constructor in derived class before accessing 'this' or returning from derived constructor". This only happen on my deployed site but it the same code I have using works fine on my localhost. 

Not sure if anyone getting the same error and know how to troubleshoot this? 

References:  

- I had allowed all domains
- No bundle IDs configured 

<img width="495" alt="Screenshot 2023-08-22 at 5 19 18 pm" src="https://github.com/thirdweb-dev/js/assets/92702070/940cdd6f-1ada-4855-9266-304681b54d4f">

- My code looks something like this - which I had tried both fromPrivateKey and fromSigner and they both doesn't even initialise on deployed site. I get the reference error "Must call super constructor in derived class before accessing 'this' or returning from derived constructor" before console logging 'sdk successfully launched'. 

```
onChange={async () => {
            const signer = provider?.getSigner();
            let rolesSet = false;
            if (signer && account === '0x123') {
              if (chainId === item.chainID) {
                try {
                  // const sdk = ThirdwebSDK.fromSigner(signer, '', {
                  //   clientId: 'xxx',
                  // });
                  const sdk = new ThirdwebSDK.fromPrivateKey(
                    'xxx',
                    '',
                    { clientId: 'xxx' },
                  );
                  console.log('sdk successfully launched');
                  const contract = await sdk.getContract(item.contractAddress);
                  console.log('successfully getContract');
                  if (!rolesSet) {
                    await contract.roles.setAll({
                      admin: ['0x123'],
                      minter: ['0x123']
                    });
                    rolesSet = true;
                    console.log('successfully setAll');
                  }
                  await request(api.collection, { method: 'PUT', data: { ...item, setAll: !val } });
                } catch (error) {
                  alert(error);
                }
                actionRef.current?.reload();
              } else {
                alert('Please switch to the network of the collection');
              }
            } else {
              alert('Only admin is allowed');
            }
          }}

```

**Comment by iketw** [comment]
@regina-c thanks for opening this issue.

I noticed you do `new ThirdwebSDK.fromPrivateKey(` in your code, but please note that `fromPrivateKey` is a static method so no need to add `new` in that call. Please, just do:

`ThirdwebSDK.fromPrivateKey` or `ThirdwebSDK.fromSigner`

**Comment by regina-c** [comment]
> @regina-c thanks for opening this issue.
> 
> I noticed you do `new ThirdwebSDK.fromPrivateKey(` in your code, but please note that `fromPrivateKey` is a static method so no need to add `new` in that call. Please, just do:
> 
> `ThirdwebSDK.fromPrivateKey` or `ThirdwebSDK.fromSigner`

I had tried without `new` in the call and it the same error still occurred.

**Comment by iketw** [comment]
@regina-c I just tried running:

```
const sdk = ThirdwebSDK.fromPrivateKey(
        'my-private-key',
        'ethereum',
      );
const address = await sdk.wallet.getAddress();
console.log('address', address);
```

and it worked for me. Could you confirm the version of the sdk you're using?
