### ISSUE TITLE
Using Thirdweb in different languages

### ISSUE THREAD

**Issue by emin-karadag** [thirdweb-dev/js#1543]
Hello,
I want to use "ThirdWeb" in my application. But does ThirdWeb have different language support?
For example; I want to use ThirdWeb in Turkish language. How can I do it?
Thanks.

**Comment by joaquim-verges** [comment]
@emin-karadag do you mean the documentation?

**Comment by emin-karadag** [comment]
@joaquim-verges I want to make all texts appearing in the interface suitable for Turkish language.

**Comment by joaquim-verges** [comment]
I see. Is it for all text in the dashboard, or in UI components like the connect wallet button?

**Comment by emin-karadag** [comment]
@joaquim-verges 
Hello,

Button text customization available. But I want to customize all other texts.
For this;
- Is there an embedded language enetgrason?
- If there is no embedded language integration, how should we do different language integrations?

Thank you.

**Comment by joaquim-verges** [comment]
For the button we allow changing most of the text, but for those that can't be overriden right now the best way would be to provide your own UI. 

Would love help on localizing the components properly though, if you're up for it please put up a PR

**Comment by emin-karadag** [comment]
Yes, I am ready to give the necessary assistance.

**Comment by etnlbck** [comment]
@joaquim-verges I was wondering if this might be an opportunity to add i18n into the mix. Is that something that has been considered by the team? I'd be interested in helping to implement that.

**Comment by joaquim-verges** [comment]
@etnlbck yes! We've been actively discussing it and it now that our new components are out it should be easy to expose a way to add localization.

Would def appreciate help on it though! Feel free to open a draft PR and we can iterate on it together

**Comment by iketw** [comment]
@etnlbck in our next release you're going to be able to pass your own custom `locale` prop object in order to translate our SDKs, both React and React Native. We are also going to ship with support for Japanese and Spanish.

ReactNative is already out: https://blog.thirdweb.com/changelog/adding-support-for-japanese-and-spanish-react-native/

and you can test React by importing `@thirdweb-dev/react@nightly`.

**Comment by iketw** [comment]
Closing this for now since you can now pass your own locale object :)
