### ISSUE TITLE
Could not fetch bytecode for contract at 0x370C............ on chain 11155111

### ISSUE THREAD

**Issue by Raziur306** [thirdweb-dev/js#1573]
**I have deployed my contract on sepolia test net but I face this issue.** 

![image](https://github.com/thirdweb-dev/js/assets/75040026/d7ca4a01-93ea-4514-8952-a17424952450)

**I have already set my chain id to Sepolia**

![image](https://github.com/thirdweb-dev/js/assets/75040026/9feceb59-e86f-49f4-9182-5a72ae294674)

What is the issue My Metamask wallet have Sepolia Test net with chain the same chainID

**Comment by joaquim-verges** [comment]
Looks.lile.youre getting some 401 responses for rpc calls which indicates something is missing in your API key configuration.

If you check the error message of those 401 responses in the network tab it'll tell you what's missing.
