### ISSUE TITLE
Smart Wallet doesn't work with Magic Link social login

### ISSUE THREAD

**Issue by jarrodwatts** [thirdweb-dev/js#1708]
Code in `ThirdwebProvider` (react sdk):

```jsx
        smartWallet(
          magicLink({
            apiKey: process.env.NEXT_PUBLIC_MAGIC_LINK_API_KEY as string,
            oauthOptions: {
              providers: ["google"],
            },
            type: "auth",
          }),
          {
             factoryAddress: "0xf766DB9d6b0587B74637003767071C24063c5457",
             gasless: true,
          };
        ),
```

- Mumbai network
- Social login works without the smart wallet wrapping it

The error I get:

```
Failed to auto connect wallet
Error: Cannot read properties of undefined (reading 'getSigner')
```

![image](https://github.com/thirdweb-dev/js/assets/35651410/80d13f42-a672-4260-ba38-6a30216c77c3)

**Comment by joaquim-verges** [comment]
thanks for the report @jarrodwatts ! looking into this

**Comment by jarrodwatts** [comment]
Same issue on `v4.1.8`

**Comment by joaquim-verges** [comment]
@MananTank can you look into this?

@jarrodwatts the error is on auto connection after refreshed, does it work with the normal connection flow?

**Comment by MananTank** [comment]
I can replicate the issue. Figured out why this is happening, I'm working on fixing this

**Comment by MananTank** [comment]
@jarrodwatts This issue has been fixed and is available in latest `@nightly` version
