### ISSUE TITLE
detailsBtn in Connect Wallet is not working

### ISSUE THREAD

**Issue by mominnawaf** [thirdweb-dev/js#1718]
Though the functionality is working fine. I cant customize the UI
My Code In React SDK
`<ConnectWallet
  detailsBtn={() => {
    return <button>Help</button>;
  }}
/>`

I still see the default Connect button

**Comment by iketw** [comment]
Thanks for reporting this @mominnawaf. The `detailsBtn` prop is to customize the button after your wallet is connected. You can see it by connecting any wallet and check what gets rendered after:

https://portal.thirdweb.com/react/react.connectwallet#props

**Comment by mominnawaf** [comment]
Thanks for responding back. Is there a to customise the connect button before hand?

**Comment by iketw** [comment]
@mominnawaf you can change the title as you mentioned and then theming is the other thing you can change. You can play with the different settings here: https://thirdweb.com/dashboard/wallets/connect

**Comment by mominnawaf** [comment]
@iketw I think there should be a hook to programmatically open the connect modal.

**Comment by MananTank** [comment]
@mominnawaf you can programmatically open the modal using the `useSetIsWalletModalOpen ` hook

```ts 
import { useSetIsWalletModalOpen } from '@thirdweb-dev/react'

const setIsWalletModalOpen = useSetIsWalletModalOpen();

const openModal = () => setIsWalletModalOpen(true);
```
