### ISSUE TITLE
A common API Metadata issue and how to solve it for my use case.

### ISSUE THREAD

**Issue by IntrepidShape** [thirdweb-dev/js#1741]
[Repost from the discord with modification.] Note that the attached metadata can be found [in the original discord support post](https://discord.com/channels/834227967404146718/1159756829304295455/1161189715245011065)

Tagging: @warengonzaga

# 👋 A common API Metadata issue and how to solve it for my use case.

Hi  so it appears that the smart contract metadata for 

PulseX V1 SwapRouter address  = 0x98bf93ebf5c380C0e6Ae8e192A7e2AE08edAcc02
and 
PulseX V2 SwapRouter address = 0x165C3410fC91EF562C50559f7d2289fEbed552d9

Are NEVER going to be updated, imported or resolved without manual intervention. 

I also would like to note that this is a common error motif, I'm not sure of a good solution, perhaps another way to verify metadata other than https://sourcify.dev/  as it also has it's own issues, one of them being it doesn't support Pulsechain. Perhaps the ability to throw in a abi/metadata .json file and optimistically see if it works - It'd probably be a good idea to scope said metadata to the individual user/web3 connect - perhaps that's a lot of overhead i'm just theorizing here. Perhaps I am also misunderstanding the workflow here too - do feel free to point that out if thats the case.

There is a solution to at least get what I would like to do done, it's not a perfect solution but I think "good enough" is better than "not at all". 

1. I've attached a metadata.json file [in the original discord post](https://discord.com/channels/834227967404146718/1159756829304295455/1161189715245011065)- it's taken from [here]( https://scan.pulsechain.com/address/0x165C3410fC91EF562C50559f7d2289fEbed552d9/contracts#address-tabs)
2. Place it wherever you place metadata for your API to register it.
3. Repeat so it's done for both 0x98bf93ebf5c380C0e6Ae8e192A7e2AE08edAcc02 and 0x165C3410fC91EF562C50559f7d2289fEbed552d9

Thats its really.
Thank you in advanced.

PS I've added an alternate version of the metadata should the first one not work, the alternate has worked for me just using vanilla js and querying the blockchain directly. You may need to go one bracket layer deeper to the "ABI" section.

**Comment by warengonzaga** [comment]
Hey @joaquim-verges or @MananTank can you take a look here?

**Comment by joaquim-verges** [comment]
@IntrepidShape thanks for reporting this.

We'll take a look at the metadata and see what can be done there.

In the meantime, you can always pass an ABI to `getContract()` and `useContract()` if you have it to bypass the automatic abi resolution. That should solve your problem immediately.
