### ISSUE TITLE
thirdweb v4.0.1 useWalletConnect Hooks does not work

### ISSUE THREAD

**Issue by Kkirito1** [thirdweb-dev/js#1748]
![image](https://github.com/thirdweb-dev/js/assets/41469229/56b9e4e0-de1e-403c-8e76-cd208a74470c)
This seems to be a problem with walletconnect

**Comment by joaquim-verges** [comment]
thanks for reporgibnt this @Kkirito1 - we're looking into this

**Comment by iketw** [comment]
@Kkirito1 thanks for reporting this. Could you share more context on when you're getting this error? Is it when disconnecting/connecting? Even when you get this error in the console, does the wallet still works as expected?

If it does, then this may be on the walletconnect side and they are working on muting these errors:

According to this issue: https://github.com/WalletConnect/walletconnect-monorepo/issues/2983 : 

```
FYI, we're patching most of the No matching key. errors and if you encounter any errors/behavior that blocks the client from operating normally feel free to open a new issue 💯
```
