### ISSUE TITLE
[CRITICAL]Transactions not working Thirdweb Dashboard through wallet connect on Polygon Mainnet Chain

### ISSUE THREAD

**Issue by hammasxd** [thirdweb-dev/js#1829]
![Capture](https://github.com/thirdweb-dev/js/assets/142976137/843c3803-2604-4d39-9c03-8402ba8c7833)
getting overflow error while minting token on Polygon scan.
here is the code 

`
const {contract}= useContract(params.contractAddress);
const metadataNFT = {
  name: "Hanami",
  description: "Hanami from Jujutsu Kaizen",
};
    const mintNFT = async ()=>{
     await contract?.erc721.mint(metadataNFT).then((tr)=>{
      console.log('this is minted nft : ',tr).catch(err){
      console.log(err)
};
     })
    }
`
this is the contract address on Polygon : 0x24696D2D5328C9c2D361C370637e1CE827dbcDF0
Error occurs when i click on confirm in my Metamask Mobile wallet(conencted through WC) but transaction still continues and get confirmed on chain.

![Capture2](https://github.com/thirdweb-dev/js/assets/142976137/a318cf99-6f88-4f07-a517-d77cef9d4b87)
Ive tested it on https://thirdweb.com/dashboard/contracts/deploy
It is showing the same error when deploying on polygon mainnet
it is a thirdweb related issue kindly solve it fast its fatal.

I've tested the same code with a collection contract on Elysium Testnet `chainID : 1338  contractAddress:0x103A1b9194c78f38A40CfB3F21d59B521E5072AD`
and it is working fine but on Polygon Mainnet it is showing this issue.
TO INVOKE THIS
deploy a collection contract on Polygon
test this function after setingup providers and conencting MM through WC using connect wallet UI component
and running the provided mint function.

**Comment by kien-ngo** [comment]
Hi @hammasxd thanks for reporting this. We're looking into this atm.
Any chance you can share the whole error message?

**Comment by Fabioepb** [comment]
Hey @kien-ngo, I'm not sure on wether this is on WalletConnect's side or Thirdweb-dev, so I've left extra information on the issues of both libraries.

This seems to happen with other mobile wallets as well, I've tested MetaMask mobile wallet, Trust Wallet and Fireblocks. They all experience the same NUMERIC_FAULT error.

The actual error message:
overflow [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-overflow ] (fault="overflow", operation="toNumber", value="39429324759775805056870346697879527774854152784605618705975791686434047059132", code=NUMERIC_FAULT, version=bignumber/5.7.0)

Steps to reproduce:

Connect any Mobile Wallet app using WalletConnect (Through thirdweb-dev/sdk)
Sign any transaction
Tx approval is sent to mobile wallet
Approve the tx
The transaction will fail after being parsed on the front end
note: The transaction does succesfully get submitted to the blockchain, it's just the parsing afterwards for the hash that causes the issue

**Comment by Wagalidoom** [comment]
I have the exact same issue (overflow error while the transaction still valid) on Goerli chain. Someone find the way to fix this? Thank you.

**Comment by wadader** [comment]
Similiar issue. I'm not minting but I get a minting overflow error. Similarly, while using wallet connect. Following

**Comment by maximeclaisse** [comment]
Similar issue here, with a marketplace contract, calling buyDirectlisting

**Comment by kien-ngo** [comment]
Ty everyone for reporting, we will let you know once there's a fix rolled out for this issue!

**Comment by MananTank** [comment]
Hi @hammasxd, @Fabioepb, @maximeclaisse, @wadader, @Wagalidoom 

The root cause of this issue was the polygon RPC - we have fixed this issue now
