### ISSUE TITLE
thirdweb.com authorization with wallet connect

### ISSUE THREAD

**Issue by Wagalidoom** [thirdweb-dev/js#1831]
Hello everyone,

I'm using the ConnectWallet component in React, and, while i don't have any trouble to connect with Metamask, a pop up always show when connect from Wallet Connect through iphone (ios). This behaviour started sinced the last version of thirdweb sdk.

Screenshot of the pop up:
![thirdweb](https://github.com/thirdweb-dev/js/assets/43578243/fa73bd6f-afd9-489c-ae43-4dfc915901d8)

How i can get rid of this issue ? Thank you

**Comment by MananTank** [comment]
@Wagalidoom 

Hi 👋,  We have not made any changes to the MetaMask connection, This is the expected behavior with the latest Metamask wallet app on iOS
