### ISSUE TITLE
Error connecting to Coinbase wallet on mobile

### ISSUE THREAD

**Issue by mertcankose** [thirdweb-dev/js#1857]
I encountered such an error while connecting to my coinbae wallet in React Native.
My Provider

  const activeChain = Ethereum;
  return (
    <ThirdwebProvider
      activeChain={activeChain}
      clientId={THIRD_WEB_PROJECT_ID}
      supportedChains={[Ethereum]}
      supportedWallets={[
        walletConnect(),
        metamaskWallet({
          projectId: WALLET_CONNECT_PROJECT_ID,
          recommended: true,
        }),
        rainbowWallet({
          projectId: WALLET_CONNECT_PROJECT_ID,
        }),
        coinbaseWallet(),
        trustWallet({
          projectId: WALLET_CONNECT_PROJECT_ID,
        }),
        localWallet(),
      ]}>
.........

![thirdweb-coinbase](https://github.com/thirdweb-dev/js/assets/56760896/a49f8b6d-35ec-42cd-aea7-7d1920cb4414)

**Comment by iketw** [comment]
@mertcankose thanks for reporting this. Could you list the steps you took to get this screen? Does this page opens up when you select Coinbase?

**Comment by mertcankose** [comment]
> @mertcankose thanks for reporting this. Could you list the steps you took to get this screen? Does this page opens up when you select Coinbase?

I select coinbase and press the allow button in the app, after pressing the allow button it redirects me here.

**Comment by iketw** [comment]
> > @mertcankose thanks for reporting this. Could you list the steps you took to get this screen? Does this page opens up when you select Coinbase?
> 
> I select coinbase and press the allow button in the app, after pressing the allow button it redirects me here.

Please, find below a couple of questions to better understand the issue:

1. You open your React Native app
2. You press the ConnectWallet button
3. (what is the allow button you press?)
4. I redirects you to the browser?

Could you share the version of the `@thirdweb-dev/react-native` package you're using?

**Comment by mertcankose** [comment]
> > > @mertcankose thanks for reporting this. Could you list the steps you took to get this screen? Does this page opens up when you select Coinbase?
> > 
> > 
> > I select coinbase and press the allow button in the app, after pressing the allow button it redirects me here.
> 
> Please, find below a couple of questions to better understand the issue:
> 
> 1. You open your React Native app
> 2. You press the ConnectWallet button
> 3. (what is the allow button you press?)
> 4. I redirects you to the browser?
> 
> Could you share the version of the `@thirdweb-dev/react-native` package you're using?

the allow button in the coinbase app gives me a pop up, it says the app wants to access the following information and as soon as I press allow it redirects me to another browser.
    "@thirdweb-dev/react": "^4.0.8",
    "@thirdweb-dev/react-native": "^0.3.13",
    "@thirdweb-dev/react-native-compat": "^0.3.13",
    "@thirdweb-dev/sdk": "^4.0.7",
