### ISSUE TITLE
useSwitchChain does not switch the activeChain for ThirdwebProvider

### ISSUE THREAD

**Issue by tommaay** [thirdweb-dev/js#1868]
## Background
This issue is causing the `useContract` hook to be unusable. If I go from `Ethereum` chain to Polygon and pass a Polygon contract to `useContract`, the hook will fail because the `activeChain` in `ThirdwebProvider` is still `Ethereum`.  `activeChain` is currently passed as props to `ThirdwebProvider` and does not change.  

## Proposal
Set a state in `ThirdwebWalletProvider` that takes the `activeChain` value from props as the initial value. 
- When `useSwitchChain` is used to switch the chain, set the `activeChain` state to the chain that was called with `useSwitchChain` or a create a new hook like `useSwitchActiveChainForProvider`.

**Comment by kien-ngo** [comment]
cc. @MananTank @joaquim-verges

I think it's a good idea to have a `useSwitchActiveChain` or `useSwitchChainProvider` so that users can conveniently navigate between networks in a multichain application.

**Comment by tommaay** [comment]
I created a draft pr to show what it might look like: [pr](https://github.com/thirdweb-dev/js/pull/1869)

**Comment by mertcankose** [comment]
> I created a draft pr to show what it might look like: [pr](https://github.com/thirdweb-dev/js/pull/1869)

same issue! I am waiting to approve your commit as soon as possible

**Comment by tommaay** [comment]
> > I created a draft pr to show what it might look like: [pr](https://github.com/thirdweb-dev/js/pull/1869)
> 
> same issue! I am waiting to approve your commit as soon as possible

They won't be exposing a hook to handle the activeChain switch so we will have to do that in our apps
