### ISSUE TITLE
[Cloudflare Security Challenge] IPFS upload error during deployment

### ISSUE THREAD

**Issue by pcdotfan** [thirdweb-dev/js#1940]
I am experiencing an issue with the thirdweb CLI during deployment, specifically when uploading files to IPFS. The process fails with a 403 Forbidden error, which appears to be triggered by Cloudflare's security mechanisms.

## Error Details

**Command Executed:** `npx thirdweb@latest deploy`

**Error Message:** 
```
✖ Error uploading metadata
Error: Failed to upload files to IPFS - 403 - Forbidden - <!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title>...
```

- The issue seems to be linked to a Cloudflare security challenge, which typically requires human interaction to resolve.
- Using a VPN to bypass firewall restrictions does not alleviate the problem.
- The error page indicates a need to "Enable JavaScript and cookies to continue," suggesting a browser-based security check.

What if implementing a mechanism within the CLI to handle Cloudflare's security challenge during the IPFS upload process? This could involve prompting the user to complete the Cloudflare challenge through a browser (popping up a new window, etc) whenever a 403 error is detected during the deployment.

@warengonzaga

**Comment by warengonzaga** [comment]
Thank for the report @pcdotfan tagging @joaquim-verges and @MananTank here to take a look.

**Comment by JackMateWeb** [comment]
Same issue here!
This security challenge page cannot pop up automatically. When I tried to intercept and copy this security challenge page to the browser, it could no longer connect and displayed Cannot Get/, so I hope that a browser window can pop up automatically to allow you to conduct a security challenge.

**Comment by joaquim-verges** [comment]
@pcdotfan @JackMateWeb where are you guys located? Wonder if you're hitting a geo block.

**Comment by JackMateWeb** [comment]
at Hong Kong

**Comment by waynessa** [comment]
China mainland

**Comment by pcdotfan** [comment]
> @pcdotfan @JackMateWeb where are you guys located? Wonder if you're hitting a geo block.

Hi @joaquim-verges I am in mainland China

**Comment by joaquim-verges** [comment]
@pcdotfan @JackMateWeb can you try again now? We just did some changes on cloudflare

**Comment by pcdotfan** [comment]
Works like a charm, thanks for your help!

From: Joaquim Verges ***@***.***>
Date: Wednesday, November 15, 2023 at 14:39
To: thirdweb-dev/js ***@***.***>
Cc: Weng Weiyu ***@***.***>, Mention ***@***.***>
Subject: Re: [thirdweb-dev/js] [Cloudflare Security Challenge] IPFS upload error during deployment (Issue #1940)

- External Email -



@pcdotfan<https://github.com/pcdotfan> @JackMateWeb<https://github.com/JackMateWeb> can you try again now? We just did some changes on cloudflare

**Comment by JackMateWeb** [comment]
@joaquim-verges 
Thanks for your help, it works perfectly now! great

**Comment by warengonzaga** [comment]
Glad it works now @pcdotfan @JackMateWeb, we'll close this now. Should you require further assistant please don't hesitate to reach out to us. Responded too on our Discord ticket thread.

Thanks @joaquim-verges for the quick fix!
