### ISSUE TITLE
ThirdwebSDK problem

### ISSUE THREAD

**Issue by bolisteward** [thirdweb-dev/js#196]
Hi, I'm beginning with ThirdwebSDK and I got the next problem. 

const sdk = new ThirdwebSDK("mumbai");
            ^

TypeError: ThirdwebSDK is not a constructor

I followed the instructions using first step.

```
const ThirdwebSDK = require ("@thirdweb-dev/sdk");
const sdk = new ThirdwebSDK("mumbai");
```

**Comment by jnsdls** [comment]
hi @bolisteward I believe that should be
```
const { ThirdwebSDK } = require("@thirdweb-dev/sdk");
const sdk = new ThirdwebSDK("mumbai");
```
also where did you find that code-snippet? Would love to hunt it down and fix it / have it fixed as well!

**Comment by bolisteward** [comment]
Thank u, jajaj
