### ISSUE TITLE
Cannot access 'AbstractWallet' before initialization

### ISSUE THREAD

**Issue by ChrisCates** [thirdweb-dev/js#1999]
Using next `13.5.3`. The module does not work.

![image](https://github.com/thirdweb-dev/js/assets/1561091/0972d695-0783-4a6d-851c-017a4518b8e8)

The code is as follows (Next App Directories):

```typescript
'use client'
import { Suspense } from 'react'
import {
  ThirdwebProvider,
  metamaskWallet,
  coinbaseWallet,
  walletConnect,
  ConnectWallet
} from '@thirdweb-dev/react'

export interface LoginI {}

export function Login({}: LoginI) {
  return (
    <Suspense>
      <ThirdwebProvider
        supportedWallets={[metamaskWallet(), coinbaseWallet(), walletConnect()]}
      >
        <div className="container page center login-page">
          <div className="panel login-panel">
            <ConnectWallet />
          </div>
        </div>
      </ThirdwebProvider>
    </Suspense>
  )
}

export default Login
```

Any clues?

**Comment by MananTank** [comment]
Hi @ChrisCates - If you are using Next.js App router - please refer to "Next.js > App router" in https://portal.thirdweb.com/react/getting-started on how to use the client components like `ThirdwebProvider`, `ConnectWallet` etc
