### ISSUE TITLE
[CLI] Rename "Initial commit from Create thirdweb app"

### ISSUE THREAD

**Issue by nachoiacovino** [thirdweb-dev/js#204]
We should rename this initial commit to be `Initial commit from npx thirdweb create`

One line change, good first contribution :)

Remember to add a changeset!

**Comment by simonlim94** [comment]
Hi @nachoiacovino , thanks for opening an easy issue for beginner. I have made a PR for this https://github.com/thirdweb-dev/js/pull/246. Let me know if any changes is required
