### ISSUE TITLE
@thirdweb-dev/sdk incompatibility issue with ethers v6

### ISSUE THREAD

**Issue by sebpalluel** [thirdweb-dev/js#2057]
I'm encountering an issue related to `ethers v6` with `@thirdweb-dev/sdk`.

The specific error is: 
`Cannot find module 'ethers/lib/utils' from '../../../node_modules/.pnpm/@thirdweb-dev+sdk@4.0.19_ethers@6.9.0_typescript@5.3.2/node_modules/@thirdweb-dev/sdk/dist/index-0cf99325.cjs.dev.js'`.
This appears to stem from a change in the file path structure in `ethers v6` (refer to [this issue](https://github.com/ethers-io/ethers.js/issues/3703#issuecomment-1696823942) for more details).

To work around this, I've temporarily resorted to creating an alias for ethers as `"ethers6": "npm:ethers@^6.9.0"`, allowing us to use it throughout the project via `import { ethers } from 'ethers6';`, while also maintaining `ethers v5.7.2`.

However, this solution is quite hacky and not ideal. It would be greatly beneficial for `@thirdweb-dev/sdk` to extend support to `ethers v6`, especially considering it has reached a stable release. Currently, `@thirdweb-dev/sdk` is the sole dependency in our stack that is causing compatibility issues with `ethers v6`.

**Comment by bennettl** [comment]
+1 Is this on the roadmap?

**Comment by joaquim-verges** [comment]
@sebpalluel @bennettl thank you for submitting the issue - we're actively working on an upgrade that will allow to use the SDK alongside ethers v6, v5 and viem. 

Will update here with progress updates - cc @jnsdls

**Comment by juniardys** [comment]
I have the same issues in here, hope this will be updated ASAP

**Comment by GENERATIONART** [comment]
Any update on timing?

**Comment by joaquim-verges** [comment]
We're close to opening up the alpha version of our new SDK which will be compatible with ethers 5, 6 and viem.

Here's the alpha tester sign up link if you're interested: https://docs.google.com/forms/d/e/1FAIpQLSfMTy_1ZKPHAGIs8hQAlLfR_Xur1tw5soF_fEumFawdBEhK5g/viewform?usp=send_form

Adding @saminacodes and @jnsdls for 👀

**Comment by GENERATIONART** [comment]
Our lead dev Sameer will be filling this out. Thank you!

**Comment by AcmeNiles** [comment]
@joaquim-verges -- we need Ether 6 compatibility for the SDK, and have filled up the form to get access to the alpha version. Could you please give us access? Thanks!

**Comment by saminacodes** [comment]
Hey Acme! 

Here are some links to get you started:

- [Documentation](https://portal.thirdweb.com/typescript/v5)
- [Repository](https://github.com/thirdweb-dev/js/tree/alpha)
- [Feedback form](https://forms.gle/FhdupeAuCVQqwSA59)

Let us know if you have any questions and please [join our #sdk-v5-alpha Discord channel](https://discord.com/channels/834227967404146718/1204607960899264562) to directly speak with the engineers on the project. :D

**Comment by hexforcesy** [comment]
> @joaquim-verges -- we need Ether 6 compatibility for the SDK, and have filled up the form to get access to the alpha version. Could you please give us access? Thanks!

Needed

**Comment by GENERATIONART** [comment]
Please give us an update. I'm about to have torecode half of my marketplace that connects to seaport js at this point. We filled out the form and got nothing in return. At this point its delaying our launch... PLEASE HELP!

**Comment by hexforcesy** [comment]
Do we have a date when this will be released? We desperately requires Ethers v6 support

**Comment by jnsdls** [comment]
hey @hexforcesy @GENERATIONART we have an `ethers6adapter` in the new version of our SDK that would be the path forward here:

[New Docs](https://portal.thirdweb.com/typescript/v5)
[Ethers6Adapter](https://portal.thirdweb.com/references/typescript/v5/ethers6Adapter)

Note that this will only work with the new version of the SDK (currently in alpha, the APIs are about to be stable today or tomorrow and we'll go to beta)

**Comment by jnsdls** [comment]
also cc @AcmeNiles @bennettl @juniardys ☝️

**Comment by hexforcesy** [comment]
ETA on beta?

**Comment by joaquim-verges** [comment]
@hexforcesy beta is out today! https://blog.thirdweb.com/changelog/introducing-the-unified-thirdweb-sdk/

**Comment by joaquim-verges** [comment]
posting the ethers6 adapter docs here for anyone looking for it: https://portal.thirdweb.com/typescript/v5/adapters#ethers-v6

**Comment by jnsdls** [comment]
the new SDK `npm i thirdweb` is now stable as `v5` it is fully compatible with ethers v5, ethers v6 and viem (including adapters for each)

**Comment by hexforcesy** [comment]
Thank you

We will deploy this today.

Regards
________________________________
