### ISSUE TITLE
Uncaught ReferenceError: Buffer is not defined (Cloudflare Worker)

### ISSUE THREAD

**Issue by tleperou** [thirdweb-dev/js#2100]
# Problem

Execution failure of `@thirdweb-dev/sdk` because of the specific Node's Buffer implementation.

Eventually, I `pnpm i -D buffer` and manually exposed `Buffer` in `index-4471f8a3.cjs.dev.js` with `var Buffer = require('buffer');`. It worked.

What do you recommend to get it work nicely ?

# Context

- running against Web standards – Cloudflare Worker
- version `@thirdweb-dev/sdk@^4.0.23`
- Cloudflare has a [node compat mode](https://developers.cloudflare.com/workers/configuration/compatibility-dates/#nodejs-compatibility-flag); but being on or off, I've not seen effect.

I went through issues and past PRs. Notably, 

- [[SDK] Remove usages of Buffer to decode bytecodes](https://github.com/thirdweb-dev/js/pull/205/files) 
- and #459 that mentions such usages.

# Error message

```sh
service core:user:api: Uncaught ReferenceError: Buffer is not defined
  at index.js:143465:24
  at index.js:143466:7 in node_modules/.pnpm/@thirdweb-dev+sdk@4.0.23_ethers@5.7.2_typescript@5.3.3/node_modules/@thirdweb-dev/sdk/dist/index-4471f8a3.cjs.dev.js
  at index.js:19:50 in __require2
  at index.js:153530:17 in node_modules/.pnpm/@thirdweb-dev+sdk@4.0.23_ethers@5.7.2_typescript@5.3.3/node_modules/@thirdweb-dev/sdk/dist/sdk-b603cef4.cjs.dev.js
  at index.js:19:50 in __require2
  at index.js:156612:15 in node_modules/.pnpm/@thirdweb-dev+sdk@4.0.23_ethers@5.7.2_typescript@5.3.3/node_modules/@thirdweb-dev/sdk/dist/thirdweb-dev-sdk.cjs.dev.js
  at index.js:19:50 in __require2
  at index.js:157109:24 in node_modules/.pnpm/@thirdweb-dev+sdk@4.0.23_ethers@5.7.2_typescript@5.3.3/node_modules/@thirdweb-dev/sdk/dist/thirdweb-dev-sdk.cjs.js
  at index.js:19:50 in __require2
  at index.js:157149:26
```

**Comment by jnsdls** [comment]
hey @tleperou, we're actively working on a major version that's going to solve this. We have ran into the same problem of trying to use the SDK inside cloudflare workers and not being able to. I will ping you the alpha version of this new SDK the moment the APIs are somewhat stable so you can use it.

One thing that would be useful to know is a rough outline of what you're trying to accomplish within the cloudflare worker, it can help me prioritize those features early in the new SDK version. :)

**Comment by tleperou** [comment]
Thanks for the info.

I'm just experimenting, so nothing specific here.

**Comment by 0xalecks** [comment]
About to start a new project using CF workers, will need this too. From light reading CF's docs, it seems that simply prefixing the nodejs core stuff with "node:" might do it.
https://developers.cloudflare.com/workers/runtime-apis/nodejs/buffer/

For ex: 
`import { Buffer } from 'node:buffer';`

Also, making sure to use only the Uint8Array methods would prob be helpful.

**Comment by tleperou** [comment]
Indeed it helped.

But the piece of code that imports Buffer comes from a thirdweb bundle. So, quiet inconvenient to change the instruction to using `node:buffer`.

Thanks for the tips about Uint8Array tho. I realised it using other lib too.

**Comment by 0xalecks** [comment]
@jnsdls

> we're actively working on a major version that's going to solve this. We have ran into the same problem of trying to use the SDK inside cloudflare workers and not being able to. 

Do you have a rough timeframe on this. Starting a new project and will need something sooner than later.. trying to gauge if we should wait on this or not. We talking days, weeks, months? Anything you can share would be great.

Thank you

**Comment by jnsdls** [comment]
sorry about the delay here folks, we'll start testing the new alpha version very soon

Here's the alpha tester sign up link if you're interested: https://docs.google.com/forms/d/e/1FAIpQLSfMTy_1ZKPHAGIs8hQAlLfR_Xur1tw5soF_fEumFawdBEhK5g/viewform?usp=send_form
