### ISSUE TITLE
data is not of type NFT[] when using useUnclaimedNFTs

### ISSUE THREAD

**Issue by mostafa-rio** [thirdweb-dev/js#2110]
Reproducing this bug is simple. Create an NFT Drop Contract on Thirdweb dashboard and try to fetch the unclaimed NFTs using useUnclaimedNFTs():
  const { data } = useUnclaimedNFTs(contract)

if you try to log the data you will notice that the type is different:

![Screenshot 2023-12-29 at 13 48 39](https://github.com/thirdweb-dev/js/assets/32630862/21147dc9-c115-49d7-9558-aee767556326)

**Comment by MananTank** [comment]
Hi @mostafa-rio Thanks for reporting this. I can confirm that the return type of hooks is incorrect. It should be type `UseQueryResult<NFTMetadata[]>` and not `UseQueryResult<NFT[]>` - We are fixing it and the fix will be released today
