### ISSUE TITLE
NFT Checkout / Payments not working

### ISSUE THREAD

**Issue by johanneskares** [thirdweb-dev/js#2111]
Hi Team,

Great to hear that you are releasing the NFT Checkout / Paymetsn feature. I tried getting it to run, but here are several issues:

1. I tried installing the React integration using `CheckoutWithCard` according to [this guide](https://portal.thirdweb.com/checkouts/checkout-with-card), but the Component doesn't exist in the package.
2. Then I tried the pure Javascript integration using `createCheckoutWithCardElement`. When I import the function, I receive this error in my Next.js project.
<img width="1015" alt="Screenshot 2023-12-29 at 12 10 58" src="https://github.com/thirdweb-dev/js/assets/1416628/b906951d-f90a-4e33-94fd-62cea96455be">

Edit: After editing the file and removing the `// const packageJson = require("../../package.json");` line from the file, which didn't seem super important, I now get this error inside the iframe.
<img width="548" alt="Screenshot 2023-12-29 at 12 34 37" src="https://github.com/thirdweb-dev/js/assets/1416628/72ace8dc-c1a3-4d34-be13-a16fc11a297a">

Is it even possible to use these packages, I'm confused.

**Comment by edisonlee55** [comment]
[`@thirdweb-dev/react@4.2.0`](https://github.com/thirdweb-dev/js/releases/tag/%40thirdweb-dev%2Freact%404.2.0) added `@thirdweb-dev/payments@1.0.0` as a dependency, which breaks the whole package by this issue, making it unusable.

**Comment by MananTank** [comment]
Hi @johanneskares, @edisonlee55  - This has been fixed in the latest version. Please update to the latest package to resolve this issue `@thirdweb-dev/react@4.2.3`
