### ISSUE TITLE
[SmartWallet] Enable gassless option per transaction.

### ISSUE THREAD

**Issue by alko89** [thirdweb-dev/js#2113]
Currently gasless option has to be enabled in the `SmartWalletConfig`. A great improvement would be to allow disabling this option per transaction, with optional config:

```typescript
const wallet = new SmartWallet(config);

await wallet.executeBatch([tx1, tx2], { gassless: false })

await wallet.send(tx, { gassless: false })
```

**Comment by joaquim-verges** [comment]
thanks for the PR @alko89 ! will get this in next week
