### ISSUE TITLE
ERC721 Staking contract methods not working in Google Chrome

### ISSUE THREAD

**Issue by alexey727** [thirdweb-dev/js#2123]
getStakeInfo from ERC721 Staking contract in Google Chrome. In Brave working

[
![Screenshot 2024-01-07 at 12 04 21](https://github.com/thirdweb-dev/js/assets/15924337/b274d201-0109-4d64-975f-052b698487a3)
](url)

**Comment by warengonzaga** [comment]
Hello @alexey727, could you please share your contract address for the staking? We'll try to replicate it on our end. Looking forward to your prompt response.

**Comment by alexey727** [comment]
Hello @warengonzaga 0xFA73ac9A2632228E82Cc4f6Eb459083bE19FB1c1 in BSC testnet
