### ISSUE TITLE
Update Magic Link dependency version in React SDK

### ISSUE THREAD

**Issue by jarrodwatts** [thirdweb-dev/js#2134]
The `@magic-sdk/provider` dependency is on version 13 and the latest version is 21

Later versions have cool new features like fiat-on-ramp that would be nice to have available in the react sdk 😁

**Comment by warengonzaga** [comment]
Hello @jarrodwatts, thank you for the update! 

I'll tag @adam-maj and @MananTank here for the update on the magic link provider.
