### ISSUE TITLE
useSetIsWalletModalOpen options

### ISSUE THREAD

**Issue by eth0izzle** [thirdweb-dev/js#2178]
When I'm using the `<ConnectWallet />` component I can pass in a bunch of `ConnectWalletProps` such as `modalSize`, etc.

But I can't seem to pass any options to `useSetIsWalletModalOpen` and calling it throws the default ThirdWeb UX.

Is there a way to customize the modal via this hook?

**Comment by MananTank** [comment]
Hi @eth0izzle - Currently this option is not exposed. I'll expose the API to do this ASAP. 

Also, Can you let us what UI you are trying to build with `useSetIsWalletModalOpen` hook?

**Comment by MananTank** [comment]
Hey @eth0izzle, A new hook `useSetWalletModalConfig` is added to customize the Modal config

Please update to latest version of `@thirdweb-dev/react` to use this hook

Refer to documentation for for info:  

https://portal.thirdweb.com/references/react/v4/useSetWalletModalConfig
