### ISSUE TITLE
Unmodified `thirdweb create contract` project does not compile

### ISSUE THREAD

**Issue by mefillluous** [thirdweb-dev/js#2229]
Running the lastest `npx thirdweb@latest create contract`

Then selecting:

- Foundry
- ERC721
- SignatureMint

Creates a project where `forge test` fails with the compilation error:

```
Error (6275): Source "@openzeppelin/contracts/utils/Address.sol" not found: File not found. Searched the following locations: "/home/silas/code/test-contract".
 --> node_modules/@thirdweb-dev/contracts/external-deps/openzeppelin/token/ERC20/utils/SafeERC20.sol:7:1:
  |
7 | import { Address } from "@openzeppelin/contracts/utils/Address.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

`Address.sol` is not vendored into thirdweb unlike the source `SafeERC20.sol` contract so adding a remapping to `foundry.toml` like this, does not help:

```
    '@openzeppelin/contracts=node_modules/@thirdweb-dev/contracts/external-deps/openzeppelin/',
```

However, I can pull in `@openzeppelin/contracts@4.9.5` then add a remapping like:

```
'@openzeppelin/=node_modules/@openzeppelin`
```

which does work, but it seems like this should work out the box, it also means I am working against an old version of the OZ contracts, which given recent security issues doesn't seem like a great idea.

In any case it seems clear the intention of having a tool to scaffold a project is meant to give a working set of dependencies out of the box

Versions:

```

❯ npx thirdweb@latest version
 💎 thirdweb v0.13.33 💎

❯ forge --version
forge 0.2.0 (4a36f53 2024-01-28T00:18:19.564681661Z)
```

**Comment by joaquim-verges** [comment]
@mefillluous thanks for reporting this and sorry for the late response. I believe this should be fixed in the latest release of @thirdweb-dev/contracts - could you give it another try?

Cc @nkrishang

**Comment by oliinyks** [comment]
'npx thirdweb@latest create --contract' - not working
{
  errno: -1,
  code: 'EPERM',
  syscall: 'uv_cwd'
}

**Comment by angalarodgers** [comment]
> 'npx thirdweb@latest create --contract' - not working { errno: -1, code: 'EPERM', syscall: 'uv_cwd' }

Use an older version of node. Worked for me.
