### ISSUE TITLE
Warning: Invalid DOM property ... (console screenshot attached)

### ISSUE THREAD

**Issue by saul-atomrigs** [thirdweb-dev/js#2296]
<img width="717" alt="스크린샷 2024-02-12 오후 5 11 22" src="https://github.com/thirdweb-dev/js/assets/82362278/7bae49bb-74d9-4f66-89da-91027db63fc7">
<img width="717" alt="스크린샷 2024-02-12 오후 5 49 46" src="https://github.com/thirdweb-dev/js/assets/82362278/d33b79ae-193a-48e7-907b-06396db76d06">
<img width="717" alt="스크린샷 2024-02-12 오후 5 49 34" src="https://github.com/thirdweb-dev/js/assets/82362278/34cdc79c-0e5d-4f0a-8cf6-aceab4b7fab9">

**Comment by MananTank** [comment]
Thanks @saul-atomrigs For reporting this. This is fixed in #2299

**Comment by saul-atomrigs** [comment]
Sure, glad to be helpful :)

and thanks for the fix
