### ISSUE TITLE
React Native SDK Yarn ios

### ISSUE THREAD

**Issue by Navip10** [thirdweb-dev/js#2320]
Hi @warengonzaga  thank you for reaching out on the discord, 
i could use some help/guidance on a project I am building. I am using the React Native SDK and started the build with "npx thirdweb create --template react-native-expo-starter" went through the whole environment set up and I'm up to the part where I could run "yarn iOS" when I run this everything seems to build fine and the IOS simulator does come up but then that's when I run into some errors preventing me from moving forward. I will attach images of this errors I'm seeing repeatedly, please help with any sort information you can provide. Im attaching photos below of my package.json and the errors im receiving in the console.

Thank You,
Navier Polanfco

![Image 2-15-24 at 12 53 PM](https://github.com/thirdweb-dev/js/assets/92967686/ca6c3626-5d8d-4bc5-85b1-c05dfd8ecd98)
![Screenshot 2024-02-16 at 6 31 39 PM](https://github.com/thirdweb-dev/js/assets/92967686/c3e233fc-06eb-4110-8ff4-789a222e92e6)
![Image 2-16-24 at 4 27 PM](https://github.com/thirdweb-dev/js/assets/92967686/1d7a2177-2ba4-4d84-a41e-be0f496a99f2)
![simulator_screenshot_3E4FF836-3BCB-4AB8-86E9-74F00FEC4B1D](https://github.com/thirdweb-dev/js/assets/92967686/a48ce4ab-1aeb-4a99-afaf-a342db5c1b53)
![simulator_screenshot_B73F33C6-960A-44EF-A16B-8BF75107F924](https://github.com/thirdweb-dev/js/assets/92967686/7b7cb058-346d-4961-be26-3f09812dda46)
![simulator_screenshot_D8986EFF-00C6-433F-A4C0-98656206EEF1](https://github.com/thirdweb-dev/js/assets/92967686/b375e5f9-aaeb-4678-9557-dc97a7671513)

**Comment by warengonzaga** [comment]
Hello @iketw can you take a look into this? Thanks!

**Comment by Navip10** [comment]
Thank you, @iketw if theres anything i could provide to help with diagnosing this problem of mine let me know. could use the help as soon as possible i've been trying to figure out the problem for 3 days now before coming for help.

**Comment by iketw** [comment]
Hi @Navip10, thanks for reporting this. The issue stems from the fact that since expo-application 5.8, the module has been migrate to a Native module. Please, run `npx expo install expo-application` in your app and re-run, this should fix your issue.

I'll make sure to update the templates.

**Comment by huy-lv** [comment]
> Hi @Navip10, thanks for reporting this. The issue stems from the fact that since expo-application 5.8, the module has been migrate to a Native module. Please, run `npx expo install expo-application` in your app and re-run, this should fix your issue.
> 
> I'll make sure to update the templates.

thanks, it worked

**Comment by Navip10** [comment]
@iketw it worked! thank you for getting back to me with a quick solution!

**Comment by warengonzaga** [comment]
Closing this issue, thanks @iketw for the quick fix.

Should you require any further assistance @Navip10 and @huy-lv let us know.
