### ISSUE TITLE
getting RPC error while doing txn on Arbitrum sepolia network

### ISSUE THREAD

**Issue by ap-allo** [thirdweb-dev/js#2353]
txn with goerli works fine but when I switch to arbitrum sepolia network it throws error when sending txn till yesterday it works fine

**Comment by joaquim-verges** [comment]
There was some downtime with Arbitrum in the pas couple of days, but I think it should be resolved now. Cc @jakeloo

**Comment by joaquim-verges** [comment]
@ap-allo let us know if you see anymore issues, closing for now
