### ISSUE TITLE
Not able to send transaction request on mobile..

### ISSUE THREAD

**Issue by mominnawaf** [thirdweb-dev/js#2423]
I have the following code

```ts
 const signer = useSigner() // somewhere above not undefined
          const transaction = {
            to: selectedCurrency?.receiver_address,
            value: utils.toWei(selectedCurrency.amount.raw_value_uint, 'wei')
          }
          const txResponse = await signer?.sendTransaction(transaction) //
```
the above works on desktop  when connected to Metamask extensions but on Metamask mobile its not working

Makes following request 
curl "https://5.rpc.thirdweb.com//?bundleId=undefined" 

Req payload : `{"id":1,"jsonrpc":"2.0","method":"test","params":[]}`
Res: `{"error":"Invalid chain"}` status: 400
btw I'm on Eth mainnet
the above code is in try catch however.. the catch block is not executed

PS: ScreenShots
![Screenshot 2024-03-07 233757](https://github.com/thirdweb-dev/js/assets/47545933/ffabfdd6-5eb4-4464-b95f-0df122f49487)
![Screenshot 2024-03-07 233804](https://github.com/thirdweb-dev/js/assets/47545933/c62be26c-50d4-4859-be14-3c5f9a7556e6)
![Screenshot 2024-03-07 233810](https://github.com/thirdweb-dev/js/assets/47545933/663e1cf1-73cd-485f-b51e-de10fb3bb4e1)

Refer to this video
[screen-capture.webm](https://github.com/thirdweb-dev/js/assets/47545933/86538728-81e6-4bb9-8497-76d6f9ebacf9)

**Comment by mominnawaf** [comment]
React SDK

**Comment by iketw** [comment]
@MananTank can you assist?

@mominnawaf can you double check your app is connected to Eth mainnet? Maybe do 

```
const chain = useChain();

console.log(chain?.chainId)
```

**Comment by mominnawaf** [comment]
@iketw it used to work until yesterday. regardless of which chain I connected to. 
PS: it don't work with Eth Mainnet.

**Comment by iketw** [comment]
@mominnawaf did you update the react package or make any other change? If not, can you try again?

Also, please, share which version of the react package you're on

**Comment by mominnawaf** [comment]
@iketw 
i'm on
```json  
 "@thirdweb-dev/react": "^4.1.7",
 "@thirdweb-dev/sdk": "^4.0.14",
 ```

**Comment by iketw** [comment]
@mominnawaf you're testing on Goerli, that testnet has been shutdown by the Ethereum foundation:

https://blog.thirdweb.com/goodbye-goerli-hello-sepolia/

Please, use Sepolia moving forward for testing.

Also, make sure you're passing the clientId to ThirdwebProvider instead of a secretKey.

**Comment by jnsdls** [comment]
hey @mominnawaf it looks like you're passing a `secret key` in the url path, that is reserved for the `client id`, secret key should be sent in headers as `x-secret-key` -> can you make sure you've set them correctly in your `<ThirdwebProvider>`?

also, since you have now publicly posted your secret key you should create a new api key as the secret key should *stay secret*

**Comment by mominnawaf** [comment]
@iketw @jnsdls I passed the clientId as well.issue still persists. also since its optional [According to this](https://portal.thirdweb.com/react/v4/ThirdwebProvider#clientId) I removed, yet no outcomes.

**Comment by iketw** [comment]
@mominnawaf which chain are you testing on now? Can you share the same output you shared above with the new error you're getting?
