### ISSUE TITLE
Error: Signer address does not match payload address "newly created account here"

### ISSUE THREAD

**Issue by dholliday** [thirdweb-dev/js#2478]
Hello,

I am following the tutorial here https://www.youtube.com/watch?v=mtaf6VtgcRo from the repo https://github.com/thirdweb-example/web3-idle-game-youtube/blob/main/pages/_app.tsx and when i try to sign in i get the error:

`Error: Signer address does not match payload address "newly created account here"`

I am using the Sepolia testnet for this.

It's erroring in the POST to http://localhost:3000/api/auth/login with payload:

```
{
    "payload": {
        "type": "evm",
        "domain": "localhost:3000",
        "address": "NEW ACCOUNT ADDRESS FROM ACCOUNT CONTRACT",
        "statement": "Please ensure that the domain above matches the URL of the current website.",
        "version": "1",
        "chain_id": "11155111",
        "nonce": "2e33f9cc-4c6b-481f-affb-d9915e6bddb6",
        "issued_at": "2024-03-14T00:07:24.217Z",
        "expiration_time": "2024-03-14T00:52:25.355Z",
        "invalid_before": "2024-03-14T00:32:25.355Z"
    }
}
```

Response

```
{
    "error": "Signer address does not match payload address 'NEW CONTRACT ADDRESS'"
}
```

The code at /api/auth/login is:

```
import { ThirdwebAuth } from "@thirdweb-dev/auth/next";
import { PrivateKeyWallet } from "@thirdweb-dev/auth/evm";

export const { ThirdwebAuthHandler, getUser } = ThirdwebAuth({
  wallet: new PrivateKeyWallet(process.env.WALLET_PRIVATE_KEY || ""),
  domain: process.env.DOMAIN || "",
});

export default ThirdwebAuthHandler;
```

Any ideas?

**Comment by joaquim-verges** [comment]
thanks for the report @dholliday - just checking, did you intentionally replace the address with `NEW CONTRACT ADDRESS` in that error reponse you pasted?

**Comment by dholliday** [comment]
@joaquim-verges  Yes, i intentionally masked it

**Comment by joaquim-verges** [comment]
@dholliday ok i debugged this, the issue is that for smart walllet authentication, the server needs to do a RPC call to verify the signature against the smart account contract. We recently enforced clientId/secretKey for RPC, which means that you need to pass your secretKey to the `ThirdwebAuth` constructor like this:

```
export const { ThirdwebAuthHandler, getUser } = ThirdwebAuth({
  domain: process.env.NEXT_PUBLIC_THIRDWEB_AUTH_DOMAIN || "",
  thirdwebAuthOptions: {
    secretKey: process.env.THIRDWEB_AUTH_SECRET_KEY,
  },
  wallet: new PrivateKeyWallet(process.env.THIRDWEB_AUTH_PRIVATE_KEY || ""),
});
```

**Comment by watase-eth** [comment]
Updated the repo from the video as well. Should work now.
