### ISSUE TITLE
"Connect a wallet" first in ConnectEmbed

### ISSUE THREAD

**Issue by eth0izzle** [thirdweb-dev/js#2534]
Is there a way to make the "Connect a wallet" button appear first in the `ConnectEmbed`? If not can it be added as an option? I'd rather not re-write the entire modal just to swap the order.

![image](https://github.com/thirdweb-dev/js/assets/97316/14fe6a79-f50d-4bb3-a390-f5ae9b7b9870)

**Comment by joaquim-verges** [comment]
@eth0izzle thank you for the feedback - we've considered this and will likely add it in the next few weeks, but curious how do you expect the UI to behave? list of wallets up top and a button below to switch to embedded wallet UI?

Also the code is open source, would love a contribution for this!

**Comment by eth0izzle** [comment]
Just as simple as the below.

![image](https://github.com/thirdweb-dev/js/assets/97316/1f8f5fa2-c6ad-416e-bea2-2f249bb88e75)

We regularly get users completey missing the "Connect a wallet option" as it sits below a traditonal account login + the large Continue CTA. Being "Web3 first" with the wallet options first would be a nice option. You might not even need to add a separate option and just honor the order of the `supportedWallets` array, e.g.,

![image](https://github.com/thirdweb-dev/js/assets/97316/269546d0-121d-421e-852a-c043ca0aa09e)

`const isWeb3First = supportedWallets[supportedWallets.length - 1].id == EmbeddedWallet.id`
