### ISSUE TITLE
Cannot use `useSigner()` with ThirdwebProvider from SDK v5

### ISSUE THREAD

**Issue by matthewmorek** [thirdweb-dev/js#2548]
The `ThirdwebProvider` between v4 and v5 are not compatible, and are currently throwing the following error in Next.js:

> Error: Invariant failed: `useSigner()` hook must be used within a `<ThirdwebProvider/>` or `<ThirdwebSDKProvider/>` component

This makes it impossible to implement anything other than basic wallet authentication.

The migration guide for v5 mentions the following, but this won't work with the new `ThirdwebProvider`:
> In React, you can obtain the current signer using the useSigner hook, and convert it when needed using the ethers5Adapter:
```tsx
import { useSigner } from "@thirdweb-dev/react";
import { ethers5Adapter } from "thirdweb/adapters/ethers5";
 
const signer = useSigner();
 
const onClick = async () => {
  // convert the signer to used with the new SDK
  const account = await ethers5Adapter.signer.fromEthers(signer);
  // then use the new SDK normally
  const transaction = prepareContractCall({ ... });
  await sendTransaction({
    transaction,
    account,
  });
};
```

## Setup
```tsx
// ThirdwebProvider.tsx
'use client'

import { ReactNode } from 'react'
import { ThirdwebProvider as Provider } from 'thirdweb/react'

export default function ThirdwebProvider({
  children,
}: {
  children: ReactNode
}) {
  return <Provider>{children}</Provider>
}
```

```tsx
// RootLayout
const RootLayout = async ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <body>
        <ThirdwebProvider>
          {children}
        </ThirdwebProvider>
      </body>
    </html>
  )
}
```

```tsx
// component file (under one of routes)
import { useSigner } from '@thirdweb-dev/react'
import { useState } from 'react'
import { ethers5Adapter } from 'thirdweb/adapters/ethers5'

export default function Buy() {
  const [provider, setProvider] = useState(null)
  const signer = useSigner()

  useEffect(() => {
    async function getProvider() {
      const provider = await ethers5Adapter.getProvider()
      setProvider(provider)
    }
    getProvider();
  }, [setProvider, signer])

  return <></>
}
```

Documentation mentions that both `@thirdweb-dev/*` and `thirdweb` SDKs can be used side by side, but in React this is impossible due to those `ThirdwebProvider` providers being incompatible.

For example you cannot use `useClient()` with v5 provider or `useActiveWallet()` with v4 provider.

**Comment by joaquim-verges** [comment]
@matthewmorek good call out, will add to the migration guide!

**Comment by ivanminutillo** [comment]
im having the same issues with other functions like useNFTs which are missing from SDK5, should i use the same solution? ps. doesn't this defeat all the optimisations made between the 2 releases if we should use them together?

**Comment by eth0izzle** [comment]
> im having the same issues with other functions like useNFTs which are missing from SDK5, should i use the same solution? ps. doesn't this defeat all the optimisations made between the 2 releases if we should use them together?

Yeah I also figured this out after hours of migration. Not sure how they could called V5 SDK a stable release when it has a bunch of missing features (e.g., Auth) and _has_ to be used alongside the "old" V4 SDK—effectively increasing your bundles sizes. Stick to V4 until V6 comes out 😂
