### ISSUE TITLE
Metamask (chrome extension) no longer able execute smart contract functions / calls

### ISSUE THREAD

**Issue by kennaku1** [thirdweb-dev/js#2561]
As of last week & the recent updates, I am no longer able to execute smart contracts calls using the Metamask Chrome Extension. 
1. When trying to execute calls, nothing happens, no errors are surfaced.
2. I tried the same exact function call with Metamask Mobile + Other wallets and it works perfectly fine.

Has anyone else experienced these issues?

**Comment by joaquim-verges** [comment]
@kennaku1 thanks for the report - can you give me a bit more info? is this from your app? what version of the SDKs are you using?

**Comment by kennaku1** [comment]
@joaquim-verges, Yes using the latest version of the react SDK, I am using the connect button component and also using the latest version of Google Chrome on a MacOS

**Comment by MananTank** [comment]
Hey @kennaku1 Can you try disabling the MetaMask extension and enabling it back and see if that fixes the issue for you?

**Comment by kennaku1** [comment]
@MananTank,

I tried this but unfortunately did not work for me. I have also tried another device

**Comment by kennaku1** [comment]
Is this issue fixed in the latest build?

**Comment by MananTank** [comment]
Hey @kennaku1 - We are not able to replicate the issue. Can you specify which smart contract calls you are testing that is not working for you?
