### ISSUE TITLE
The imToken wallet is missing some of the information in the connect modal

### ISSUE THREAD

**Issue by unix** [thirdweb-dev/js#2578]
### Brief

When using the `imTokenWallet` from the `@thirdweb-dev/react` package, the modal doesn't display the icon and description properly, and there's a missing text prompt in the connection window.

### Current behavior

1. imToken wallet icon has rough edges in dark mode;
2. imToken wallet lost its name and description;
3. Click `Don't have imToken wallet?`:
  a. Unable to jump to the specified page or no content on the page.

### Demo

- [issue repo](https://github.com/unix/thirdweb-imtoken-issue)
- [online preview](https://thirdweb-imtoken-issue.vercel.app/)

### Screenshot

<img width="728" alt="image" src="https://github.com/thirdweb-dev/js/assets/11304944/0607571d-bad2-4f29-92dc-12ca672620d5">

**Comment by jnsdls** [comment]
hi, could you update the version of `@thirdweb-dev/react` to `4.4.25`

I believe this was likely fixed in: https://github.com/thirdweb-dev/js/pull/2562 which is included in that version.
