### ISSUE TITLE
Mobile MetaMask Dead Link

### ISSUE THREAD

**Issue by warengonzaga** [thirdweb-dev/js#2625]
We receive a report about Unified SDK that when you choose MetaMask on mobile browser it will redirect to this path `metamask.app.linkwc/` instead of `metamask.app.link/wc`

@jnsdls @joaquim-verges could you please check this? Thanks!

**Comment by jnsdls** [comment]
checking now!

**Comment by jnsdls** [comment]
I believe I found it, will open a PR with the fix shortly
