### ISSUE TITLE
Issue with Tailwind CSS className Styles Not Being Applied to TransactionButton

### ISSUE THREAD

**Issue by seangray-dev** [thirdweb-dev/js#2703]
I am encountering an issue with the `TransactionButton` component where Tailwind CSS classes passed through the `className` prop do not seem to apply. Despite providing custom Tailwind utility classes, the button does not reflect these styles, and it appears that default styles are taking precedence or the Tailwind classes are being ignored altogether.

Thank you for looking into this issue. I am happy to provide further details if needed and look forward to a resolution.

**Comment by joaquim-verges** [comment]
@seangray-dev try setting the tailwind properties as !important by prefixing them with a !

**Comment by seangray-dev** [comment]
> @seangray-dev try setting the tailwind properties as !important by prefixing them with a !

@joaquim-verges Thanks for your response! Was literally just about to update my comment. Tried this it does indeed work. 

Is there a more permanent fix potentially that avoids the use of `!important` being discussed? I'd be interested in investigating further.

**Comment by joaquim-verges** [comment]
Agreed that it would be great to not require that. And we should at a minimum document it.

The code is all open so feel free to make a PR to fix this! Cc @MananTank

**Comment by seangray-dev** [comment]
I'd be happy to look at finding a solution and contributing, please assign this to me if you'd like. Also, I believe there are other ui components with similar behaviour as well. I will report back on this.
