### ISSUE TITLE
Error using React Query

### ISSUE THREAD

**Issue by alireza-sharifpour** [thirdweb-dev/js#2709]
I'm encountering an issue with Thirdweb while using React Query.

I use both Thirdweb and React Query in my app. Thirdweb works fine without React Query, but when I add React Query, I get this error: 

``Error: No QueryClient set, use QueryClientProvider to set one.``

And when I pass QueryClient to ThirdwebProvider, I get another error:

``Type 'QueryClient' is missing the following properties from type 'QueryClient': queryCache, mutationCache, logger, defaultOptions, and 4 more.``

I use React Query v5.29.0, and I checked that Thirdweb uses the same. My Thirdweb versions are:

``"@thirdweb-dev/react": "^4.4.33", "@thirdweb-dev/sdk": "^4.0.59".``

Do you know what the problem is?

**Comment by jnsdls** [comment]
@alireza-sharifpour the version of `@tanstack/react-query` in use in `@thirdweb-dev/react` is still version `4` - purely based on what you're describing here I *assume* the version of `@tanstack/react-query` you are using in your project is version `5`.

If my guess is correct these are your options:
- downgrade `@tanstack/react-query` to `v4` in your application (if possible)
- upgrade from `@thirdweb-dev/react` to `thirdweb` [Docs](https://portal.thirdweb.com/typescript/v5) [Migration guide](https://portal.thirdweb.com/typescript/v5/migrate)
