### ISSUE TITLE
Error Invalid chain

### ISSUE THREAD

**Issue by diamondskrt** [thirdweb-dev/js#2738]
I'm encountering an issue with thirdweb-dev/react in my React project and as result I can't get my smart contract metadata via useContractMetadata method

```
Failed to load resource: the server responded with a status of 400

Request URL: https://80001.rpc.thirdweb.com/xxx
Request Method: POST
Status Code: 400 Bad Request

error: "Invalid chain"

Logger.throwError Error: missing revert data in call exception;
```

`@thirdweb-dev/react": "^4.4.33`

**Comment by jnsdls** [comment]
hi there @diamondskrt,

as [previously announced](https://blog.thirdweb.com/goodbye-mumbai-hello-amoy/) we have stopped supporting `Mumbai (80001)` earlier today.

[You can read more about this here](https://blog.thirdweb.com/deprecation-of-mumbai-testnet/)

Thanks for reaching out!
