### ISSUE TITLE
AutoConnect doesn't work when building custom UI experiences for AA wallets (not using ConnectButton)

### ISSUE THREAD

**Issue by mmahdigh** [thirdweb-dev/js#2750]
When using the `ConnectButton` component, the auto connection works correctly and as expected. However, when you create a custom UI for the connect wallet experience and use `useConnect` hook to connect to a smart wallet whose signer is an embedded wallet, it doesn't work or even trigger (1).

Here's the manual connection part:

```ts
const createSmartWallet = async () => {
  const socialEOA = inAppWallet();
  await socialEOA.connect({
    client,
    strategy: "google",
  });
  const wallet = smartWallet(smartWalletConfig);
  const EoaAccount = socialEOA.getAccount()
  await wallet.connect({
    personalAccount: EoaAccount!,
    client,
  })

  return wallet
}

const login = async () => {
    const wallet = await connect(createSmartWallet)
}
```

Here's how the `AutoConnect` component is used:

```tsx
'use client'

export const smartWalletConfig = {
  factoryAddress: factoryAddress,
  chain: activeChain,
  gasless: true,
}

export const wallets = [inAppWallet()]


export const ThirdwebAutoConnect = () => {

  const bool = useIsAutoConnecting()

  useEffect(() => {
    console.log("is auto connecting?", bool)
  }, [bool])

  return (
    <AutoConnect
      client={client}
      wallets={wallets}
      accountAbstraction={smartWalletConfig}
    />
  )
}

```

`ThirdwebAutoConnect` is used in the root layout beneath the `<body>`.  
The `smartWalletConfig` and `client` objects are shared in the code snippets.

1- I'm saying it's not even triggered because the log in the second code snippet shows just `false`. So the `AutoConnect` component is accessible however it never logs `true` so perhaps something is happening before [this line](https://github.com/thirdweb-dev/js/blob/1f79973/packages/thirdweb/src/react/core/hooks/connection/useAutoConnect.tsx#L270).

Environment:

```json
"thirdweb": "^5.3.1",
"next": "^14.0.3",
"react": "18.2.0",
"react-dom": "18.2.0",
"typescript": "5.3.2",
```

**Comment by MananTank** [comment]
Hey @mmahdigh - The autoconnect for Smart Wallet is not yet supported outside the `ConnectButton` component. We'll fix this as soon as possible

**Comment by mmahdigh** [comment]
> Hey @mmahdigh - The autoconnect for Smart Wallet is not yet supported outside the `ConnectButton` component. We'll fix this as soon as possible

Thanks for your reply! We're going to have a launch in a month and badly need this feature. I was wondering if you could give us some pointers so maybe we could make a PR fixing this.

Thanks!

**Comment by MananTank** [comment]
@mmahdigh As a workaround - you can do this for now in your app: 
when you connect smart wallet with a personal wallet - save the personal wallet id in localStorage

Example 

```ts
const account = await wallet.connect()
localStorage.setItem('last-connect-personal-wallet-id', wallet.id) // <-- 
const smartWallet = createWallet('smart', smartWalletOptions);
await smartWallet.connect({ personalAccount: account, client: client })
```

On page load - read the wallet id from stoarge, create a wallet using `createWallet(id)`, connect the personal wallet and then connect the smart wallet

Example
```ts
const personalWalletId = localStorage.getItem('last-connect-personal-wallet-id');
const personalWallet = createWallet(personalWalletId);
const account = await personalWallet.autoConnect({ client: client })
const smartWallet = createWallet('smart', smartWalletOptions);
await smartWallet.connect({ personalAccount: account, client: client })
```

**Comment by joaquim-verges** [comment]
@mmahdigh we're tackling this issue in #2853 

you'll be able to pass the `accountAbstraction` options to `useConnect` which will handle connecting and auto connecting smart wallets for any EOA

**Comment by joaquim-verges** [comment]
PR is merged and docs updated: https://portal.thirdweb.com/connect/account-abstraction/get-started#3-connect-smart-accounts-in-your-application
