### ISSUE TITLE
signTypedData malfunction

### ISSUE THREAD

**Issue by warengonzaga** [thirdweb-dev/js#2776]
> I’m trying to use the new sdk to sign a typed data but after signing I’m getting an error on my console saying “Failed to sign message” 
const activeAccount =useActiveAccount 
const signature =activeAccount?.signTypedData({domain,types,value}):  has anyone had this issue before?

Posted originally from our Discord community server.
Link: https://discord.com/channels/834227967404146718/1229239680323686401

cc: @jnsdls

**Comment by gregfromstl** [comment]
Hey @jnsdls I can take this if you'd like

@warengonzaga are they able to provide the domain, types, and value values? I'm not able to reproduce with my own data

**Comment by warengonzaga** [comment]
> Hey @jnsdls I can take this if you'd like
> 
> @warengonzaga are they able to provide the domain, types, and value values? I'm not able to reproduce with my own data

Let me ask the community member to provide the data for you. Thank you for your help!

**Comment by warengonzaga** [comment]
I added the link to the exact post from our community server on Discord.

**Comment by LeeVee127** [comment]
{
  "domain": {
      "name": "Permit2",
      "chainId": 137,
      "verifyingContract": "0x000000000022D473030F116dDEE9F6B43aC78BA3"
  },
  "types": {
      "PermitBatch": [
          {
              "name": "details",
              "type": "PermitDetails[]"
          },
          {
              "name": "spender",
              "type": "address"
          },
          {
              "name": "sigDeadline",
              "type": "uint256"
          }
      ],
      "PermitDetails": [
          {
              "name": "token",
              "type": "address"
          },
          {
              "name": "amount",
              "type": "uint160"
          },
          {
              "name": "expiration",
              "type": "uint48"
          },
          {
              "name": "nonce",
              "type": "uint48"
          }
      ]
  },
  "primaryType": "PermitBatch",
  "message": {
      "details": [
          {
              "token": "0x6d80113e533a2c0fe82eabd35f1875dcea89ea97",
              "amount": {
                  "type": "BigNumber",
                  "hex": "0x01668bde1750a210"
              },
              "nonce": 0,
              "expiration": 1713780071
          },
          {
              "token": "0x45c32fa6df82ead1e2ef74d17b76547eddfaff89",
              "amount": {
                  "type": "BigNumber",
                  "hex": "0xfa144cca4cc18a"
              },
              "nonce": 0,
              "expiration": 1713780073
          }
      ],
      "spender": "0x7bB7d6C35bDe08e9f969039EDc575Daa27AA680A",
      "sigDeadline": 1713780073
  }
}

**Comment by gregfromstl** [comment]
Hey @LeeVee127, thanks for providing the data. Could you try specifying the `amount` fields as a regular BigInt instead of the hex value in a typed object? If you need to convert the hex values at runtime you can do `hexToBigInt("0xfa144cca4cc18a")`. Let me know if this works

It should look something like this:
```
const typedData = {
    domain: {
        name: "Permit2",
        chainId: 11155111,
        verifyingContract: "0x000000000022D473030F116dDEE9F6B43aC78BA3",
    },
    types: {
        PermitBatch: [
            {
                name: "details",
                type: "PermitDetails[]",
            },
            {
                name: "spender",
                type: "address",
            },
            {
                name: "sigDeadline",
                type: "uint256",
            },
        ],
        PermitDetails: [
            {
                name: "token",
                type: "address",
            },
            {
                name: "amount",
                type: "uint160",
            },
            {
                name: "expiration",
                type: "uint48",
            },
            {
                name: "nonce",
                type: "uint48",
            },
        ],
    },
    primaryType: "PermitBatch" as const,
    message: {
        details: [
            {
                token: "0x6d80113e533a2c0fe82eabd35f1875dcea89ea97",
                amount: hexToBigInt("0xfa144cca4cc18a"),
                nonce: 0,
                expiration: 1713780071,
            },
            {
                token: "0x45c32fa6df82ead1e2ef74d17b76547eddfaff89",
                amount: hexToBigInt("0xfa144cca4cc18a"),
                nonce: 0,
                expiration: 1713780073,
            },
        ],
        spender: "0x7bB7d6C35bDe08e9f969039EDc575Daa27AA680A",
        sigDeadline: 1713780073,
    },
};
```

**Comment by LeeVee127** [comment]
Thanks @gregfromstl the solution worked perfectly. and thank you @warengonzaga for your help in opening the issue.

**Comment by jnsdls** [comment]
thanks for the assist @gregfromstl! glad its working @LeeVee127!
