### ISSUE TITLE
how to use setIsWalletModalOpen on v5

### ISSUE THREAD

**Issue by mateodaza** [thirdweb-dev/js#2784]
I don't see any option to open the modal programmatically, can you guys help out?

**Comment by jnsdls** [comment]
hey @mateodaza I don't think we support this yet, but we'll take a look! cc: @MananTank

**Comment by MananTank** [comment]
@mateodaza - This is in our roadmap, We'll soon add a hook for this (ideally by next week)

**Comment by MananTank** [comment]
Hi @levitatejay - This feature is now available in the latest version of `thirdweb` package via `useConnectModal` hook 

Please refer to https://portal.thirdweb.com/references/typescript/v5/useConnectModal for more information:

**Comment by levitatejay** [comment]
@MananTank Thanks that's worked great for sign in. I haven't been able to find a way to programatically open the Detail Modal (with the Send/Receive/Buy). Do you know if there's a way?
