### ISSUE TITLE
get list of all the transactions by contract address

### ISSUE THREAD

**Issue by jeckvld** [thirdweb-dev/js#2849]
Hi! I use react's `<ConnectWallet/>` to connect to `SafeWallet` for multi-sig purpose. I use `sepolia` test network. When I click on the "Transactions" button it loads nothing and throws an error in the console logs. When I use `contract.events.getAllEvents()` I get all the past events, but they don't have any `eventName` (set as an empty string). How can I get a list of all the transactions including past & pending in `sepolia` network?
![image](https://github.com/thirdweb-dev/js/assets/24661867/233707cf-219b-481b-a7de-4602ab389274)
![image](https://github.com/thirdweb-dev/js/assets/24661867/5e365fe0-af8c-42d7-be53-7a5d9e01c85e)

**Comment by joaquim-verges** [comment]
for a list of transactions, your best bet is to use an indexer solution. We don't currently provide one but its on our roadmap!
