### ISSUE TITLE
Getting error when use useSendTransaction

### ISSUE THREAD

**Issue by kai2703** [thirdweb-dev/js#2876]
"thirdweb": "^5.13.0"
I use inAppWallet (email) and call mutateAsync from useSendTransaction, but getting this error

<img width="756" alt="image" src="https://github.com/thirdweb-dev/js/assets/166356084/592167d4-13c6-4dfd-b468-480182f87f6c">

**Comment by kai2703** [comment]
Sample code
```
      const tx = prepareContractCall({
        contract: getContract({
          client,
          chain,
          address,
        }),
        method: {
          inputs: [],
          name: "mint",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      });
      const { transactionHash } = await mutateAsync(tx);

```

**Comment by gregfromstl** [comment]
Hey @kai2703, happy to take a look at this for you. Are you able to share the contract address and chain you're using so we're able to reproduce the issue?

**Comment by kai2703** [comment]
> Hey @kai2703, happy to take a look at this for you. Are you able to share the contract address and chain you're using so we're able to reproduce the issue?

I can share that I use it on Arbitrum Sepolia

**Comment by gregfromstl** [comment]
> > Hey @kai2703, happy to take a look at this for you. Are you able to share the contract address and chain you're using so we're able to reproduce the issue?
> 
> I can share that I use it on Arbitrum Sepolia

What contract address is it? Do you have a link to the contract in the dashboard?

**Comment by joaquim-verges** [comment]
@kai2703 this should be fixed in the latest version of the SDK - can you confirm on your end?
