### ISSUE TITLE
useContractEvents: {code: -32602, message: 'invalid params', data: 'from block is greater than latest block'}

### ISSUE THREAD

**Issue by RamanSB** [thirdweb-dev/js#2964]
`useContractEvents` and passing in the contract param works fine, however when changing network to another Network in my case (moving from Sepolia to Base) - I refetch a new contract and pass that in to useContractEvents, this now causes an issue regarding the blockNumber passed to the from param within: 

https://github.com/thirdweb-dev/js/blob/8d1aaffb68b48310b3c0a3006c86aa63cf8cbdef/packages/thirdweb/src/react/core/hooks/contract/useContractEvents.ts#L84

For more detail please [view this issue.](https://github.com/RamanSB/Token-Bank/issues/1)

**Comment by jnsdls** [comment]
@gregfromstl any chance #2958 solved this?

**Comment by RamanSB** [comment]
Unfortunately not. I still see the error message.

https://token-bank.vercel.app/ (Deposit on Sepolia, then move to Base, inspect the console, you will begin to see the error below) - I've also raised this issue with a @Yash094 , CSE from ThirdWeb on Discord who is actively looking in to this I believe? 

<img width="658" alt="image" src="https://github.com/thirdweb-dev/js/assets/13969478/a1dd8189-70b7-47cf-8176-92319d21bf91">

**Comment by gregfromstl** [comment]
Hey @RamanSB, thanks for opening an issue. This is a known bug with our RPCs and we're actively working on a fix. I'll let you know as soon as it's resolved

**Comment by RamanSB** [comment]
Any update on this @gregfromstl ?

**Comment by RamanSB** [comment]
Pinging this thread for an update

**Comment by gregfromstl** [comment]
Hey @RamanSB thanks for the ping, there's an issue on our RPCs that the team is still working through. I'll followup with them now

**Comment by joaquim-verges** [comment]
@RamanSB we did an update to our RPC infra that should have resolved this - can you confirm?

**Comment by RamanSB** [comment]
I can confirm the issue no longer exists. Thank you
