### ISSUE TITLE
defineChain not overrided the value from thirdweb chainlist

### ISSUE THREAD

**Issue by iamcryptofennec** [thirdweb-dev/js#3022]
My defineChain config
![image](https://github.com/thirdweb-dev/js/assets/128964/d43058e5-21b2-4b4a-9341-beef6fb885b1)

My Popup
- Icon doesn't be changed
- Explorers url not included (undefined)
![image](https://github.com/thirdweb-dev/js/assets/128964/ae1fe8c7-0491-4d5c-9a09-a579457cc8fe)
![image](https://github.com/thirdweb-dev/js/assets/128964/22506ce1-3ed2-4fda-8138-b2681fc7b42a)

It looks like to take a data from thirdweb.com/chainlist
[](https://thirdweb.com/plyr-tau-testnet)

Maybe I misunderstood about defineChain concept. But should it able to override the value?

**Comment by gregfromstl** [comment]
@iamcryptofennec could you try this again on `thirdweb@nightly`? Should be fixed now

**Comment by iamcryptofennec** [comment]
> @iamcryptofennec could you try this again on `thirdweb@nightly`? Should be fixed now

Yes, it works well on 5.20.0
