### ISSUE TITLE
Transaction history doesn't show anything

### ISSUE THREAD

**Issue by iamcryptofennec** [thirdweb-dev/js#3036]
![image](https://github.com/thirdweb-dev/js/assets/128964/801cb5cd-84d8-4b4b-be2b-1721351eceaf)

But on Explorer it shows like

![image](https://github.com/thirdweb-dev/js/assets/128964/89da1572-6095-45d1-bae6-ae527545ff6f)

Or this transaction history count on Pay only? (I guesses it is Abstract account feature?)

**Comment by joaquim-verges** [comment]
Correct at the moment it only shows pay (buying currency) transactions, but soon it will expand to all wallet transactions!

**Comment by iamcryptofennec** [comment]
Ok great! Thanks for your info
