### ISSUE TITLE
 No QueryClient set, use QueryClientProvider to set one

### ISSUE THREAD

**Issue by Eronred** [thirdweb-dev/js#3070]
When using the `ThirdwebProvider` from the `@thirdweb-dev/react` package for my Next.js, App router codebase, I'm encountering an error message that says _"No QueryClient set, use QueryClientProvider to set one"._ This error occurs when I use the `ConnectWallet` component and after I connect the wallet. When I remove the ConnectWallet, the error disappears.

import { ConnectWallet } from "@thirdweb-dev/react";

I tried to wrap the `ThirdwebProvider` with my `TanstackProvider` from `'@tanstack/react-query'` or the opposite but did not work. 

Here are the codes;

```
//ThirdwebProvider

"use client";
import React from 'react';
import { ThirdwebProvider } from "@thirdweb-dev/react";

export function WalletProvider({ children }: { children: React.ReactNode; }) {
    return (
        <ThirdwebProvider
            clientId="..."
        >
            {children}
        </ThirdwebProvider>
    );
}
```

```
"use client";
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import React, { useMemo } from 'react';

const TanstackProvider = ({ children }: { children: React.ReactNode; }) => {
    const queryClient = useMemo(() => new QueryClient(), []);

    return (
        <QueryClientProvider client={queryClient}>
            {children}
        </QueryClientProvider>
    );
};

export default TanstackProvider;
```

Also here is my layout: 

```
import './globals.css';
import React from 'react';
import { Toaster } from "@/components/ui/toaster";
import TanstackProvider from './provider/TanstackProvider';
import { Analytics } from '@vercel/analytics/react';
import { WalletProvider } from './provider/WalletProvider';

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {

    return (
        <html lang="en">
            <body className='bg-white w-full h-full'>
                <TanstackProvider>
                    <WalletProvider>
                        {children}
                    </WalletProvider>
                </TanstackProvider>
                <Analytics />
            </body>
            <Toaster />
        </html>
    );
}

```

**Comment by jnsdls** [comment]
my best guess based on the information provided so far is that you have `@tanstack/react-query@>=5` installed as a dependency. `@thirdweb-dev/react` requires `@tanstack/react-query@4`.

If this is the issue you have 2 options:
1. downgrade react query to a 4.x.x version - easier (if you do not depend on react query elsewhere)
2. migrate from `@thirdweb-dev/react` to `thirdweb` - the way forward (but a bit of migration work) [migration guide](https://portal.thirdweb.com/typescript/v5/migrate)

**Comment by Eronred** [comment]
> my best guess based on the information provided so far is that you have `@tanstack/react-query@>=5` installed as a dependency. `@thirdweb-dev/react` requires `@tanstack/react-query@4`.
> 
> If this is the issue you have 2 options:
> 
> 1. downgrade react query to a 4.x.x version - easier (if you do not depend on react query elsewhere)
> 2. migrate from `@thirdweb-dev/react` to `thirdweb` - the way forward (but a bit of migration work) [migration guide](https://portal.thirdweb.com/typescript/v5/migrate)

None of the solutions worked, as I am still encountering the same error. I am using the `@tanstack/react-query@>=5` dependency, which is essential for my project. I am also planning to integrate the thirdweb SDK into my React Native app, and I'm concerned that I might encounter the same error there. Is there an alternative approach to resolve this issue?

**Comment by jnsdls** [comment]
> > my best guess based on the information provided so far is that you have `@tanstack/react-query@>=5` installed as a dependency. `@thirdweb-dev/react` requires `@tanstack/react-query@4`.
> > If this is the issue you have 2 options:
> > 
> > 1. downgrade react query to a 4.x.x version - easier (if you do not depend on react query elsewhere)
> > 2. migrate from `@thirdweb-dev/react` to `thirdweb` - the way forward (but a bit of migration work) [migration guide](https://portal.thirdweb.com/typescript/v5/migrate)
> 
> Yes, I am using the `@tanstack/react-query@>=5` dependency, which is essential for my project.
> 
> None of the solutions worked. I am also planning to integrate the thirdweb SDK into my React Native app, and I'm concerned that I might encounter the same error because I am using Tanstack dependency for my React Native app, too.
> 
> Is there an alternative approach to resolve this issue without removing my `@tanstack/react-query@>=5` dependency?

Sadly no, the only path here is to upgrade to `thirdweb` from `@thirdweb-dev/react`. However `thirdweb` is about to get (much improved) react-native support shortly, which should make this the correct choice here regardless.

**Comment by jnsdls** [comment]
yes, it should solve the dependency error since `thirdweb` relies react-query v5

if your code is open source or you have a reproduction example I could take a look at I'm happy to see what's not working :)
