### ISSUE TITLE
[React] How to add custom JSX than "string" on connectBtnProp ?

### ISSUE THREAD

**Issue by iamcryptofennec** [thirdweb-dev/js#3077]
https://portal.thirdweb.com/references/typescript/v5/ConnectButton_connectButtonOptions

Now it supports only "label" that is "String" type.

What if I want to add  an Icon?

like this one

![image](https://github.com/thirdweb-dev/js/assets/128964/5fa1a499-db81-4c57-9498-e6ba9a1b98c7)

**Comment by gregfromstl** [comment]
Hey @iamcryptofennec we currently don't support this when using the ConnectButton component. If you want more control over your connect button like this, I'd recommend creating a custom component.
