### ISSUE TITLE
Viem adapter 'signMessage' produces different signature than a TwAccount 'signMessage'

### ISSUE THREAD

**Issue by jaxernst** [thirdweb-dev/js#3113]
Hello, I was trying to implement SIWE in my app which uses a TW embedded wallet with the Viem adapter, and I was having trouble getting the Viem adapter signed messages to recover to the correct address.

My debugging led me to compare the output from the TwAccount.signMessage function and the signMessage function produced by the Viem adapter, which I would expect to output the same values, but I'm seeing different signatures produced. Here is a quick repro of what I'm trying:

```typescript
const twWallet = createWallet("embedded")

const twWalletAccount = await twWallet.autoConnect({ client: tw })

const walletClient = viemAdapter.walletClient.toViem({
  client: tw,
  account,
  chain: defineChain(chain as any),
}) as Wallet

const message = "Hello"
const twAccountSigned = await twWalletAccount.signMessage({ message })
const twViemClientSigned = await walletClient.signMessage({ message })

console.log("TW wallet account address", twWalletAccount.address)

console.log(
  "TW wallet account signature recovery ",
  await recoverMessageAddress({ message, signature: twAccountSigned }),
)

console.log(
  "TW viem client adapter recovery",
  await recoverMessageAddress({ message, signature: twViemClientSigned }),
)
```

This outputs the following:
```
TW wallet account address 0x0e27Af5cF96515759ecF27FC3247556f450232DB
TW wallet account signature recovery  0x0e27Af5cF96515759ecF27FC3247556f450232DB
TW Viem client adapter recovery 0x51EE343F84802A7178D7248954d4cD77Edd97874
```

I believe these should be returning the same signatures and recovering to the same address, but that is not what I am seeing here. 

Thank you

**Comment by gregfromstl** [comment]
Hey @jaxernst, thanks for opening an issue. We're not able to replicate this on our end, but if you're able to make [this test](https://github.com/thirdweb-dev/js/blob/a76c638dffd91f7e867a455141b3125f51447e53/packages/thirdweb/src/adapters/viem.test.ts#L91) fail we can reopen the issue and look into it further
