### ISSUE TITLE
Fails to compile with next dev --turbo

### ISSUE THREAD

**Issue by iamcryptofennec** [thirdweb-dev/js#3116]
![image](https://github.com/thirdweb-dev/js/assets/128964/141d1c55-0f9e-44b4-91b2-d07e42a2876b)

**Comment by iamcryptofennec** [comment]
I found that when I switched from **turbo (nextjs) to use Webpack**. It was ok.
but when I use **next dev --turbo** again. It has the issues as I showed you above.

**Comment by joaquim-verges** [comment]
thank you for reporting this, investigating

**Comment by jnsdls** [comment]
still looking into this, we have a rough idea of what the problem is but no solution yet

as our own nextjs build times are getting up there (for local dev) we're definitely prioritizing it more :)

**Comment by iamcryptofennec** [comment]
Take your time ;) I can use without --turbo. Hope you gonna find the solution soon. Cheer!

**Comment by jnsdls** [comment]
appreciate the patience!

**Comment by iamcryptofennec** [comment]
Ok I have found that you guys already fixed it on 5.29.6
