### ISSUE TITLE
Accidently react v18 required?

### ISSUE THREAD

**Issue by vanya2h** [thirdweb-dev/js#3146]
After installation of `thirdweb@5.24.0` I noticed new warning in dependency resolution.

```
warning "workspace-aggregator-xxx > my-package > thirdweb > @tanstack/react-query@5.29.2" has incorrect peer dependency "react@^18.0.0".
```

This `@tanstack/react-query` dependency accidently brings react v18 as a minimal supported version.

**Comment by joaquim-verges** [comment]
hmmm we've always had `"react": >= 18` in our peer dependencies, don't think this is a new requirement. https://github.com/thirdweb-dev/js/blob/c1d3a5a259341e6fdda62e3dcaf0c4dae3bd60ff/packages/thirdweb/package.json#L209

Is that an issue for you?

**Comment by ShotsxxxFired** [comment]
I'm also getting dependency errors when moving to 3.24, downgraded back to 3.23 and issues went away. Included the error message below. 

`npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: react-native@0.74.1
npm ERR! Found: react@18.3.1
npm ERR! node_modules/react
npm ERR!   peer react@">=16.8.0" from @floating-ui/react-dom@2.1.0
npm ERR!   node_modules/@floating-ui/react-dom
npm ERR!     @floating-ui/react-dom@"^2.0.8" from @mui/base@5.0.0-beta.40
npm ERR!     node_modules/@mui/base
npm ERR!       @mui/base@"5.0.0-beta.40" from @mui/material@5.15.18
npm ERR!       node_modules/@mui/material
npm ERR!         peer @mui/material@"^5.4.1" from @mui/x-data-grid@6.20.0
npm ERR!         node_modules/@mui/x-data-grid
npm ERR!         3 more (@mui/x-data-grid-pro, @mui/x-date-pickers, the root project)
npm ERR!       1 more (@mui/x-date-pickers)
npm ERR!   peer react@"^17.0.0 || ^18.0.0" from @mui/base@5.0.0-beta.40
npm ERR!   node_modules/@mui/base
npm ERR!     @mui/base@"5.0.0-beta.40" from @mui/material@5.15.18
npm ERR!     node_modules/@mui/material
npm ERR!       peer @mui/material@"^5.4.1" from @mui/x-data-grid@6.20.0
npm ERR!       node_modules/@mui/x-data-grid
npm ERR!         @mui/x-data-grid@"6.20.0" from @mui/x-data-grid-pro@6.20.0
npm ERR!         node_modules/@mui/x-data-grid-pro
npm ERR!         1 more (the root project)
npm ERR!       3 more (@mui/x-data-grid-pro, @mui/x-date-pickers, the root project)
npm ERR!     @mui/base@"^5.0.0-beta.22" from @mui/x-date-pickers@6.20.0
npm ERR!     node_modules/@mui/x-date-pickers
npm ERR!       @mui/x-date-pickers@"^6.20.0" from the root project
npm ERR!   24 more (@mui/material, @mui/private-theming, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"18.2.0" from react-native@0.74.1
npm ERR! node_modules/react-native
npm ERR!   peer react-native@">=0.70" from thirdweb@5.24.0
npm ERR!   node_modules/thirdweb
npm ERR!     thirdweb@"*" from the root project
npm ERR!   peer react-native@"*" from @react-native/virtualized-lists@0.74.83
npm ERR!   node_modules/react-native/node_modules/@react-native/virtualized-lists
npm ERR!     @react-native/virtualized-lists@"0.74.83" from react-native@0.74.1
npm ERR!
npm ERR! Conflicting peer dependency: react@18.2.0
npm ERR! node_modules/react
npm ERR!   peer react@"18.2.0" from react-native@0.74.1
npm ERR!   node_modules/react-native
npm ERR!     peer react-native@">=0.70" from thirdweb@5.24.0
npm ERR!     node_modules/thirdweb
npm ERR!       thirdweb@"*" from the root project
npm ERR!     peer react-native@"*" from @react-native/virtualized-lists@0.74.83
npm ERR!     node_modules/react-native/node_modules/@react-native/virtualized-lists
npm ERR!       @react-native/virtualized-lists@"0.74.83" from react-native@0.74.1
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.`

**Comment by jnsdls** [comment]
hy @vanya2h can you check if the latest version still has the problem? I have a suspicion that https://github.com/thirdweb-dev/js/pull/3169 also likely fixed this issue...

release to check is [thirdweb@5.25.1](https://github.com/thirdweb-dev/js/releases/tag/thirdweb%405.25.1)

**Comment by joaquim-verges** [comment]
We do use a bunch of react 18 features in the react components, so unfortunately we'll need that min requirement. 

One thing that might help I'm the near future is once we break down the package into sub packages, that will let you use the core independently from react.

going to close this issue for now.
