### ISSUE TITLE
[BUG] Default Typescript SDK is now requiring React Native

### ISSUE THREAD

**Issue by ZachHandley** [thirdweb-dev/js#3167]
Title. I posted in Discord, but I figured I might as well have it here.

```
"react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-dropzone": "^14.2.3",
    "sonner": "^1.4.41",
    "tailwindcss": "^3.4.3",
    "thirdweb": "^5.25.0",
 ```

gives me errors on running of

```
13:38:58 watching for file changes...
✘ [ERROR] Could not resolve "@coinbase/wallet-mobile-sdk"

    node_modules/thirdweb/dist/esm/wallets/coinbase/coinbaseMobileSDK.js:1:26:
      1 │ import { configure } from "@coinbase/wallet-mobile-sdk";
        ╵                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@coinbase/wallet-mobile-sdk" as external to exclude it from the bundle,
  which will remove this error and leave the unresolved path in the bundle.

✘ [ERROR] Could not resolve "react-native"

    node_modules/thirdweb/dist/esm/wallets/wallet-connect/index.js:45:40:
      45 │             const { Linking } = require("react-native");
         ╵                                         ~~~~~~~~~~~~~~

  You can mark the path "react-native" as external to exclude it from the bundle, which will remove
  this error and leave the unresolved path in the bundle. You can also surround this "require" call
  with a try/catch block to handle this failure at run-time instead of bundle-time.

✘ [ERROR] Could not resolve "@coinbase/wallet-mobile-sdk/build/WalletMobileSDKEVMProvider"

    node_modules/thirdweb/dist/esm/wallets/coinbase/coinbaseMobileSDK.js:10:4:
      10 │     "@coinbase/wallet-mobile-sdk/build/WalletMobileSDKEVMProvider")).WalletMobileSDKEVMProvider;
         ╵     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@coinbase/wallet-mobile-sdk/build/WalletMobileSDKEVMProvider" as external
  to exclude it from the bundle, which will remove this error and leave the unresolved path in the
  bundle. You can also add ".catch()" here to handle this failure at run-time instead of
  bundle-time.
  ```
  
 idk what's going on, but I do *not* need react-native, and I didn't need Coinbase's SDK either if it's gonna be bringing in react-native bullcrap.

**Comment by jnsdls** [comment]
hey @ZachHandley which bundler etc are you using here?

> You can mark the path "@coinbase/wallet-mobile-sdk" as external to exclude it from the bundle,
>   which will remove this error and leave the unresolved path in the bundle.

  
this should solve it in the short term, but as you correctly point out this should not be required to run if you are not running inside a react native context.

essentially what's happening here is that whichever bundler you are using is not properly tree-shaking code that should not be hit. The best possible thing would be a minimal reproduction of this error (I cannot reproduce this in nextjs for example) and then we'll be able to fix it from there.

**Comment by ZachHandley** [comment]
@jnsdls the issue is most likely that people are using NextJs. I'm using `vite`, using `Astro`

All this means is that the default TypeScript bundle is wrong, and nobody checked it with Vite or a non-react-native context.

**Comment by ZachHandley** [comment]
@jnsdls more specifically

https://github.com/thirdweb-dev/js/commit/b9b185b665e9cc2085f0cc07e3a3cc06a755b42a

![image](https://github.com/thirdweb-dev/js/assets/16495679/252cc85f-7ecc-4bf0-b2b2-6da658c521f5)

**Comment by jnsdls** [comment]
thanks, we'll dig into it and get a fix out as quickly as possible

**Comment by ZachHandley** [comment]
No worries, if you need a default env just run the following

```bash
npm create astro@latest
npx astro add @astrojs/react
npm install thirdweb
npm run dev
```

that should work

**Comment by joaquim-verges** [comment]
@ZachHandley thank you for reporting this, we're getting the fix out in 5.25.1. Should be out in a few minutes

**Comment by ZachHandley** [comment]
Awesome thank you!!

**Comment by joaquim-verges** [comment]
release is out now https://github.com/thirdweb-dev/js/releases/tag/thirdweb%405.25.1
