### ISSUE TITLE
Error when instaling dependency react-native-quick-crypto

### ISSUE THREAD

**Issue by kacperkurek** [thirdweb-dev/js#3173]
Following docs you pointed to install react-native-quick-crypto@0.7.0-rc.6 but thirdweb app requires  >=0.6.1 

While resolving: thirdweb@5.25.1
Found: react-native-quick-crypto@0.7.0-rc.6
node_modules/react-native-quick-crypto
react-native-quick-crypto@"0.7.0-rc.6" from the root project
Could not resolve dependency:
peerOptional react-native-quick-crypto@">=0.6.1" from thirdweb@5.25.1

version 0.6.1 of react-native-quick-crypto have bug that cannot be builded on iOS

**Comment by joaquim-verges** [comment]
hi @kacperkurek thank you for the report and and PR! just curious, what setup do you have? I haven't ran into an error with this using yarn in this demo repo: https://github.com/thirdweb-example/expo-starter

react-native-quick-crypto should be close to releasing stable 0.7 hopefully, but in the meantime im not sure if it's the right solution to prescribe a specific version in peerDependencies

**Comment by kacperkurek** [comment]
@joaquim-verges changed to >=0.6 so it will include all versions from 0.6

**Comment by joaquim-verges** [comment]
@kacperkurek i pushed a change to your PR which i think should do it, and prepare us for when they release v0.7.0 stable. Will merge and release shortly. Thanks again for the report!
