### ISSUE TITLE
Broken npx thirdweb create app

### ISSUE THREAD

**Issue by warengonzaga** [thirdweb-dev/js#3179]
When you try to create app using CLI it will throw an error.

Command: `npx thirdweb create app`

Error:
![image](https://github.com/thirdweb-dev/js/assets/15052701/13b2b69f-9703-4b2e-99b9-f87ebb2a9b91)

Command: `npx thirdweb create app --node` (when using a template node-starter)

Error:
![image](https://github.com/thirdweb-dev/js/assets/15052701/e42dbc6e-ecb5-42be-ba8f-df8a59dea610)

A community member reported it from the [Discord community](https://discord.com/channels/834227967404146718/834227967404146721/1245559243218878518); I can replicate the issue.

I'm using GitBash from Windows 11.

**Comment by warengonzaga** [comment]
Can you review this @jnsdls or @joaquim-verges thanks!

**Comment by warengonzaga** [comment]
For anyone having the issue, alternatively, go to [thirdweb templates](https://github.com/thirdweb-example). See starter templates.

**Comment by gregfromstl** [comment]
@warengonzaga what's your operating system?

**Comment by warengonzaga** [comment]
> @warengonzaga what's your operating system?

Tested on Windows 11 with GitBash.

**Comment by warengonzaga** [comment]
Two reported issues from our Discord community.
