### ISSUE TITLE
detailsButton props doesn't seem display specific token balance properly

### ISSUE THREAD

**Issue by iamcryptofennec** [thirdweb-dev/js#3191]
![image](https://github.com/thirdweb-dev/js/assets/128964/41deeb3d-f5d9-4f61-b7e9-876dd935bc41)

detailsButton={{
            className: "ThirdwebWalletBtn",
            displayBalanceToken: {
                1: "0x5085f96Fab5A4F4cD6AceDf8054b431AaCf298f9",
            }
        }}
        
this token address is ETH on Avax-Fuji. It shows "avax" rather than WETH.

https://testnet.snowtrace.io/token/0x5085f96Fab5A4F4cD6AceDf8054b431AaCf298f9?chainId=43113

But on useWalletBalance hook work correctly.

    const {data: balanceData, isLoading, isError} = useWalletBalance({
        chain: activeChain,
        address: activeAccount?.address,
        client: client,
        tokenAddress: '0x5085f96Fab5A4F4cD6AceDf8054b431AaCf298f9'
    });

result --> 

![image](https://github.com/thirdweb-dev/js/assets/128964/3af65ead-b96a-40a5-a1c0-74b4ecece49d)

**Comment by joaquim-verges** [comment]
thank you for the report! we're looking into this asap

**Comment by gregfromstl** [comment]
Hey @iamcryptofennec, this is actually expected behavior. The `displayBalanceToken` field is chain-specific and takes chain IDs as keys. So to fetch that token on Avalanche-Fuji, you'd want to do:
```ts
detailsButton={{
  className: "ThirdwebWalletBtn",
  displayBalanceToken: {
    43113: "0x5085f96Fab5A4F4cD6AceDf8054b431AaCf298f9",
  }
}}
```

Let me know if this doesn't work for you and I can reopen the issue!

**Comment by iamcryptofennec** [comment]
ahhhhh I see that number is chainId lol. I just thought it is ordering number

I think you should add some text in the doc to say it is a chainId , token address

![Screenshot_2024-06-01-12-06-04-832_com android chrome](https://github.com/thirdweb-dev/js/assets/128964/ca4334d0-bd47-482f-8bc2-81cbd0c05988)
