### ISSUE TITLE
useWalletBalance() hook can't get an ETH on BNB Testnet

### ISSUE THREAD

**Issue by iamcryptofennec** [thirdweb-dev/js#3192]
Token Address: 0xd66c6B4F0be8CE5b39D52E0Fd1344c389929B378

https://testnet.bscscan.com/token/0xd66c6B4F0be8CE5b39D52E0Fd1344c389929B378#balances

I think it's official one because, I took it from BNB faucet

https://www.bnbchain.org/en/testnet-faucet

In Network tab of Chrome dev tools
![image](https://github.com/thirdweb-dev/js/assets/128964/bb1907cf-f4dc-4763-8f83-2d5932c5c3d5)

![image](https://github.com/thirdweb-dev/js/assets/128964/fba6b273-43f2-4399-8ca5-005067f3827b)

I guess because it can't fetch a "name" of this token.

**Comment by joaquim-verges** [comment]
hm yeah we should handle this - what would you expect the name/symbol to be in this case?

**Comment by iamcryptofennec** [comment]
I think if there doesnt have a name. It should be replace d by symbol I guess

**Comment by joaquim-verges** [comment]
fixed here https://github.com/thirdweb-dev/js/pull/3201

**Comment by joaquim-verges** [comment]
will be in next release
