### ISSUE TITLE
When changed address on Wallet manually. Can't signMessage

### ISSUE THREAD

**Issue by iamcryptofennec** [thirdweb-dev/js#3204]
![image](https://github.com/thirdweb-dev/js/assets/128964/6aa60464-86ec-471a-b739-720e59dbb357)

const activeAccount = useActiveAccount();
.....

const signedMessage = await activeAccount.signMessage({
      message: 'Message to be signed',
 });
 
 ps:
 activeAccount.address --> changed after manual switch to another address
 but activeAccount.signMessage() has an error like I describe above. I think it just not change "from" to a current address

**Comment by joaquim-verges** [comment]
thanks for the report @iamcryptofennec - fix is merged in nightly (`npm i thirdweb@nightly`)

will release shortly
