### ISSUE TITLE
how to use wagmi/vue with useSetActiveWallet ? 

### ISSUE THREAD

**Issue by reslear** [thirdweb-dev/js#3205]
we have inly react import `useSetActiveWallet` how to use in `@wagmi/vue` ? 

```ts
  const setActiveWallet = useSetActiveWallet()
```

also `@wagmi/vue` not support `useWalletClient` (https://github.com/wevm/wagmi/discussions/4005)

could you create a working playground/demo for vue ? 
(Otherwise I don't see how we can migrate by the end of June and have to part ways. )

**Comment by MananTank** [comment]
Hi @reslear - Can you give more info on what you are trying to do and what features of thirdweb SDK you want to use?

**Comment by reslear** [comment]
I'm trying to replicate https://github.com/thirdweb-example/wagmi-thirdweb only in vue.

**Comment by joaquim-verges** [comment]
you should be able to just use the viem adapter, like:

```ts
const account = viemAdapter.walletClient.fromViem({ walletClient });
 ```

and keep the `account` around using your state manager of choice. With that account you can use the rest of the SDK to send transactions.
