### ISSUE TITLE
cannot use cloudflare runtime

### ISSUE THREAD

**Issue by jbs-fm** [thirdweb-dev/js#3272]
Hi there,

At the moment you cannot use thirdweb v5 js sdk if you want to build and deploy for cloudflare pages/workers runtime.

There's something weird going on where it's pulling in react-native related dependencies. Also if you try and do nextjs on cloudflare there's going to be a similar problem.

Reproduction with error log in README: https://github.com/jbs-fm/thirdweb-cloudflare-bug

Any help would be much appreciated.

![CleanShot 2024-06-11 at 15 01 42@2x](https://github.com/thirdweb-dev/js/assets/36034436/39bb1a0c-c476-46c9-92c6-9854bfea69bc)

**Comment by nigelmo** [comment]
We are having the same issue with SST as well. Cannot deploy since version 5.23 onwards!

**Comment by gregfromstl** [comment]
Hey @jbs-fm thanks for reporting this. We'll look into it and get back to you ASAP

**Comment by joaquim-verges** [comment]
update - we have a path forward that maintains the react native DX and fixes this issue as well.

working on the refactoring, will post here when its done

**Comment by joaquim-verges** [comment]
@jbs-fm @nigelmo we just merged the fix for this, was able to run the example repo (super helpful for debugging thank you!), connect wallets and transact from it.

You can try it right now by installing the latest nightly: `npm i thirdweb@nightly`

Lmk if it works for you!

We'll get it out in stable early next week.

**Comment by jnsdls** [comment]
assumed to be fixed as part of [5.29.3](https://github.com/thirdweb-dev/js/releases/tag/thirdweb%405.29.3)

please feel free to re-open if the assumption is incorrect
