### ISSUE TITLE
[React Native] [Thirdweb V4] : JSON value '<null>' of type NSNull cannot be converted to NSString warning

### ISSUE THREAD

**Issue by jimit-raval-sf** [thirdweb-dev/js#3283]
I am getting this warning while connecting my wallet in React Native,
Basically What I am doing is...

I am using the ConnectWallet component in the React native project.
whenever I try to connect the wallet using the ConnectWallet component I get "JSON value '<null>' of type NSNull cannot be converted to NSString" this warning.
it doesn't affect the app in development mode but in release mode the app crashes.
I tried using custom UI to connect wallet but it throws the same warning.

Here is the picture of the warning that I got in Xcode:
![unnamed (3)](https://github.com/thirdweb-dev/js/assets/135334627/d954ea91-839a-4f4b-9490-6e9471836a05)

Here is the dependency version:

    "@thirdweb-dev/chains": "^0.1.116",
    "@thirdweb-dev/react-native": "0.7.3",
    "@thirdweb-dev/react-native-compat": "0.7.3",
    "@thirdweb-dev/sdk": "4.0.6",

Thank you

**Comment by joaquim-verges** [comment]
have you tried upgrading to the new `thirdweb@^5` package? we recently added support for react native and is going to be the only supported version moving forward.

It has everything to build custom connection UI already, and prebuilt connect UI components are in the works (you can follow along in this PR #3246

**Comment by jimit-raval-sf** [comment]
Hi @joaquim-verges Thanks for the reply

No, I've not tried upgrading to V5 yet.

In v4, it was working perfectly fine but somehow it suddenly started crashing on iOS only, in the release build.

Here I'm attaching the screenshot of crashlytics, please have a look:
 
<img width="1093" alt="Screenshot 2024-06-17 at 12 07 01 PM" src="https://github.com/thirdweb-dev/js/assets/135334627/293524c9-bbb3-4e15-a3e3-9ad36a8c5128">

**Comment by joaquim-verges** [comment]
which wallet are you connecting in this case? looks lit might be sending a null value via WalletConnect websocket

**Comment by jimit-raval-sf** [comment]
@joaquim-verges 
I'm trying to connect the "Meta Mask" mobile wallet, through the ConnectWallet component.

Here is the code snippet:

![Screenshot 2024-06-18 at 10 36 17 AM](https://github.com/thirdweb-dev/js/assets/135334627/749e7f71-7ef3-4601-8c31-86e153c79eb0)

**Comment by jimit-raval-sf** [comment]
Hi @joaquim-verges 
Is there any progress on this issue?
Thanks!

**Comment by joaquim-verges** [comment]
does it happen with other wallets? one thing i would check is making sure the metamask app is updated to the latest version

**Comment by jimit-raval-sf** [comment]
Hey @joaquim-verges I've the latest meta mask app installed but it is not working and the same issue.

PS: this issue is on iOS only, it is working fine in android

**Comment by jimit-raval-sf** [comment]
Hi @gregfromstl & @joaquim-verges 

is there any progress / update on this issue?

Thanks!

**Comment by gregfromstl** [comment]
Hey @jimit-raval-sf, the v4 SDK is deprecated and we'd recommend upgrading to v5. Please let me know if you have any questions regarding the migration
