### ISSUE TITLE
[React Native] [Thirdweb v5] Thirdweb v5 + Nativewind v4 metro config does not work together

### ISSUE THREAD

**Issue by ludwig-g-w** [thirdweb-dev/js#3284]
When setting up [Nativewind v4](https://www.nativewind.dev/v4/getting-started/expo-router) on the [Thirdweb v5 example React Native app](https://github.com/thirdweb-example/expo-starter), I get errors when trying to connect with `inAppWallet` same result for strategy `phone` and `apple`, the errors I get are:

 Error setting up wallet on device [Error: Invalid share : Share id must be an integer between 1 and 255, inclusive.]
 ERROR  Error while signing in with: Apple. Error: Malformed response from post authentication: Invalid share : Share id must be an integer between 1 and 255, inclusive.
 ERROR  [Error: Error signing in with Apple: Malformed response from post authentication: Invalid share : Share id must be an integer between 1 and 255, inclusive.]

**Comment by joaquim-verges** [comment]
Thanks for the report @ludwig-g-w !

We just shipped a change in the way we do encryption for react native to make sure that it's inline with web and game platforms.

This means that existing accounts you might have done before this change are no longer valid. I believe that's the issue you're seeing.

You might have to create a new account (you can use the + trick to get a different email, like foo+1@bar.com).

Or even easier, create a new client id and use that moving forward so you start with a fresh set of wallets.

Apologies for the inconvenience.

**Comment by ludwig-g-w** [comment]
Super thanks for the quick answer, I can confirm it works fine now 🥳
