### ISSUE TITLE
[React Native] Add support for cli based projects

### ISSUE THREAD

**Issue by mbalazy** [thirdweb-dev/js#3285]
Currently, the documentation describes support for projects using expo: 
https://portal.thirdweb.com/typescript/v5/react-native/installation

My application uses bare RN cli. I tried with mentioned steps with error:

<img width="452" alt="image" src="https://github.com/thirdweb-dev/js/assets/49127168/8ddb0e43-ce88-49ad-9279-59ecaa8b5241">

`TypeError: Cannot read property 'NativeModule' of undefined, js engine: hermes`

```tsx
  useAsync(async () => {
    const wallet = createWallet('embedded')
    const account = await wallet
      .connect({
        strategy: 'apple',
        redirectUrl: 'myApp://',
        client,
      })
      .catch((e) => {
        console.log(e)
      })
    console.log('account -> ', account)
  }, [])
```

Any plans for support non-expo projects or I'm missing something?
My end goal is implement email + apple/google auth.

**Comment by criadoperez** [comment]
similar issue here. Thanks for reporting this @mbalazy.

**Comment by gregfromstl** [comment]
Hey @mbalazy @criadoperez, you'll just need to do the expo module installation first, then you should be able to use the RN CLI normally: https://docs.expo.dev/bare/installing-expo-modules/

Let me know if you run into any issues with it

**Comment by mbalazy** [comment]
> Hey @mbalazy @criadoperez, you'll just need to do the expo module installation first, then you should be able to use the RN CLI normally: https://docs.expo.dev/bare/installing-expo-modules/
> 
> Let me know if you run into any issues with it

adding an expo to the app is the only solution? it's not `just` imo 😏
