### ISSUE TITLE
How to show disconnect button and send transaction button

### ISSUE THREAD

**Issue by abaymhjn** [thirdweb-dev/js#3302]
Hi Guys,
I am trying to use 
<ThirdwebProvider>
        <ConnectButton
            client={client}
            wallets={wallets}
            theme={"light"}
            connectModal={{ size: "wide" }}
            onConnect={(wallet) => {
              handleConnect(wallet);
            }}
        />
        <div>
          {connecting && <p>Connecting...</p>}
          {connected && <p>Connected with accounts: {accounts.join(', ')}</p>}
          {error && <p>Error: {error.message}</p>}
        </div>
        </ThirdwebProvider>
        
       I did not able to find in documentation.

**Comment by MananTank** [comment]
Hey @abaymhjn, Can you elaborate on what exactly you are trying to do?
