### ISSUE TITLE
"Switch Account" button does not have any events and no event fires to `onConnect` either

### ISSUE THREAD

**Issue by ZachHandley** [thirdweb-dev/js#3322]
So basically, when a user connects their wallet, I have an onConnect event that fires and creates them an account and I manage their auth myself. Now the issue is there's a `Switch Account` button, but no way to listen to or know that event has fired (maybe I could check the current account vs the stored address but like, cmon), can we get this added to the connect button props?

**Comment by joaquim-verges** [comment]
@ZachHandley good feedback. 

You should be able to subscribe to these account changed events using `activeWallet.subscribe(...)`

This fires a bunch of interesting events l, including `accountChanged` which gives you the new account.

https://portal.thirdweb.com/references/typescript/v5/WalletEmitterEvents

Lmk if that helps

**Comment by ZachHandley** [comment]
Interesting, okay, I'll look into that, thank you!
