### ISSUE TITLE
ConnectButton component not showing balance

### ISSUE THREAD

**Issue by Anonymous961** [thirdweb-dev/js#3332]
While connecting to the wallet, the `ConnectButton` component is unable to show the balance on any chain.

![image](https://github.com/thirdweb-dev/js/assets/96728156/dfefab86-bbfb-46da-9009-6d75305da0af)

I've tried specifying the Sepolia chain as a prop in the `ConnectButton` component, but the result remains the same.

```
import { client } from "./client";
import { defineChain, sepolia } from "thirdweb/chains";

export default function Home() {
  const chain = defineChain(sepolia);
  return (
    <main className="p-4 pb-10 min-h-[100vh] flex items-center justify-center container max-w-screen-lg mx-auto">
      <div className="py-20">
        <Header />

        <div className="flex justify-center mb-20">
          <ConnectButton client={client} chain={chain} />
        </div>
      </div>
    </main>
  );
}
```

Framework: Next.js

**Comment by jnsdls** [comment]
most likely this is a problem with the way your `client` is set up - make sure you have a clientId set up and that the api key it is using is allowed on the domain(s) (including localhost if running locally) that this is hosted on.

also as a note (but this won't be causing it) the `defineChain(sepolia)` is redundant, `sepolia` is already a "defined" chain

**Comment by Anonymous961** [comment]
@jnsdls Next.js server is throwing an error if the `clientId` is not set up properly. So, I think `clientId` is working properly but how do I allow it in domain(s) ? I also thought that sepolia is a defined chain. So, initialy I used `sepolia` directly without `defineChain`. However it was not working for me. Then I saw this video by thirdweb's official YT [video](https://youtu.be/EI-nm1sLe3U?si=voMZlAsUjAxk5ZAl) `21:39` and I got confused because I was unable to find it in the docs.

**Comment by gregfromstl** [comment]
Hey @Anonymous961, a few other things you could try:
1. Make sure you've wrapped your app in a `ThirdwebProvider` https://portal.thirdweb.com/typescript/v5/react/ThirdwebProvider
2. Make sure your client ID is correct (Next.js won't complain as long as it's **set**, but it could still be the wrong client ID. Get you client ID from the thirdweb dashboard
3. Make sure you allow all domains or the specific domains you'll be using (including localhost) on your client id, you can configure this in the dashboard when creating your client id

**Comment by jnsdls** [comment]
also if you're server rendering you may *also* have to set a secretKey in `createThirdwebClient()` (if you do not set allowed domains to `*`) so that on the server the RPC requests to fetch the balance are authenticated
