### ISSUE TITLE
[React Native][Thirdweb v5] Expo web support?

### ISSUE THREAD

**Issue by ludwig-g-w** [thirdweb-dev/js#3342]
Running Thirdweb with Expo on web doesn't seem to work, I've been trying with the Expo Starter project, will it be supported in the future?

**Comment by joaquim-verges** [comment]
@ludwig-g-w currently the crypto/wallet libs required a not compatible with Expo web - that said i'd really like to make it work so we'll get to it at some point. Would love some contributions if you're interested!

**Comment by ludwig-g-w** [comment]
> @ludwig-g-w currently the crypto/wallet libs required a not compatible with Expo web - that said i'd really like to make it work so we'll get to it at some point. Would love some contributions if you're interested!

Ok thank you for your response. For sure, I'm willing to help out if I can :)
