### ISSUE TITLE
walletConfig "smartWalletOnly" is not working for coinbase wallet

### ISSUE THREAD

**Issue by jnsdls** [thirdweb-dev/js#3350]
Hey @joaquim-verges  didn't want to spam with new issue
```
 createWallet("com.coinbase.wallet",{
    walletConfig:{
      options: "smartWalletOnly"
    }
  }),
```

is not working i.e dapp is picking coinbase wallet extension over coinbase smart wallet

_Originally posted by @bablu573 in https://github.com/thirdweb-dev/js/issues/3320#issuecomment-2173772507_

**Comment by joaquim-verges** [comment]
@bablu573 fixed in #3364 releasing a patch shortly

thanks for reporting
