### ISSUE TITLE
[React] custom themes no longer work as described in the docs

### ISSUE THREAD

**Issue by alecananian** [thirdweb-dev/js#3351]
A [recent change to validate custom theme props](https://github.com/thirdweb-dev/js/pull/3341/files#diff-a81c8ea1693a9adf47a4068b0579e77d67eb6b5eeafd53f30118029d3f5cfe11R25) has broken existing functionality for providing custom themes [as described in the docs](https://portal.thirdweb.com/references/typescript/v5/ConnectButtonProps#example-7), for example:

```
import { ConnectButton, darkTheme } from "thirdweb/react";

<ConnectButton
  ...
  theme={darkTheme({
    colors: {
      primaryButtonBg: "#DC2626",
      primaryButtonText: "#E7E8E9",
    },
  })}
/>
```

This code now fails the `isValidTheme` check because `darkTheme` doesn't provide the `fontSizes`, `radii` and `space` fields.

**Comment by joaquim-verges** [comment]
fixed in #3356 getting out in a patch release shortly
