### ISSUE TITLE
Coinbase smart wallet taking more time to load than expected

### ISSUE THREAD

**Issue by bablu573** [thirdweb-dev/js#3418]
With thirdweb when coinbase smart wallet is configured it's taking more time to load the tx and this load time increasing linearly w.r.t to gas estimite unlike other providers like rainbow kit demo video attached with same function called in both

https://github.com/thirdweb-dev/js/assets/100342157/5d3c928f-4ca3-485a-8689-f6459d0851a5

**Comment by joaquim-verges** [comment]
hmmm this is consistent for you? exact same transaction on both sides? once you're in the cb smart wallet screen it should be out of our control, we don't dictate how it should estimate/simulate the transaction

**Comment by bablu573** [comment]
Yes its same tx on both sides and its consistent
