### ISSUE TITLE
Switch wallet not working metamask mobile

### ISSUE THREAD

**Issue by bablu573** [thirdweb-dev/js#3419]
When metamask on different chain than active chain,it should make user to allow adding chain and switching chain but its directly returning attaching video for refernce

https://github.com/thirdweb-dev/js/assets/100342157/49d57157-1edb-4a14-bfb0-ac7547386c3d

**Comment by joaquim-verges** [comment]
are you passing the desired chain in the ConnectButton ?

**Comment by bablu573** [comment]
yes

**Comment by bablu573** [comment]
Hey any update on this

**Comment by jnsdls** [comment]
we'll dig in! we'd also be very happy to take any PRs to fix this if you already know how to reproduce it

**Comment by MananTank** [comment]
This should be fixed in https://github.com/thirdweb-dev/js/pull/3465

**Comment by jnsdls** [comment]
stable release coming early this week
