### ISSUE TITLE
Can't switch chain on WalletConnect

### ISSUE THREAD

**Issue by iamcryptofennec** [thirdweb-dev/js#3437]
![image](https://github.com/thirdweb-dev/js/assets/128964/1b060759-a0aa-408d-b569-f791601ac311)

I use the preset of AvalancheFuji

![image](https://github.com/thirdweb-dev/js/assets/128964/7309c27f-8822-4518-ac25-2d81bb404352)

![image](https://github.com/thirdweb-dev/js/assets/128964/cb0b8c55-6009-4c37-a036-e6e61aa37cb2)

it works on Rabby, Metamask. But on WalletConnect nope :(

thirdweb sdk : 5.29.6

**Comment by iamcryptofennec** [comment]
![image](https://github.com/thirdweb-dev/js/assets/128964/0f31307c-77d6-4e8a-9054-b5bcb6f0fe8d)
![image](https://github.com/thirdweb-dev/js/assets/128964/f39acded-f075-4fd4-b926-6ab1f5d5707a)


On <ConnectButton> has the same problem too

http://localhost:3000/turbopack/[project]/node_modules/thirdweb/src/wallets/wallet-connect/controller.ts

it said the problem came from here, SwtichChainError

**Comment by iamcryptofennec** [comment]
in switchChainWC
![image](https://github.com/thirdweb-dev/js/assets/128964/21fbf46e-c2c2-4cbf-b217-e691443b0085)

why doesn't it use like another wallet type?
![image](https://github.com/thirdweb-dev/js/assets/128964/9963f8d6-30d3-4c0e-b75d-64e6e939fb45)
just  blockExplorerUrls: apiChain.explorers?.map((x) => x.url),

**Comment by jnsdls** [comment]
we'll take a look! thanks for the report

alternatively feel free to send a PR if you have a working solution to the problem!

**Comment by iamcryptofennec** [comment]
https://github.com/thirdweb-dev/js/pull/3465

I have PR a fixed code

**Comment by iamcryptofennec** [comment]
> ![image](https://private-user-images.githubusercontent.com/128964/341788930-0f31307c-77d6-4e8a-9054-b5bcb6f0fe8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMjQ3NTgsIm5iZiI6MTcxOTIyNDQ1OCwicGF0aCI6Ii8xMjg5NjQvMzQxNzg4OTMwLTBmMzEzMDdjLTc3ZDYtNGU4YS05MDU0LWI1YmNiNmYwZmU4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQxMDIwNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMGNjNTVhZDMzZTE1MmQwNmFmZWE3YzM3YmFmZjUwZDhhODJkMTkxNTlhNTgzZmMwYmU1M2FlZWQ3MjdmM2UxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EjLi1qBGdJcqoRssmTX4mmNdxPU-j8yiEK3nK5hMHPo) ![image](https://private-user-images.githubusercontent.com/128964/341789293-f39acded-f075-4fd4-b926-6ab1f5d5707a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMjQ3NTgsIm5iZiI6MTcxOTIyNDQ1OCwicGF0aCI6Ii8xMjg5NjQvMzQxNzg5MjkzLWYzOWFjZGVkLWYwNzUtNGZkNC1iOTI2LTZhYjFmNWQ1NzA3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQxMDIwNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MmJkZWQ3NjViMjRiMzY1NTdjY2VkNTkxN2VkOTFkMmM3MmU1NmYzMDZmY2VjNWM0ZDIxNzQ0NjVmMDFkZTFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1kzolXZ-9xFZ39BeuKCWiq0CotLjkRNeYcxL_9RNCTQ)
> 
> On has the same problem too
> 
> [http://localhost:3000/turbopack/[project]/node_modules/thirdweb/src/wallets/wallet-connect/controller.ts](http://localhost:3000/turbopack/%5Bproject%5D/node_modules/thirdweb/src/wallets/wallet-connect/controller.ts)
> 
> it said the problem came from here, SwtichChainError

But still have a problem when using <ConnectButton>
with a new error: {"code":-32602,"message":"May not specify default MetaMask chain."}

But with my PR. Using hook useSwitchActtiveWalletChain() seem fine.

**Comment by jnsdls** [comment]
closing, we'll release a stable version with these updates early this week! thanks for the contribution!
