### ISSUE TITLE
Can't programmatically open Details Modal

### ISSUE THREAD

**Issue by levitatejay** [thirdweb-dev/js#3450]
A way to programmatically open the Connect Modal was recently added, but I don't think there is a way to open the Details Modal

Reference:

> @MananTank Thanks that's worked great for sign in. I haven't been able to find a way to programatically open the Detail Modal (with the Send/Receive/Buy). Do you know if there's a way?

_Originally posted by @levitatejay in https://github.com/thirdweb-dev/js/issues/2784#issuecomment-2156452273_

**Comment by MananTank** [comment]
Hey @levitatejay - You can use `useWalletDetailsModal` hook - https://portal.thirdweb.com/references/typescript/v5/useWalletDetailsModal
