### ISSUE TITLE
Problem with thirdweb cli 

### ISSUE THREAD

**Issue by thefool76** [thirdweb-dev/js#3520]
# Unable to Create thirdweb Project Due to Invalid Version Error

## Environment
- Operating System: Windows 11
- Node.js version: v20.15.0

## Issue Description

I'm trying to create a new project using thirdweb, but I'm encountering an "Invalid Version" error. Here's what I've experienced and attempted:

1. Initially, I tried to create a project using:
   ```
   npx thirdweb create app
   ```
   This resulted in an "Invalid Version" error.

2. After researching online, I've tried several methods to resolve the issue:
   - Updated Node.js to the latest version
   - Attempted to install the thirdweb CLI globally

3. Despite these efforts, I'm still unable to run:
   ```
   thirdweb create app
   ```

4. I sought help on the Discord channel but didn't receive any response.

## Steps Taken
1. Updated Node.js to the latest version
2. Installed thirdweb CLI globally
3. Attempted to create a project using both `npx thirdweb create app` and `thirdweb create app`
4. Sought assistance on the Discord channel

## Expected Behavior
The command should successfully initiate the creation of a new thirdweb project.

## Actual Behavior
The command fails with an "Invalid Version" error.

## Additional Information
Any error messages, logs, or additional context that might help in diagnosing the issue would be appreciated.
![1](https://github.com/thirdweb-dev/js/assets/69065938/73fd33a8-b59c-4796-b48c-8581d6703b8c)

## Question
Has anyone else encountered this issue or knows of a solution? Any assistance would be greatly appreciated.

**Comment by gregfromstl** [comment]
Hey @thefool76, I'm not able to reproduce this and its likely an issue with your node setup. However, if you could share the project you're trying to create, I can point you to a github repo to clone that will give you the same effect as the create command
