### ISSUE TITLE
The Info of PLYR PHI mainnet on thirdweb chain list not correct

### ISSUE THREAD

**Issue by iamcryptofennec** [thirdweb-dev/js#3544]
Ref to the testnet: https://github.com/thirdweb-dev/js/issues/3047
We have a problem like this before. and you guys solved this problem.

Now, we already released a mainnet and the problem occured again. Please fix this problem
https://thirdweb.com/plyr-phi

![image](https://github.com/thirdweb-dev/js/assets/128964/386079f9-2093-4927-bc00-e85b614f92c1)

icon : ipfs://QmVhG7xeTc78ibQunQ5sBJ4533r9FDM2xUCQKV72DPd1ux
from ethereum-list -> https://github.com/ethereum-lists/chains/blob/master/_data/icons/plyr.json

and info is : https://plyr.network/ not avacloud.io

**Comment by jnsdls** [comment]
updated, caches will clear over the next couple of minutes to an hour and it should be fixed
