### ISSUE TITLE
Suggest to have manual update for useWalletBalance()

### ISSUE THREAD

**Issue by iamcryptofennec** [thirdweb-dev/js#3618]
Just an idea. Because, right now after transferred fund. Need to wait such a long time to update balance data.

Or is it possible to have
- Trigger function to update
- can set Interval to update ;)

Thanks...

**Comment by jnsdls** [comment]
@gregfromstl @MananTank it probably makes sense to expose these RQ options and also the refresh option.

**Comment by jnsdls** [comment]
@iamcryptofennec If you wanna give it a shot yourself feel free to send a PR. Otherwise we'll get it added soon.
