### ISSUE TITLE
Error when offering to a Direct Listing

### ISSUE THREAD

**Issue by guliing** [thirdweb-dev/js#363]
Getting an error on makeOffer in useMakeOffer

| Raw error |

cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted: !BAL20", method="estimateGas",...

**Comment by joaquim-verges** [comment]
you're getting the error `execution reverted: !BAL20` from the contract, this means that you don't have enough of the currency to make the offer.
