### ISSUE TITLE
[React Native] [Thirdweb v5] ERROR  TypeError: Cannot read property 'readFile' of undefined, js engine: hermes

### ISSUE THREAD

**Issue by ludwig-g-w** [thirdweb-dev/js#3645]
It seems like this error has reappeared for me without any relevant changes to my dependencies. I've tried to create a new Thirdweb client Id which hasn't solved the issue. Here's the error:

 ERROR  TypeError: Cannot read property 'readFile' of undefined, js engine: hermes
 Error: Malformed response from post authentication: Something went wrong getting cognito recovery code

**Comment by joaquim-verges** [comment]
@ludwig-g-w what are the steps you're doing to reproduce this? some code would be helpful too. And is it consistently failing with that error?

**Comment by ludwig-g-w** [comment]
I encounter this error consistently whenever I try to login using whatever method otp, Apple(I think same result when using wallets as well). The strange thing is that two weeks ago these same methods were working, no changes in the code since then. The only change I have done now is to update my API key.

**Comment by ludwig-g-w** [comment]
The error is pointing to this file: **getSSOTokenFromFile.js**

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getSSOTokenFromFile = void 0;
const fs_1 = require("fs");
const getSSOTokenFilepath_1 = require("./getSSOTokenFilepath");
const { readFile } = fs_1.promises;
const getSSOTokenFromFile = async (id) => {
    const ssoTokenFilepath = (0, getSSOTokenFilepath_1.getSSOTokenFilepath)(id);
    const ssoTokenText = await readFile(ssoTokenFilepath, "utf8");
    return JSON.parse(ssoTokenText);
};
exports.getSSOTokenFromFile = getSSOTokenFromFile;

**Comment by joaquim-verges** [comment]
hmmm that code doesnt look familiar, its not from our library - is it from another library maybe?

**Comment by ludwig-g-w** [comment]
After looking a bit further it seems to be this function that is throwing the error: **Something went wrong getting cognito recovery code**

```
private async validateEmailOTP(options: {
    email: string;
    otp: string;
    recoveryCode?: string;
  }): Promise<AuthLoginReturnType> {
    try {
      const { storedToken } = await validateEmailOTP({
        email: options.email,
        client: this.options.client,
        otp: options.otp,
        recoveryCode: options.recoveryCode,
      });
      const account = await this.getAccount();
      return {
        user: {
          status: UserWalletStatus.LOGGED_IN_WALLET_INITIALIZED,
          account,
          authDetails: storedToken.authDetails,
          walletAddress: account.address,
        },
      };
    } catch (error) {
      console.error(`Error while validating otp: ${error}`);
      if (error instanceof Error) {
        throw new Error(`Error while validating otp: ${error.message}`);
      }
      throw new Error("An unknown error occurred while validating otp");
    }
  }
```

**Comment by joaquim-verges** [comment]
how consistent is this? you can reproduce everytime?

**Comment by ludwig-g-w** [comment]
It always happens for me in two different apps as well.

**Comment by joaquim-verges** [comment]
very weird im not able to reproduce. Does it happen with every email for you or only certain ones? the error seems to indicate that either the account or client id was used in a different way before...

**Comment by joaquim-verges** [comment]
@ludwig-g-w can you try updating to latest (5.43+) we shipped a fix related to this issue
