### ISSUE TITLE
[React Native] [Thirdweb v5] Not working with new architecture

### ISSUE THREAD

**Issue by ludwig-g-w** [thirdweb-dev/js#3723]
Turning on `newArchitecture: true` in `app.json` with Thirdweb installed and configured makes my app show a white screen and nothing more.

**Comment by gregfromstl** [comment]
Thanks for reporting this @ludwig-g-w, I'll look into it and follow up here

**Comment by gregfromstl** [comment]
Hey @ludwig-g-w, sorry about the delay here. I'm able to enable new architecture on our example repo using the steps here: https://docs.expo.dev/guides/new-architecture/

If you can provide more info about your setup we might be able to debug further.

**Comment by ludwig-g-w** [comment]
Sorry for coming back very late to this topic once again. 

I've tried on several projects(including the starter thirdweb template) trying to enable the new architecture without success and it seems to fail on @thirdweb-dev/react-native-adapter.

**Comment by ShehrozAttique** [comment]
> Sorry for coming back very late to this topic once again.
> 
> I've tried on several projects(including the starter thirdweb template) trying to enable the new architecture without success and it seems to fail on @thirdweb-dev/react-native-adapter.

Hey, i am having same issue but not only on new architecture also on expo sdk 52

On web it is working fine but on Android and getting this error
ERROR  TypeError: Cannot read property 'includes' of undefined
