### ISSUE TITLE
Smart wallet is not working?

### ISSUE THREAD

**Issue by 0xrpj** [thirdweb-dev/js#3727]
This is what I was using:

```
    connectWithCB = async (): Promise<CoinbaseWallet> => {
        const instance = new CoinbaseWallet({
            chains: [Base, BaseSepoliaTestnet],
        });
        return instance;
    };
```

If the wallet was not installed, it would give the smart wallet popup. But now it just gives the normal "Install Coinbase" popup. I have not changed/updated the package version.

```
        "@thirdweb-dev/sdk": "^4.0.99",
        "@thirdweb-dev/wallets": "^2.5.39",
```

**Comment by gregfromstl** [comment]
Hey @0xrpj, Coinbase Smart Wallet is only supported in V5 of the SDK. V4 will be deprecated soon, so we highly recommend [migrating](https://portal.thirdweb.com/typescript/v5/migrate). If you need any help with it, please let us know.
