### ISSUE TITLE
[React Native][v5] ethers6 adapter throws error

### ISSUE THREAD

**Issue by ludwig-g-w** [thirdweb-dev/js#3788]
```
const signer = await ethers6Adapter.signer.toEthers({
            chain,
            client: thirdwebClient,
            account: account,
          });
```
this fails with: `TypeError: property is not configurable` and `TypeError: Cannot read property 'getAddress' of undefined`

Same call works with ethers5Adapter

**Comment by joaquim-verges** [comment]
can you show what `account` is in your case? 

a minimal reproducible code snippet would help a lot

**Comment by kien-ngo** [comment]
Hi @ludwig-g-w would love to get this issue resolved for you if you can provide more context (your package.json, how you get the `account` as Joaquim previously mentioned, etc.)

For example, the following code works fine for me:

```ts
const account = await generateAccount({ client });
const signer = await ethers6Adapter.signer.toEthers({
	chain: ethereum,
	client,
	account,
});
console.log({ signer, account });
```

**Comment by gregfromstl** [comment]
Closing this issue since it appears to be stale. Feel free to reopen if it's still a problem!
