### ISSUE TITLE
Marketplace: Active listings query filtering works incorrect

### ISSUE THREAD

**Issue by UladzislauVintsarevich** [thirdweb-dev/js#389]
Hi! I'm using ThirdWeb React SDK to communicate with marketplace contracts.

Active Listings pagination seems to work based on All Listing pagination and just filter data when it's fetched.

Let me show you

I have a ThirdWeb Marketplace Contract with 17 active listings. You can check it by link https://thirdweb.com/mumbai/0xe844E4183DB6F6F026d44a7Cb3AD0C485d18748a/listings

I wrote such code:
```
const activeListings = await contract.getActiveListings({
    start: 0,
    count: 24,
  });

  const activeListingsSecond = await contract.getActiveListings({
    start: 23,
    count: 24,
  });

  const allListings = await contract.getAllListings({
    start: 0,
    count: 24,
  });
  const allListingsSecond = await contract.getAllListings({
    start: 23,
    count: 24,
  });

  console.log('activeListings', activeListings);
  console.log('activeListingsSecond', activeListingsSecond);
  console.log('allListings', allListings);
  console.log('allListingsSecond', allListingsSecond);
```

And I have such output:
<img width="1486" alt="image" src="https://user-images.githubusercontent.com/64966002/202363960-c64e9307-3e8f-4c9b-9bbd-8073c8c2bbe3.png">
<img width="1501" alt="image" src="https://user-images.githubusercontent.com/64966002/202363841-e2463510-77b4-45e5-859f-e06420f9279d.png">

As you can see, I have 17 Active Listings in total. But these listings are placed on different pages, event size of page 24.

I think the issue is that your pagination works based on all listings and data is filtered after fetch.

Could you check it? 

Thanks! Have a nice day!

**Comment by joaquim-verges** [comment]
@UladzislauVintsarevich thank you for the report and sorry for the late reply.

You're correct that the filtering happens after page size is fetched. I'll look for ways to mitigate that, not a simple problem unfortunately. One way to work around might be is to use `getAll()` instead, and do your own filtering/disabling on the display side.

**Comment by joaquim-verges** [comment]
@UladzislauVintsarevich just FYI, we released a new version of our marketplace contract (v3) which solves the pagination issues and is much much faster to fetch listings 🙂
