### ISSUE TITLE
 process is not defined

### ISSUE THREAD

**Issue by wenjoy** [thirdweb-dev/js#396]
I try to as example describe in READEME.md, but got this error:

  @thirdweb-dev_react.js?v=2f243b4d:19243 Uncaught ReferenceError: process is not defined

My version is:
    "@thirdweb-dev/react": "^3.6.0",
    "@thirdweb-dev/sdk": "^3.6.0",

Cant understand why react lib try to access `process`?

```js
 if (process.env.NODE_DEBUG) {
      debugEnv = process.env.NODE_DEBUG;
      debugEnv = debugEnv.replace(/[|\\{}()[\]^$+?.]/g, "\\$&").replace(/\*/g, ".*").replace(/,/g, "$|^").toUpperCase();
      debugEnvRegex = new RegExp("^" + debugEnv + "$", "i");
    }
```

**Comment by wenjoy** [comment]
It's caused by Vite. So I closed it .

**Comment by kien-ngo** [comment]
@wenjoy Did you solve this issue by putting `define` inside vite.config.js?
