### ISSUE TITLE
[Dashboard] - Duplicate / in Block Explorer URL

### ISSUE THREAD

**Issue by jarrodwatts** [thirdweb-dev/js#3992]
Not sure what is causing this but the "Block explorer" button has an additional forward slash on Abstract testnet

Example: https://thirdweb.com/abstract-testnet/0xC4822AbB9F05646A9Ce44EFa6dDcda0Bf45595AA

If you click the Block Explorer button it takes you to a broken link - `https://explorer.testnet.abs.xyz//address/0xC4822AbB9F05646A9Ce44EFa6dDcda0Bf45595AA`

Note additional forward slash after the .xyz

**Comment by jnsdls** [comment]
good find, will fix (unless you want to send a PR that strips any trailing `/` for those components :) )

**Comment by jnsdls** [comment]
fixed!
