### ISSUE TITLE
Broken link on Thirdweb Portal: /cli/build Page not Accessible

### ISSUE THREAD

**Issue by 0xScratch** [thirdweb-dev/js#4021]
Hey @jnsdls Just got to know that a few users are facing problems in accessing this link -> https://portal.thirdweb.com/cli/build

It says `Page Not Found`, moreover there doesn't exist any file within the [cli](https://github.com/thirdweb-dev/js/tree/main/apps/portal/src/app/cli) folder of this repository.

Thanks!

**Comment by jnsdls** [comment]
fixed, thanks for the report!
