### ISSUE TITLE
[SDK] - Expose convenience function to do `ethers.utils.formatEther` and `ethers.utils.parseEther`

### ISSUE THREAD

**Issue by jarrodwatts** [thirdweb-dev/js#411]
## Background

Working with `BigNumber` variables requires importing `ethers` and using `ethers.utils.formatEther` and `parseEther` functions which is not very discoverable through our SDK unless you are already familiar with the ethers dependency.

It would be great to expose convenience functions that expose these directly from our SDK package rather than ethers.

## Goal

[] Add `toEther` function
  - Users can import toEther from the @thirdweb-dev/sdk package and convert a number from wei to formatted value. Use the ethers.utils.formatEther functionality under the hood.

[] Add `toWei` function
  - Same as above, except use parseEther under the hood.

**Comment by yehia67** [comment]
Hey @jarrodwatts 👋 
I would be happy to help!
But I am not sure where it is better to add them inside `sdk/src/evm/common/utils.ts` to be similar to the `ethers` package. Or should I add them on `sdk/src/evm/common/currency.ts` I see we have similar methods there like `normalizeAmount` and `fetchCurrencyValue`

**Comment by joaquim-verges** [comment]
@yehia67 thanks for helping out! I think it makes sense to put them in `currency.ts` with the other currency helper functions :)

**Comment by jnsdls** [comment]
fixed in #421 by @yehia67 thx!

**Comment by yehia67** [comment]
@jnsdls Much welcome I am looking forward to the new contribution here 🚀
