### ISSUE TITLE
Connect UI doesn't display image passed to the inAppWallet()'s metaData

### ISSUE THREAD

**Issue by codingfarhan** [thirdweb-dev/js#4148]
Code:

`
<ConnectButton
client={client}
wallets={[inAppWallet(
metadata: {
      image: {
        alt: "Alt Text",
        height: 100,
        width: 100,
        src: "https://logowik.com/content/uploads/images/ethereum3649.jpg",
      },
 }),
  createWallet("global.safe"),
  createWallet("com.exodus")
  ]}
`

**Comment by joaquim-verges** [comment]
thank you @codingfarhan - looking into this

**Comment by codingfarhan** [comment]
Thanks! @joaquim-verges as per my investigation, it looks like we need to add the 'metadata' object to the 'useStoreScreen' hook (in packages/thirdweb/src/react/web/ui/ConnectWallet/Modal/ConnectModal.tsx). If you're caught up with some other stuff, I'd be happy to create a PR for this! Will just need to know where exactly we want to place the image passed to inAppWallet() :)

**Comment by joaquim-verges** [comment]
Should be even simpler than that. @gregfromstl was gonna look into it but feel free to open a PR!
