### ISSUE TITLE
Coinbase Wallet Shows Incorrect ERC20 Token Total Supply

### ISSUE THREAD

**Issue by larron** [thirdweb-dev/js#4232]
Hey guys,

I'm not sure if this is a thirdweb or coinbase issue but figure you will be able to make something happen.

Upon creating a token with a 1,000,000 supply and 9 decimals instead of 18, the connect interface is showing the incorrect total supply while the actual underlying contract when deployed is indeed accurate.

Here's an example link:
https://sepolia.basescan.org/tx/0x725f2e49a1aaf700e8f0b4790fb87fd8cdcc283fd457dd29e654119c119f088f

SS:
<img width="468" alt="Screenshot 2024-08-21 at 10 19 46 PM" src="https://github.com/user-attachments/assets/c2835247-605b-4cca-a0c6-1d02f731a8f4">

**Comment by gregfromstl** [comment]
Thanks for the report @larron, I've passed this along to the Coinbase Smart Wallet team and will report back here when there's an update!

**Comment by hieronymus777** [comment]
Hi to help us reproduce, would you please
1. Tap 5 times underneath 'asset changes'. This will copy the raw user op + simulation results from our backend.
2. Send the results async to the Coinbase Smart Wallet team.
