### ISSUE TITLE
 [React] [Thirdweb v5] Feature Request ✨  : Screen options arg in useWalletDetailsModal hook 

### ISSUE THREAD

**Issue by mtrunkbear** [thirdweb-dev/js#4238]
I think it would be very interesting if the useWalletDetailsModal hook allowed you to enter in its props the screen you want to open, for example send or receive

**Comment by gregfromstl** [comment]
Hey @mtrunkbear, thanks for your feature request. We're planning on updating the UI library to be more composable, so you can decide not only which screen appears in the modal, but which elements are on that screen. This will hopefully be available sometime in September.
