### ISSUE TITLE
How to deal with chain switching on Coinbase Smart Wallet?

### ISSUE THREAD

**Issue by iamcryptofennec** [thirdweb-dev/js#4240]
![image](https://github.com/user-attachments/assets/e19b4b47-b365-4c48-b54e-53d87e89eb82)

Now, I can't let coinbase smart wallet to switch to my specific chain id.

**Comment by jnsdls** [comment]
@iamcryptofennec this is a coinbase smart wallet problem, it only works on certain chains: https://help.coinbase.com/en/wallet/getting-started/smart-wallet

<img width="794" alt="image" src="https://github.com/user-attachments/assets/55c35f15-aaca-4a16-9991-439b69326a4c">
