### ISSUE TITLE
ERROR in ./node_modules/thirdweb/node_modules/@walletconnect/utils/dist/index.es.js

### ISSUE THREAD

**Issue by developernajib** [thirdweb-dev/js#4273]
ERROR in ./node_modules/thirdweb/node_modules/@walletconnect/utils/dist/index.es.js 4946:12-14
export 'default' (imported as 'Bo') was not found in '@stablelib/random' (possible exports: __esModule, defaultRandomSource, randomBytes, randomString, randomStringForEntropy, randomUint32)

For this issue, I couldn't even build my react project.

What I am using:
Node version: 20.0.0
Thirdweb version: latest (5.48.1)  -also tried in v5.47.1 not working

**Comment by developernajib** [comment]
![image](https://github.com/user-attachments/assets/4fa2050b-5405-4b8b-9454-684da84d8f44)

**Comment by gregfromstl** [comment]
Hello @developernajib, could you please provide a minimal reproduction of the issue? We haven't seen this issue on our internal testing projects so we'd need the exact setup you're using to isolate the issue.
