### ISSUE TITLE
[Styling][Responsive] No ability to style the Modal and Details components from ConnectButton

### ISSUE THREAD

**Issue by LeoWW** [thirdweb-dev/js#4278]
We have a responsive app where all size calculations are REM based

The ConnectModal componentry is small (on mobile) because the sizes are all **px** based. We have overrides for the Connect and Details Buttons but we also need them for the Modal and other components. Can you allow styling overrides for those components or suggest a way to customize or override the current styling? Thanks!

![image](https://github.com/user-attachments/assets/dbef900a-178a-439f-8587-e52faba5366e)

**Comment by gregfromstl** [comment]
Hey @LeoWW, is this on a mobile device? Depending on your app's global styling, this should have adjusted accordingly.

We're working on better ways to override the default styles and should have an update here in the coming weeks!

**Comment by LeoWW** [comment]
> Hey @LeoWW, is this on a mobile device? Depending on your app's global styling, this should have adjusted accordingly.

Hey @gregfromstl yes! We're building a PWA app. Our iOS PWA styling doesn't work well with the Thirdweb componentry, would love to have more flexibility for overriding styling here!

**Comment by LeoWW** [comment]
I think it makes sense to instead base the mobile drawer usage on if the device is a mobile device or if the user is in portrait mode -- many devices have high pixel density and will definitely exceed the 640px mobile media query. 

Happy to discuss potential path forward. E.g. If you could expose a style override for the modal or REM-ify the styling that would be appreciated 🙏  Thanks Greg!
