### ISSUE TITLE
Unable to Scroll the Modal When Window Height is Low

### ISSUE THREAD

**Issue by ninpeng** [thirdweb-dev/js#4314]
### Explanation
When the screen height is low, such as in landscape mode on mobile, the modal cannot be scrolled, making it cannot to close or proceed.

### Attach Image
![image](https://github.com/user-attachments/assets/a5f0d1e5-caae-4004-9ce3-be953f890378)

**Comment by adamiller1014** [comment]
I can fix this issue

**Comment by adamiller1014** [comment]
![1](https://github.com/user-attachments/assets/87202ae8-48ee-4331-a512-399225e06ae7)
![2](https://github.com/user-attachments/assets/4a8af562-0e59-4634-a480-bed1ea929e4c)

**Comment by gregfromstl** [comment]
Hey @adamiller1014 feel free to open a PR for this!
