### ISSUE TITLE
`thirdweb deploy` does not respect `--file` option when using `--ci` flag

### ISSUE THREAD

**Issue by RyanHolanda** [thirdweb-dev/js#4461]
When running the `thirdweb deploy` command with the `--ci` flag and the `--file` option, it still gives me the link to deploy contracts that are not in the path specified by `--file`.

## Example:
```bash
thirdweb deploy --ci --file Router
```
The deployment link will still include contracts that do not have "Router" in the filename.

## Solution:
I did a thorough investigation of the code, and it is not filtering the contracts when the `--ci` option is passed: https://github.com/thirdweb-dev/js/blob/7dd2869e240522a467c73f0017f080ee118c5bf0/legacy_packages/cli/src/common/processor.ts#L193-L194.

An easy way to solve this would be to add filtering for the contracts in case the `--file` option is passed, similar to how it is done in this section of the code:
https://github.com/thirdweb-dev/js/blob/7dd2869e240522a467c73f0017f080ee118c5bf0/legacy_packages/cli/src/common/processor.ts#L196-L203

**Comment by jnsdls** [comment]
hey @RyanHolanda thanks for the report and thanks for looking into how it could be fixed, massively appreciate that!

**Comment by RyanHolanda** [comment]
@jnsdls Thanks so much for being open to PRs and allowing us to contribute to the development of thirdweb tools! Unfortunately, I’m pretty busy these days (and likely for the next few weeks). I’d love to dive into contributing to the new v5-based CLI when I have more time, but for now, I’ll have to hold off 🙂

**Comment by jnsdls** [comment]
> @jnsdls Thanks so much for being open to PRs and allowing us to contribute to the development of thirdweb tools! Unfortunately, I’m pretty busy these days (and likely for the next few weeks). I’d love to dive into contributing to the new v5-based CLI when I have more time, but for now, I’ll have to hold off 🙂

totally understandable, we'll pick this bug up as a part of the CLI migration in the near future!

**Comment by gregfromstl** [comment]
This will be included as a fix in the v5 CLI migration, closing this for now
