### ISSUE TITLE
ThirdwebProvider WalletConnet Auto Connect fails

### ISSUE THREAD

**Issue by Blockchain-Junkiez-TH** [thirdweb-dev/js#4476]
Hi ,this is TH from DROPSystem.io (Cohort 2)
 I found a bug of "@thirdweb-dev/react": "^4.9.4"
    
```

    import {  ThirdwebProvider,  walletConnect,} from "@thirdweb-dev/react";
    import { Polygon } from "@thirdweb-dev/chains";

    <ThirdwebProvider
      autoConnect={true}
      clientId={process.env.NEXT_PUBLIC_THIRDWEB_CLIENT_ID}
      activeChain={Polygon}
      supportedChains={[Polygon]}
      supportedWallets={[
         walletConnect(),
      ]}
    >
```

with the above setup , auto connect (with F5/reload) will fail. and gives error to console.log.

However , once I deleted the option 

`
supportedChains={[Polygon]}
`

the error is gone and its able to re-connect after the page is reloaded
I think It's about conflict between walletConnect X  autoConnect X supportedChains

**Comment by jnsdls** [comment]
your assumption is likely correct.

My recommendation would be to use the [v5 sdk](https://portal.thirdweb.com/react/v5/migrate) instead of v4, as it is very likely it is fixed. (And also because the v5 sdk has numerous other advantages.)
