### ISSUE TITLE
'getOwnedTokenIds' function in sdk v5 is a repitition of 'getOwnedNFTs' function

### ISSUE THREAD

**Issue by Kennybabs-py** [thirdweb-dev/js#4520]
As described in the docs, 'getOwnedNFTs' does this:

"Retrieves the owned ERC1155 NFTs for a given wallet address."

While 'getOwnedTokenIds' does this:

"Retrieves the owned ERC1155 tokenIds & the owned balance of each tokenId for a given wallet address."

But there is no 'getOwnedTokenIds'  function exported from the ERC1155 extensions module.

Is this a mistake in the docs or there is no such function?

**Comment by gregfromstl** [comment]
Hi @Kennybabs-py, the return types of these two functions are slightly different. `getOwnedTokenIds` is exported from the ERC1155 extension. Please make sure you're on the latest version.
