### ISSUE TITLE
Get transaction hash of a pending transaction.

### ISSUE THREAD

**Issue by proggeramlug** [thirdweb-dev/js#4615]
When using the `useContractWrite` method I get the transaction hash _after_ the transaction is complete.

I'm using `mutateAsync`here.

I want to get the transaction hash to show the user a link to the explorer so they can follow along.

**Comment by kien-ngo** [comment]
Hi @proggeramlug, does the following code work for you:
```ts
const query = useContractWrite(...);

const transactionHash = query.data?.receipt.transactionHash
```

Also looks like you are using thirdweb SDK v4? It is going to be deprecated soon, we suggest you to migrate to our latest version asap ^ (https://portal.thirdweb.com/typescript/v5/migrate)
