### ISSUE TITLE
Different public address from Magic

### ISSUE THREAD

**Issue by arnaudjnn** [thirdweb-dev/js#473]
I have two different public addresses for the following methods

```
import { EthNetworkConfiguration, Magic } from 'magic-sdk';

const magic = new Magic(process.env.NEXT_PUBLIC_MAGIC_API_KEY, {
  network: process.env.NEXT_PUBLIC_CHAIN_KEY as EthNetworkConfiguration,
});
await magic.auth.loginWithMagicLink({ email:  'myemail@gmail.com'  });

const provider = new ethers.providers.Web3Provider(magic.rpcProvider);
const magicSigner = provider.getSigner();
const address = await magicSigner.getAddress();
console.log(address)

```

and

```
import { useMagic, useAddress } from '@thirdweb-dev/react/evm/connectors/magic';
const connectWithMagic = useMagic();
const address = useAddress()

await connectWithMagic({ email: 'myemail@gmail.com' })
console.log(address)

```

Here is the Sandbox to reproduce the issue: https://github.com/rekolt/magic-link

If I use the same email, I should have one single address, correct? Why do I have two different?

**Comment by joaquim-verges** [comment]
interesting. This might be because of the major version update magic did recentlyl. The react SDK uses an older version. We're working on an updated version in our new separate `@thirdweb-dev/wallets` package. Should help with this issue
