### ISSUE TITLE
dashboard: edit ecosystem partner dialog does not allow editing the prompt setting

### ISSUE THREAD

**Issue by alecananian** [thirdweb-dev/js#4746]
When editing ecosystem partner configuration, clicking the prompt setting doesn't bring down the dropdown so you're not able to switch between prompt and never prompt.

macOS 14.2.1
Brave Browser Version 1.70.117 Chromium: 129.0.6668.59

https://github.com/user-attachments/assets/2aa2894c-b078-44b7-ab26-960f4c607f7a

**Comment by MananTank** [comment]
This option is no longer relevant, We are removing it in https://github.com/thirdweb-dev/js/pull/4745
