### ISSUE TITLE
using useReadContract to call a contract that returns a tuple does not  retrieving the data

### ISSUE THREAD

**Issue by smallfu6** [thirdweb-dev/js#4758]
When I use **useReadContract** to call a read function, the function signature is：
``` typescript
const MethodGetLeaderboard = "function getTop10Players() returns (tuple[10])";

// other code


export const GetLeaderBoard = () => {
  const { data, isLoading } = useReadContract({
    contract,
    method: MethodGetLeaderboard,
    params: [],
  });

  const leaderboard = data;
  console.log(leaderboard, isLoading);
  return leaderboard;
};
```

I cannot get the return value of the function. Can **useReadContract** parse tuple data?

**Comment by gregfromstl** [comment]
Hey @smallfu6, could your try defining the full tuple?
`const MethodGetLeaderboard = "function getTop10Players() returns ((string memory, bool))";`

**Comment by smallfu6** [comment]
@gregfromstl    This solved my problem, thank you!
