### ISSUE TITLE
@thirdweb-dev/auth/next 'could not find name'

### ISSUE THREAD

**Issue by gtandes** [thirdweb-dev/js#485]
Good day ser. I'm trying to code along the token-gated NFT tutorial by Thirdweb in this article:

https://blog.thirdweb.com/guides/nft-gated-website/

However, during installation of the Auth SDK, I get an error about NextJS13 conflict. I tried using legacy-peer-deps, however after installation, no data could be pulled from ThirdWebAuth. Might you know what's the issue here?
![image](https://user-images.githubusercontent.com/58809832/211401241-631bb034-c2c0-43e4-a9bb-c7beee62e5c0.png)

**Comment by nachoiacovino** [comment]
hello @gtandes, seems like you have a typo with using lowercase w instead of uppercase? so it should be `ThirdWebAuth`instead of `ThirdwebAuth`

tell me if that helps!
