### ISSUE TITLE
Deployer events addDeployListener not receiving data

### ISSUE THREAD

**Issue by cmayorga** [thirdweb-dev/js#487]
emitTransactionListener is not emitting events because deployViaFactory is creating a new instance of ContractFactory and losing reference to previously added listener.

The steps i follow for above process are:

Code tried:

`sdk.deployer.events.addTransactionListener((event: any) => {
        console.log(event, "from event");
      });
   

const contractAddress = await sdk.deployer.deployNFTCollection({
      name: "My Collection NFT",
      primary_sale_recipient: "0xd6f71925b31......................625E6850DB",
    });`

Snippet is not working. 

What i also noticed:
When i logged sdk.deployer instance  there is no such  event name as addTransactionListener available in the context. Instead there is only one event is there named  addDeployListener
But when i logged contract instance from useContract hook i am able to see that addTransactionListener  is available in the context.

After debugging i noticed the issue is coming from:

https://github.com/thirdweb-dev/js/blob/main/packages/sdk/src/evm/core/classes/contract-deployer.ts

![image](https://user-images.githubusercontent.com/5519725/211486925-1eb64388-6fe1-451a-8447-ce241b096111.png)

**Comment by cmayorga** [comment]
Actually working in a proposed fix, FYI

**Comment by joaquim-verges** [comment]
thank you for the report! fixed with https://github.com/thirdweb-dev/js/pull/494

you can test it by installing the nightly build:
```
npm i @thirdweb-dev/sdk@nightly
```
