### ISSUE TITLE
Add free domain name and version to forwarder for Defender gasless transaction

### ISSUE THREAD

**Issue by EdoCrippaOfficial** [thirdweb-dev/js#497]
Hi, I found the domain for the forwarder using openzeppelin defender hardcoded into the SDK [here](https://github.com/thirdweb-dev/js/blob/782b58d3f6a3b49ff9b3d837551db5161f96171a/packages/sdk/src/evm/core/classes/contract-wrapper.ts#L691)
```
domain = {
        name: "GSNv2 Forwarder",
        version: "0.0.1",
      };
```

I would find it useful to be able to specify the domain for the forwarder, so that I can create my own forwarder and use that one instead of the one provided [here](https://blockscan.com/address/0xc82BbE41f2cF04e3a8efA18F7032BDD7f6d98a81), and specified in the [doc](https://portal.thirdweb.com/sdk/advanced-features/gasless-transactions)

Moreover, this can pair well with the pre-built contract [https://thirdweb.com/thirdweb.eth/Forwarder](Forwarder), that has the constructor `EIP712("MinimalForwarder", "0.0.1")` so that anyone can use his own contract with zero effort.

It can become easily a property of the gasless option of the sdk.

**Comment by joaquim-verges** [comment]
Makes sense to me, if you're up to it feel free to open a PR! otherwise we'll tackle it
