### ISSUE TITLE
Problem when installing React SDK

### ISSUE THREAD

**Issue by MedNewton** [thirdweb-dev/js#503]
When trying to install Thirdweb SDK in my react project, I get this error:

npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: wagmi@0.2.28
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   peer react@"^16 || ^17 || ^18" from @headlessui/react@1.7.7
npm WARN   node_modules/@headlessui/react
npm WARN     @headlessui/react@"^1.7.2" from the root project
npm WARN   35 more (framer-motion, jotai, little-state-machine, nano-css, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^17.0.0" from wagmi@0.2.28
npm WARN node_modules/wagmi
npm WARN   wagmi@"^0.2.28" from @thirdweb-dev/react@3.6.10
npm WARN   node_modules/@thirdweb-dev/react
npm WARN
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^17.0.0" from wagmi@0.2.28
npm WARN   node_modules/wagmi
npm WARN     wagmi@"^0.2.28" from @thirdweb-dev/react@3.6.10
npm WARN     node_modules/@thirdweb-dev/react
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by joaquim-verges** [comment]
@MedNewton I think this might be an error with your local npm cache, can you try deleting the npm cache and trying again?

**Comment by juanjlunar** [comment]
This is still happening.

npm ERR! As of npm@5, the npm cache self-heals from corruption issues
/home/app $ npm i @thirdweb-dev/react @thirdweb-dev/sdk
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: wagmi@0.2.28
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   peerOptional react@"^16.9.0 || ^17.0.0 || ^18" from @reduxjs/toolkit@1.9.3
npm WARN   node_modules/@reduxjs/toolkit
npm WARN     @reduxjs/toolkit@"^1.9.3" from the root project
npm WARN   17 more (next, next-redux-wrapper, react-dom, react-i18next, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^17.0.0" from wagmi@0.2.28
npm WARN node_modules/wagmi
npm WARN   wagmi@"^0.2.28" from @thirdweb-dev/react@3.10.3
npm WARN   node_modules/@thirdweb-dev/react
npm WARN 
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^17.0.0" from wagmi@0.2.28
npm WARN   node_modules/wagmi
npm WARN     wagmi@"^0.2.28" from @thirdweb-dev/react@3.10.3
npm WARN     node_modules/@thirdweb-dev/react
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -2
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2023-03-29T22_05_00_548Z-debug-0.log

This is  a new Nextjs App installed using npx create-next-app@latest

`package.json`
```
{
  "name": "app-name",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@reduxjs/toolkit": "^1.9.3",
    "@types/node": "18.15.11",
    "@types/react": "18.0.31",
    "@types/react-dom": "18.0.11",
    "i18next": "^22.4.13",
    "next": "13.2.4",
    "next-redux-wrapper": "^8.1.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-i18next": "^12.2.0",
    "react-redux": "^8.0.5",
    "react-toastify": "^9.1.2",
    "redux-persist": "^6.0.0",
    "typescript": "5.0.2"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^5.56.0",
    "@typescript-eslint/parser": "^5.56.0",
    "eslint": "^8.36.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-config-airbnb-typescript": "^17.0.0",
    "eslint-config-next": "^13.2.4",
    "eslint-config-prettier": "^8.8.0",
    "eslint-plugin-import": "^2.27.5",
    "eslint-plugin-jsx-a11y": "^6.7.1",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-react": "^7.32.2",
    "eslint-plugin-react-hooks": "^4.6.0",
    "prettier": "^2.8.7"
  }
}

```
