### ISSUE TITLE
Wallet QR Code Fails to Load When Connecting

### ISSUE THREAD

**Issue by TahaKhanAbdalli** [thirdweb-dev/js#5033]
I’m facing an issue when trying to connect a wallet. I’m using the ConnectButton for wallet connection, but the QR code for the wallet is not being fetched correctly. The following error appears:
<img width="491" alt="Screenshot 2024-10-15 at 12 53 58 PM" src="https://github.com/user-attachments/assets/ac2a7269-1e84-45c0-a0f3-c9b066541c0d">
<img width="368" alt="Screenshot 2024-10-15 at 12 53 47 PM" src="https://github.com/user-attachments/assets/495f2fb9-ccde-47bd-a2ed-95205f75c116">

Dependencies:
React v18.2.0
React-dom v18.2.0
thirdweb v5.58.3

**Comment by Julietnacy** [comment]
@TahaKhanAbdalli Make sure your internet connection is stable. Sometimes, a weak connection can cause issues with fetching the QR code.

**Comment by TahaKhanAbdalli** [comment]
I have a stable internet connection, but I'm still experiencing the same issue.

**Comment by Julietnacy** [comment]
@TahaKhanAbdalli If your internet connection is stable and you’re still having issues, try uninstalling and reinstalling the app can fix bugs.

**Comment by TahaKhanAbdalli** [comment]
@Julietnacy I've taken fresh clone of app but still facing same issue. Let me share configuration.
`const App = () => {
return <ThirdwebProvider
        clientId={CLIENT_ID}
      >
      <Home/>
      // Remaining Routes
      </ThirdwebProvider>
}`

Here is ConnectButton component:
`
const Home = () => {

const client = createThirdwebClient({
  clientId: clientID
});


const connectButtonWallets = [
  createWallet("io.metamask"),
  createWallet("com.coinbase.wallet"),
  createWallet("com.trustwallet.app"),
  createWallet("com.binance"),
  createWallet("com.okex.wallet"),
  createWallet("me.rainbow"),
];

return <ConnectButton
          client={client}
          modalSize={"wide"}
          wallets={connectButtonWallets}
          />
}
`

**Comment by Julietnacy** [comment]
@TahaKhanAbdalli It looks like you've set up the `ThirdwebProvider` and `ConnectButton` correctly. Have you checked if the `CLIENT_ID` and `clientID` are properly defined and valid? Sometimes issues can arise from incorrect or missing credentials.

**Comment by TahaKhanAbdalli** [comment]
@Julietnacy Still having same issue. I think this issue relates to [issue-4064](https://github.com/WalletConnect/walletconnect-monorepo/issues/4064)

**Comment by gregfromstl** [comment]
Hey @TahaKhanAbdalli, I cannot replicate this issue in the latest version of our SDK. Could you provide a minimal reproduction so I can clone and run to see the problem? Thanks!
