### ISSUE TITLE
eth_estimateUserOperationGas bad response format

### ISSUE THREAD

**Issue by zpoken** [thirdweb-dev/js#5037]
**_eth_estimateUserOperationGas_** response doesn`t include **_verificationGas_** which added to **_estimateUserOpGas_** function https://github.com/thirdweb-dev/js/blob/main/packages/thirdweb/src/wallets/smart/lib/bundler.ts#L87
<img width="460" alt="Знімок екрана 2024-10-15 о 17 08 49" src="https://github.com/user-attachments/assets/33cea162-689c-4e56-83f2-45dc83f7dd47">

**Comment by joaquim-verges** [comment]
thanks for the report @zpoken - we just fixed this, making a release right now
