### ISSUE TITLE
[REACT]: `isLoading` state for the `useLogin` hook in the solana package

### ISSUE THREAD

**Issue by anuraglol** [thirdweb-dev/js#505]
A returned `isLoading` state from the `useLogin` hook would be helpful to show loading state while signing the message.

**Comment by joaquim-verges** [comment]
We're about to merge a big update to the auth package which adds exactly this! cc @adam-maj

**Comment by anuraglol** [comment]
> We're about to merge a big update to the auth package which adds exactly this! cc @adam-maj

Awesome! 😀
