### ISSUE TITLE
Brave Wallet is labeled as Bitski in connect flow

### ISSUE THREAD

**Issue by alecananian** [thirdweb-dev/js#5116]
As far as I can tell there's no connection between Brave Wallet and Bitski (which merged with Phantom), so seeing info about Bitski when trying to connect a Brave wallet was a bit confusing

https://github.com/thirdweb-dev/js/blob/main/packages/thirdweb/src/wallets/__generated__/wallet/com.brave.wallet/index.ts

<img width="402" alt="Screenshot 2024-10-21 at 3 46 58 PM" src="https://github.com/user-attachments/assets/ca66d2a5-18a9-47e3-9548-4afd54b0893b">

**Comment by gregfromstl** [comment]
Hey @alecananian, thanks for reporting this! I'll have a fix up soon

**Comment by joaquim-verges** [comment]
fix is released
