### ISSUE TITLE
`getUser` produces different results for lowercased and checksum wallet addresses

### ISSUE THREAD

**Issue by alecananian** [thirdweb-dev/js#5130]
When using the `getUser` function or the `/api/2023-11-30/embedded-wallet/user-details` endpoint and querying by `walletAddress`, the result is blank unless you provide a checksum-style wallet address.

Steps to reproduce:

- Lowercase an ecosystem or in-app wallet address and query the endpoint (e.g., https://embedded-wallet.thirdweb.com/api/2023-11-30/embedded-wallet/user-details?queryBy=walletAddress&walletAddress=0x2fbf87b85f6a93e5c4f4b567150d7b4fa057c092). Note that the result is `[]` and the request took >2s.
- Checksum an ecosystem or in-app wallet address and query the endpoint (e.g., https://embedded-wallet.thirdweb.com/api/2023-11-30/embedded-wallet/user-details?queryBy=walletAddress&walletAddress=0x2FBF87b85f6a93E5C4F4b567150D7b4Fa057c092). Note that the result returns user details as expected in <1s.

I don't believe the API endpoint is open source, and I figured it should be fixed at the API level.

**Comment by joaquim-verges** [comment]
ty @alecananian ! we'll fix that in the api

**Comment by joaquim-verges** [comment]
@alecananian this is fixed
