### ISSUE TITLE
Browserify doesn't work anymore

### ISSUE THREAD

**Issue by inartin** [thirdweb-dev/js#515]
Hi, I was creating a bundle with browserify from @thirdweb-dev/sdk to be used in my environment which is not React and requires vanilla js basically (can't use module type)

Until version  3.4 the bundle worked like a charm.

Now I'm trying to update to the latest version and I get these errors:

<img width="952" alt="Screenshot 2023-01-26 at 19 07 28" src="https://user-images.githubusercontent.com/17723007/214902446-c182a45a-e56d-496c-a8e5-f91c5e34ddcc.png">

This happens right after the page loads, without initiating anything.

**Comment by inartin** [comment]
Update:
I found out that it works up **until version 3.6.9**
Something changed in the minor update 3.6.10

**Comment by inartin** [comment]
Hey there, any updates on this bug?
We are stuck on old version of SDK

**Comment by warengonzaga** [comment]
@adam-maj or @MananTank do we have update on this?
