### ISSUE TITLE
ConnectButton Component Breaks the app

### ISSUE THREAD

**Issue by hamdoudhakem** [thirdweb-dev/js#5159]
When I started my thridweb project using the Vite template the page was completly empty 
![image](https://github.com/user-attachments/assets/0cff2759-1574-4b69-8ce4-b979418f77ea)

After some debugging I found out that whenever I add the `ConnectButton` component the page breaks, here is the main page after commenting it:
![image](https://github.com/user-attachments/assets/fc8ea9ef-bb5e-47f1-95b8-d42af6983123)

I also have noticed that whenever I add it or get rid of it hot reload stops working and I need to reload manualy (but when it's commented out hot reload starts working again).

Any Idea on how I can fix this?

**Comment by kien-ngo** [comment]
Hey there, do you see any error printed out in your browser console when the app breaks?

**Comment by gregfromstl** [comment]
Hey @hamdoudhakem, I cannot reproduce this on the latest version of the Vite template. Please provide a minimal reproduction I can clone and run to replicate the issue. Once we have that we'll be able to find a solution for you. Thanks!
