### ISSUE TITLE
Allow change wording on wallet connectors

### ISSUE THREAD

**Issue by LeonelSalvo** [thirdweb-dev/js#5221]
`export const wallets = [inAppWallet(inAppWalletAuth), createWallet('io.metamask'), createWallet('com.coinbase.wallet')];
`

Would be amazing to have an option to change "Social Login" wordingo n inAppWalletAuth

**Comment by Yash094** [comment]
Hey @LeonelSalvo 

You can create a feature request to include this in the next versions at [here](https://feedback.thirdweb.com/).

You can also use a custom UI to customize such details: [Learn More](https://portal.thirdweb.com/connect/sign-in/Custom-UI).
