### ISSUE TITLE
transactions block explorer links navigate to 404 page on Treasure Topaz network

### ISSUE THREAD

**Issue by alecananian** [thirdweb-dev/js#5225]
Steps to reproduce:
- Send a transaction through on the Treasure Topaz network
- Navigate to the connected account modal > Transactions
- Click on any of the sent transactions in the list

You are taken to a URL like https://topaz.treasurescan.io//tx/0x6e082d7cda8aed2401799c1f5ec57a1af4d92dde5f944caac064fe02ac1ccca8 (note the double slashes), which is an invalid that produces a 404 page. The correct page has a single slash: https://topaz.treasurescan.io/tx/0x6e082d7cda8aed2401799c1f5ec57a1af4d92dde5f944caac064fe02ac1ccca8

**Comment by Yash094** [comment]
Hey @alecananian 

I can indeed replicate the issue, thank you for pointing this out, I'll work on getting this fixed.

**Comment by joaquim-verges** [comment]
fixed here https://github.com/thirdweb-dev/js/pull/5237
