### ISSUE TITLE
Support `next dev --turbo`

### ISSUE THREAD

**Issue by sshmaxime** [thirdweb-dev/js#5371]
Hello, I'm using `thirdweb@5.67.0` and still face this error: `...but the module factory is not available. It might have been deleted in an HMR update.`

This error goes away when I remove the `--turbo` from my command. Do you have any plans to support this `--turbo` option ?

**Comment by gregfromstl** [comment]
Hey @sshmaxime, could you please provide a minimal reproduction of the error you're facing and we can investigate

**Comment by sshmaxime** [comment]
Please re-open the issue, it's been known that you are not supporting `turbo` yet, cf https://github.com/thirdweb-dev/js/issues/5087#issuecomment-2424145144.

I just want to make sure that the issue stays here until a fixed have been provided 🙏
