### ISSUE TITLE
can't use thirdweb/wallets

### ISSUE THREAD

**Issue by ngocan3897** [thirdweb-dev/js#5377]
in react-native 0.72.6
after I install thirdweb , I can't use any function that import from child of thirdweb 
<img width="440" alt="Screenshot 2024-11-11 at 10 40 32 AM" src="https://github.com/user-attachments/assets/f0151c78-f817-4dcd-b991-d9dbd618109e">

**Comment by joaquim-verges** [comment]
hey @ngocan3897 - did you follow the instructions here? https://portal.thirdweb.com/react-native/v5/getting-started#Edit%20your%20%60metro.config.js%60

you need a flag in your metro.config.js to resolve package exports

**Comment by ngocan3897** [comment]
@joaquim-verges as I am using react-native-cli , so that I update my metro.config.js file like this: 

// Import the required Metro config from @react-native/metro-config
const { getDefaultConfig } = require('@react-native/metro-config');

module.exports = async () => {
  const {
    resolver: { sourceExts, assetExts },
  } = await getDefaultConfig();

  return {
    transformer: {
      babelTransformerPath: require.resolve('react-native-svg-transformer'),
      getTransformOptions: async () => ({
        transform: {
          experimentalImportSupport: false,
          inlineRequires: true,
        },
      }),
    },
    resolver: {
      assetExts: assetExts.filter((ext) => ext !== 'svg'),
      sourceExts: [...sourceExts, 'svg', 'jsx', 'js', 'json', 'ts', 'tsx'],

      // Enable package exports and condition names to resolve them properly
      unstable_enablePackageExports: true,
      unstable_conditionNames: ['react-native', 'browser', 'require'],
    },
  };
};
