### ISSUE TITLE
private key management question

### ISSUE THREAD

**Issue by haowang1013** [thirdweb-dev/js#5378]
Hi,

We're evaluating MPC wallet solutions and third web is one of the candidates. I've been playing with the react sdk and it seems to do everything the doc suggests. I did however look into how the MPC part works and got confused.

As I understand it MPC works by reconstructing the private key from the user shard and another shard kept in KMS so signing should happen locally on user's device, right? In my example (by following the react tutorial) the signing seems to happen in third web's backend? Specifically [here](https://github.com/thirdweb-dev/js/blob/main/packages/thirdweb/src/wallets/in-app/core/actions/sign-message.enclave.ts#L27-L43).

The client only sends the auth token saved in local storage, what roles does the user shard play in this flow, or is the user shard even used? Or perhaps I'm missing something obvious here?

<img width="667" alt="image" src="https://github.com/user-attachments/assets/cae73ce8-867c-49da-a7a8-f49fdf4104da">

**Comment by gregfromstl** [comment]
Hey @haowang1013, the signing occurs in an iframe embedded on the page. This is so the developer cannot access the user's private key within the app itself.

**Comment by haowang1013** [comment]
> Hey @haowang1013, the signing occurs in an iframe embedded on the page. This is so the developer cannot access the user's private key within the app itself.

Hi, not sure if I follow, the code I quoted above shows that the signing doesn't happen on the client side, no?

```
  const response = await clientFetch(
    `${getThirdwebBaseUrl("inAppWallet")}/api/v1/enclave-wallet/sign-message`,
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-thirdweb-client-id": client.clientId,
        Authorization: `Bearer embedded-wallet-token:${authToken}`,
      },
      body: stringify({
        messagePayload: {
          message,
          isRaw,
        },
      }),
    },
  );

  if (!response.ok) {
    throw new Error("Failed to sign message");
  }

  const signedMessage = (await response.json()) as {
    r: string;
    s: string;
    v: number;
    signature: string;
    hash: string;
  };
  return signedMessage;
```
