### ISSUE TITLE
Framework icon not displaying

### ISSUE THREAD

**Issue by wheval** [thirdweb-dev/js#5402]
The icon for the `Support for Frameworks` feature is not displaying. The link to the  [deploy page](https://portal.thirdweb.com/contracts/deploy/overview#features) of the documentation.

Here is a screenshot of how it looks.

![Screenshot (46)](https://github.com/user-attachments/assets/60376bb9-bf43-4569-8c0d-23d9de4917df)

PS: I would love to fix this, I created a PR that fixes this

**Comment by gregfromstl** [comment]
Hey @wheval, I can't seem to find your PR that fixes it. Could you reference this issue on there so it links?
