### ISSUE TITLE
useActiveAccount undefined

### ISSUE THREAD

**Issue by ngocan3897** [thirdweb-dev/js#5428]
I have already connected to google and have an account as the response of connect . but when I use useActiveAccount hook , I got undefined . do I need to do set account step after connect ? 

<img width="566" alt="Screenshot 2024-11-15 at 9 14 12 AM" src="https://github.com/user-attachments/assets/5086b4e8-9919-44f0-8f5d-5a0dc76fac44">

**Comment by kien-ngo** [comment]
Hey there, can you show us how you are using the hook?

**Comment by ngocan3897** [comment]
@kien-ngo hi, I'm using the hook like this 

![Screenshot 2024-11-17 at 1 57 26 PM](https://github.com/user-attachments/assets/e8b45b6c-4099-4f97-b771-de2052fdf814)
![Screenshot 2024-11-17 at 2 01 15 PM](https://github.com/user-attachments/assets/b10c363f-860c-48ed-ba12-f50ca4604419)

**Comment by ngocan3897** [comment]
@MananTank hi, thank you for your reply but the response of wallet.connect is an account , not a wallet

**Comment by MananTank** [comment]
@ngocan3897 You already have access to `Wallet` object using `this.wallet` in the code you attached

**Comment by ngocan3897** [comment]
@MananTank thank you , the hook now working . But when I close the app and reopen it again , the hook with get undefined again , should I do something to save it ?

**Comment by MananTank** [comment]
@ngocan3897 You can add a [AutoConnect](https://portal.thirdweb.com/react/v5/components/AutoConnect) component to automatically reconnect last connected wallet
