### ISSUE TITLE
Suggested Extensions : Permission : Page not found

### ISSUE THREAD

**Issue by srikanth-programmer** [thirdweb-dev/js#5441]
![thridweb cli](https://github.com/user-attachments/assets/465d6a9a-140a-48f2-b97c-c6130b60b89c)

The Url provided in the CLI is not found

**Comment by gregfromstl** [comment]
Hey @srikanth-programmer, you can find the correct link for this extension here: https://portal.thirdweb.com/contracts/build/extensions/general/Permissions

We'll fix this in the next CLI release
