### ISSUE TITLE
ConnectEmbed disconnects on page refresh

### ISSUE THREAD

**Issue by lelerukjaymoh** [thirdweb-dev/js#5456]
How to reproduce
- Once you have connected to a wallet using ConnectEmbed refresh the page. On refresh, the active wallet is disconnected. 

You can test it on the connect embed preview here -> https://connect-embed-example.thirdweb-preview.com/

I have tested this on the latest thirdweb version and the same issue occurs. 

Since Autoconnect is already included in connectEmbed the expected behaviour is if the page is reloaded it would automatically connects the last connected wallet.

**Comment by gregfromstl** [comment]
Hey @lelerukjaymoh, I tried this on the link you provided and it works fine (although it appears that link is also using a very outdated version of the SDK). If you can provide another example or maybe more context on your environment (browser, code snippets, etc) we can reopen this issue and investigate.
