### ISSUE TITLE
Failed to sign transaction

### ISSUE THREAD

**Issue by R-qanawati** [thirdweb-dev/js#5492]
This is an error that only occurs when using social logins. This code works perfectly when logged into a web3 wallet.

Is there a different method when they are signed in with socials?

`<TransactionButton
                          style={{
                            width: "100%",
                            background:
                              "linear-gradient(to right, #facc15, #eab308)",
                            color: "black",
                            fontWeight: 600,
                            padding: "1.5rem 0",
                            borderRadius: "0.75rem",
                            transition: "all 300ms",
                            display: "flex",
                            justifyContent: "center",
                            alignItems: "center",
                          }}
                          disabled={!amount}
                          transaction={() => {
                            return prepareTransaction({
                              to: API_WALLET,
                              value: toWei(amount),
                              chain: defineChain(42161),
                              client,
                            });
                          }}
                          onTransactionConfirmed={async (receipt) => {
                            setIsLoadingTransaction(true);
                            const purchase = await purchaseEth(
                              receipt.transactionHash
                            );
                            console.log("Transaction confirmed", purchase);
                            toast({
                              description: (
                                <TransactionToast
                                  type="deposit"
                                  ethAmount={purchase?.data.ethAmount}
                                  chipsAmount={purchase?.data.chipsAmount}
                                />
                              ),
                            });
                            setIsLoadingTransaction(false);
                            fetchData();
                          }}
                        >
                          {isLoadingTransaction ? (
                            <div className="flex items-center gap-2">
                              <div className="animate-spin w-4 h-4 border-2 border-black border-t-transparent rounded-full" />
                              Processing...
                            </div>
                          ) : (
                            "Add Funds"
                          )}
                        </TransactionButton>`

**Comment by gregfromstl** [comment]
Hey @R-qanawati, please provide the version of the SDK you're using along with a full reproduction we can pull down and easily run to reproduce the issue.

**Comment by R-qanawati** [comment]
@gregfromstl hey Greg! Thank you for the quick response.

After upgrading to the latest thirdweb version, it is working as intended now
