### ISSUE TITLE
`useActiveAccount` bug when using AA

### ISSUE THREAD

**Issue by sshmaxime** [thirdweb-dev/js#5537]
# Bug:
With AA enabled, upon first connection, changing the connected EOA doesn't update the AA (`useActiveAccount`) until force refresh.

# Reproduction:

1 - Go on https://playground.thirdweb.com/connect/account-abstraction/sponsor
2 - Disconnect everything
3 - Connect your EOA, check the Smart Account address, change your connected EOA and see the Smart Account address not change.

See the video for details:

https://github.com/user-attachments/assets/acd25cb3-b3ae-4903-9916-4f92c4a85dd4

4 - Now refresh the page
5 - Now changing the EOA will update the Smart Account address

See the video for details:

https://github.com/user-attachments/assets/0bff156a-fe13-42c2-9489-ed3a408b87a4

# Expectations:

I expect the step 5 to work at step 3.

**Comment by joaquim-verges** [comment]
thanks for the detailed report @sshmaxime - we're looking into this

**Comment by sshmaxime** [comment]
@joaquim-verges Any ETA ?

**Comment by joaquim-verges** [comment]
@sshmaxime fix will be in the next version once this merges: https://github.com/thirdweb-dev/js/pull/5592
