### ISSUE TITLE
No auth token found when signing message

### ISSUE THREAD

**Issue by LeonelSalvo** [thirdweb-dev/js#5539]
Issue started last week after a redeploy, useActiveAccount or any other ways to get to the signMessage() will throw this error for email logged wallets using In-App wallet with default settings. Weird thing, is not happening with metamask or other log in ways.

Looking into localstorage, i see that previous deploys of my app, using thirdweb sdk v5, had wallets as "sharded", now are "enclave" and methods from account objects from email logins fail with this.

Looking into localstorage, i see in my previous versions a lot of data populated, but in the new ones ( the ones that email fails ) never gets populated

Actual storage:
![image](https://github.com/user-attachments/assets/11a4eb6c-1605-46e5-8eee-e50a2a0ac06d)

Previous:
![image](https://github.com/user-attachments/assets/ee933558-e3d5-4782-bd18-fec7233709b5)

Looking into .js bundled sources i see that the signMessage() fn looks for the auth token, like "authCookie" and is not defined.

**Comment by gregfromstl** [comment]
Hey @LeonelSalvo, could you please provide the version of the SDK you're using

**Comment by LeonelSalvo** [comment]
From `5.68` to `5.71.0` happening

**Comment by LeonelSalvo** [comment]
Following through the sdk, seems like the postWalletSetUp() call is not saving the authCookie, the network request from email OTP process brings storedToken good thou:

```
    "storedToken": {
        "jwtToken": "BRINGS_THE_JWT",
        "authProvider": "Email",
        "developerClientId": "DEV_ID",
        "authDetails": {
            ... BRINGS_DETAILS
        },
        "cookieString": "BRINGS_THE_COOKIE_STRING",
        "isNewUser": false,
        "shouldStoreCookieString": true
    }
```

```
        this.wallet = await this.initializeWallet(
          authResult.storedToken.cookieString,
        );

        if (!this.wallet) {
          throw new Error("Failed to initialize wallet"); // Not triggerin, so its OK
        }

        const deviceShareStored =
          "deviceShareStored" in authResult.walletDetails
            ? authResult.walletDetails.deviceShareStored
            : undefined;

        // Here ? im not finding `${AUTH_TOKEN_LOCAL_STORAGE_PREFIX}-${key}`
        await this.wallet.postWalletSetUp({ 
          storedToken: authResult.storedToken,
          deviceShareStored,
        });
```

**Comment by gregfromstl** [comment]
Hey @LeonelSalvo, thanks for the details on this. I can't seem to reproduce this by trying to replicate your setup. Could you please provide a minimal reproduction and I can look into it further? Also, I'm assuming you've tried clearing your local storage and refreshing already?

**Comment by LeonelSalvo** [comment]
Hey @gregfromstl , yes already cleared and refreshed, even going back or moving between `5.68` and `5.72` im seeing this issue

Have been working past 8 months with same code, just this week started to happen after migration

Im working to create a small implementation with this

**Comment by LeonelSalvo** [comment]
Doing the small repro, i reached old code where we need to clean user localstorage before the sign ( previously without problem, since embedded wallet relayed on cookies instead ) since authCookie is now on localstorage, not necessary a problem on your end then

We need to find a workaround for it on our side

**Comment by LeonelSalvo** [comment]
Thanks, just for the record, I would like to suggest adding some kind of warning or alternative flow... to avoid this when the auth token not found error is triggered ( We had the localStorage to ourselves, not great to clear it, but still weird to have the auth token there )

Maybe:
- To give feedback on cache clearing, because the user is still able to do this : 1.
- Or to handle more gracefully the loss of token, getting it maybe in the future through your back ends again or make available a way to retrieve it for developers ( a refetch, or check )
