### ISSUE TITLE
`useConnectModal` auth props is forced to undefined

### ISSUE THREAD

**Issue by sshmaxime** [thirdweb-dev/js#5615]
Check the `useConnectModal.tsx` file. Line 134.

**Comment by gregfromstl** [comment]
Hey @sshmaxime, thanks for pointing this out. As the TODO says, we currently don't support auth through the `useConnectModal` hook and it shouldn't be enabled as a prop there. I'm going to remove the prop for now, and add a feature to the backlog to add support for it.
