### ISSUE TITLE
What's your take when forcing sign in but user change EOA

### ISSUE THREAD

**Issue by sshmaxime** [thirdweb-dev/js#5624]
I think there is a decision to be done on your side about what happened when we have auth in place but the user changes its EOA. As of now, nothing happens. But in reality, if a user sign in with its EOA and change its EOA through Metasmak or Rabby then it's not the same user and it should probably be disconnected. What's your take on that ?

**Comment by gregfromstl** [comment]
Hey @sshmaxime, there's a listener on the wallet instance so any time the user changes accounts it should also update the account on our end (not disconnect). This is assuming the wallet properly triggers an `accountChanged` event.

If you're not seeing this behavior, could you share a reproduction and we can take a look?
