### ISSUE TITLE
does useSendTransaction support pay modal for react native ? 

### ISSUE THREAD

**Issue by ngocan3897** [thirdweb-dev/js#5675]
I am using useSendTransaction but nothing happened .

<img width="470" alt="Screenshot 2024-12-10 at 12 05 29 PM" src="https://github.com/user-attachments/assets/2960a08d-f655-45b7-93bb-1b95b1ce3176">

**Comment by joaquim-verges** [comment]
@ngocan3897 pay transaction modal is not currently supported it in react native.

curious how do you intend to use it? is it to pay with another wallet? or for fiat onramp?

**Comment by joaquim-verges** [comment]
For native mobile apps there is a bit more complexity around fiat onramp due to app store restrictions. But we'll be working on enabling cross chain / pay from another wallet functionality soon.<br><br>Btw open to contributions!
