### ISSUE TITLE
Support Expo Go sdk 51 by making coinbase-wallet optional

### ISSUE THREAD

**Issue by Jeanclaudeaoun** [thirdweb-dev/js#5743]
I believe if we replace mmkv with @react-native-async-storage/async-storage then thirweb would support expo without prebuild.

making the below optional:
@coinbase/wallet-mobile-sdk
react-native-mmkv

npx expo install react-native-get-random-values @react-native-community/netinfo expo-application @react-native-async-storage/async-storage expo-web-browser expo-linking react-native-aes-gcm-crypto react-native-quick-crypto amazon-cognito-identity-js react-native-svg @walletconnect/react-native-compat react-native-passkey

**Comment by Jeanclaudeaoun** [comment]
similar to https://docs.reown.com/appkit/react-native/core/installation#enable-coinbase-wallet

**Comment by joaquim-verges** [comment]
@Jeanclaudeaoun thanks for the suggestion! i think its a great idea and would love to support expo go, but the biggest blocker for that is actually `react-native-quick-crypto` which still requires a development build. 

open to PRs / suggestions on this though, we _could_ make that optional as well in theory
