### ISSUE TITLE
How to connect with Walletconnect (on thirdweb connect ) and let Wagmi synced

### ISSUE THREAD

**Issue by iamcryptofennec** [thirdweb-dev/js#5751]
I follow this one : https://github.com/thirdweb-example/wagmi-thirdweb

Everything seem fine with Rabby, Metamask it synced well.

But when I try with WalletConnect it doesn't. the walletClient object will be "undefined" when connected to WalletConnect.

![image](https://github.com/user-attachments/assets/cdc6df6c-98c5-43f1-b9a5-2c6e68746bdf)

**Comment by gregfromstl** [comment]
Hey @iamcryptofennec, I wasn't able to reproduce this using our template. If you provide a reproduction, we can investigate further.

**Comment by iamcryptofennec** [comment]
Ok, I think I misunderstand about Wagmi <> Thirdweb.

The purpose that I want is connect Walletconnect via Thirdweb Connect Modal and Wagmi can catch the thirdweb session.

After I changed to Wagmi Connect Modal insteads. I can use the example to create a new wallet adapter to thirdweb.

Anyway, I think it should have a way to let Wagmi knows that Thirdweb connected with Walletconnect. (Injected wallet is fine)

**Comment by gregfromstl** [comment]
Ah, I see. If you want to go from Thirdweb to wagmi, you'll need to use the wagmi connector from [@thirdweb-dev/wagmi-adapter.](https://blog.thirdweb.com/changelog/in-app-smart-wallet-wagmi-connector-2/) Try that out and let me know if it works

**Comment by iamcryptofennec** [comment]
> Ah, I see. If you want to go from Thirdweb to wagmi, you'll need to use the wagmi connector from [@thirdweb-dev/wagmi-adapter.](https://blog.thirdweb.com/changelog/in-app-smart-wallet-wagmi-connector-2/) Try that out and let me know if it works

But this one is for InAppWallet isn't (social login)? I think walletconnect doesn't includes on InAppWallet.
