### ISSUE TITLE
Allowlist csv file bulk application issue in NFT ClaimConditions

### ISSUE THREAD

**Issue by howdyfrom2019** [thirdweb-dev/js#5791]
When attempting to upload a CSV file to set the allowlist for NFT ClaimConditions, the allowlist is applied in bulk without specific granularity. This causes unintended behavior for conditional NFT claims.

## Steps to Reproduce:
Navigate to the NFT ClaimConditions section in the thirdweb dashboard.
Upload a CSV file containing the allowlist addresses.
Observe that the allowlist is applied in bulk.
Expected Behavior:
The allowlist should allow for conditional and granular application based on the uploaded CSV file.

## Actual Behavior:
The uploaded allowlist is applied to all conditions in bulk, ignoring any specific settings.

**Comment by MananTank** [comment]
Hey @howdyfrom2019 

> The allowlist should allow for conditional and granular application based on the uploaded CSV file.

Can you elaborate what you mean by "should allow for conditional and granular application based on the uploaded CSV file?". It would be helpful if you can let us know what kind of claim conditions are you trying to set

**Comment by howdyfrom2019** [comment]
Hi @MananTank 

In my case, I set up two `Allowlist Only Phase`. and uploaded in `Add Allowlist` field with snapshot button. I inteded to apply different allowlist by each phase, but both of phases applied same allowlist. (not applied seperatly)  I'll attatch my case as a sample.

**Allowlist Only Phase 1**
- Name: Allowlist Only phase
- Date: 20 Dec 2024 00:00 UTC
- MaxClaimable in phase: 11
- price: 0
> [snapshot-allowlist-test-1.csv](https://github.com/user-attachments/files/18204679/snapshot-allowlist-test-1.csv)


**Allowlist Only Phase 2**
- Name: Allowlist Only phase
- Date: 21 Dec 2024 00:00 UTC
- MaxClaimable in phase: 4
- price: 0
> [snapshot-allowlist-test-2.csv](https://github.com/user-attachments/files/18204680/snapshot-allowlist-test-2.csv)

**Comment by MananTank** [comment]
Hi @howdyfrom2019 - Thanks for reporting this issue and detailed explanation, I was able to replicate the issue and found that the uploaded CSVs were not uploaded correctly due to incorrect caching logic - This is fixed now. Please upload the CSVs again and update the claim conditions - it should work as expected now. If you run into any issues, please let me know
