### ISSUE TITLE
Cannot switch chain to mainnet when connect with Metamask App (QR)

### ISSUE THREAD

**Issue by teodorus-nathaniel** [thirdweb-dev/js#5803]
## Versions Used
- Thirdweb 5.72.0 - 5.79.0
- Metamask (IOS) v7.37.0 (1512)

## How to reproduce:
- Connect metamask with QR (or wallet connect QR but with metamask mobile app)
- Put other chain data to `chain` parameter in `WalletConnectModal`. If the `chain` is undefined, then don't put "locked chains" (the locked chains list below) in the first element of  `chains`
- Switch your metamask wallet connected chain to any chain other than the "locked chains"
- Call `wallet.switchChain(...)` to "locked chains".
- It will cause error `May not specify default Metamask chain.`
![image](https://github.com/user-attachments/assets/68c172e9-381e-4613-abde-e233be280f50)

### Locked Chains List
- Eth Mainnet
- Eth Sepolia
- Linea
- Linea Sepolia
![image](https://github.com/user-attachments/assets/db2af633-bcfa-4626-9b07-1026c230d619)

## Issue Detail
In `thirdweb` if the chain is not included in `approved` list, then the flow is:
1. Call `wallet_addEthereumChain`
2. Call `wallet_switchEthereumChain`

In this case, metamask will throw error if you try to call `wallet_addEthereumChain` with arg of either one of the locked chains.

### Another Related Issue
As `thirdweb` uses `@walletconnect/ethereum-provider` under the hood to create the provider, I tested that library and check which chains will be included in `approved` list.
This library will only include the below ids as `approved`:
1. provided chainId from `chain` props
2. the current connected chain that user have in their metamask

This makes an issue where if the app is multichain, for example `Sepolia` and `Ozean`, and the app wants the user to connect to `Ozean` first, then we need to put `Ozean` as the `chain` props.
Which in turn will make `Sepolia` not included in approved list, and thirdweb will call `wallet_addEthereumChain` when switch chain, and throw the error.

## Possible Solution
From this [comment from metamask's issue](https://github.com/MetaMask/metamask-extension/issues/10597#issuecomment-1008767581)
We can apply this kind of behavior in the `switchChainWc` call

## Minimal Reproducible Example
https://github.com/teodorus-nathaniel/thirdweb-bug-reproduce

**Comment by Derick949** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.
