### ISSUE TITLE
@thirdweb/react not compatible with the recent version of wagmi

### ISSUE THREAD

**Issue by theArtechnology** [thirdweb-dev/js#606]
I open this issue because I recently encounter an issue with the react package of thirdweb. This is the issue and the response from wagmi:

https://github.com/wagmi-dev/wagmi/issues/1858#issuecomment-1431699318

**Comment by jnsdls** [comment]
Hey @theArtechnology since you're using wagmi directly you're likely going to be best off using our "react-core" package which lets you use your own version of wagmi for all wallet level actions and you then just pass the signer directly to the <ThirdwebSDKProvider />

**Comment by jnsdls** [comment]
as an example this should work:

initialize wagmi (per their docs):
```ts
import { WagmiConfig, createClient } from 'wagmi'
import { getDefaultProvider } from 'ethers'

const client = createClient({
 autoConnect: true,
 provider: getDefaultProvider(),
})

function App() {
 return (
   <WagmiConfig client={client}>
     <WrappedThirdwebProvider />
   </WagmiConfig>
 )
}
```
wrapped inside the `<WagmiConfig>` somewhere you can then do

```ts
import { ThirdwebSDKProvider } from '@thirdweb-dev/react-core'
import { useSigner } from 'wagmi'

function WrappedThirdwebProvider(){
  const { data: signer } = useSigner()
  
  return (
    <ThirdwebSDKProvider
      {/* pass the signer from wagmi as a prop */}
      signer={signer}
      {/* other provider options */}
    >
      <TheRestOfYourApp />
    </ThirdwebSDKProvider>
  )
}
```
