### ISSUE TITLE
Starter Kit not working by default clone

### ISSUE THREAD

**Issue by SamSin369** [thirdweb-dev/js#65]
Currently out of the box downloading the starter project does not work for me in vite or react, I tried downgrading my react scripts to v 4.0.3 still getting errors
ERROR in ./node_modules/@zag-js/react/dist/index.mjs 6:0-71 Module not found: Error: Can't resolve 'use-sync-external-store/shim' in '/home/sam/Desktop/help/node_modules/@zag-js/react/dist' Did you mean 'index.js'? BREAKING CHANGE: The request 'use-sync-external-store/shim' failed to resolve only because it was resolved as fully specified (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"'). The extension in the request is mandatory for it to be fully specified. Add the extension to the request.
Using node LTS not sure what the issue is here

**Comment by jarrodwatts** [comment]
Hey @SamSin369 thanks for letting us know! This should be fixed in the latest version of the starter kit.
