### ISSUE TITLE
Tuffle compile error during thirdweb deploy

### ISSUE THREAD

**Issue by allenjeep** [thirdweb-dev/js#70]
I have already deployed a contract to testnet. i would like to deploy with thirdweb sdk and then I can use it for my front end.
But the error shows when I  type :  npx thirdweb deploy
![image](https://user-images.githubusercontent.com/23219031/188510710-f71c5931-ed4f-44cf-a0e0-a9310723d84c.png)

**Comment by joaquim-verges** [comment]
I think this might be an issue with npx not working with truffle unless you have a local version installed.

can you run `npm install --save-dev truffle` and try again?

**Comment by joaquim-verges** [comment]
@allenjeep did that work for you?

**Comment by jarrodwatts** [comment]
Any updates on this @allenjeep? Are you happy to close this issue?
