### ISSUE TITLE
Smart contracts using Solidity libraries fail isHexStrict check during build process

### ISSUE THREAD

**Issue by alpavlove** [thirdweb-dev/js#711]
I'm using Thirdweb CLI to build a Solidity project that includes a contract with a Solidity library. However, I have discovered that the build process does not list the smart contracts that use Solidity libraries and are failing the [`isHexStrict` check](https://github.com/thirdweb-dev/js/blob/d6913d70b2d62a40f5e08e5f23f74e1f174887ca/packages/sdk/src/evm/common/feature-detection.ts#L406). Specifically, the following error messages are being generated:

* Error extracting IPFS hash from '<Contract Name>': Error: Given value '<Hash>' is not a valid hex string.
* Cannot resolve build metadata IPFS hash for contract '<Contract Name>'. Skipping.

I have created a reproduction case to demonstrate the issue, and it appears that the Thirdweb CLI is not properly handling Solidity libraries in the build process.

### Steps to Reproduce:
- Create a new Solidity project that includes a contract with a Solidity library.
- Use Thirdweb CLI to build the project with the `thirdweb build --debug` command.
- Observe that the smart contract using the library fails the [`isHexStrict` check](https://github.com/thirdweb-dev/js/blob/d6913d70b2d62a40f5e08e5f23f74e1f174887ca/packages/sdk/src/evm/common/feature-detection.ts#L406) and generates the errors described above.

### Expected Behavior:
When building a Solidity project with Thirdweb CLI, smart contracts that use Solidity libraries should be properly handled and listed without generating any errors.

### Actual Behavior:
Smart contracts that use Solidity libraries are failing the isHexStrict check and generating errors during the build process with Thirdweb CLI.

Reproduction Case:
https://github.com/alpavlove/solidity-library-use-case

### Environment Information:
- Thirdweb CLI Version: 0.10.3
- Operating System: Mac OS 13.1 (22C65)
- Node Version: v18.12.1

Please let me know if you need any further information or clarification.

**Comment by joaquim-verges** [comment]
@alpavlove thank you for the detailed issue and the reproduction repo.

We are aware of this issue which impacts smart contracts using libraries **that define public/external functions within them**, and therefore need to be deployed separately. We're working on adding support for these publicly callable libraries, including potentially avoiding the need to deploy these libraries every time by leveraging a list of pre-deployed community libraries.

In the meantime, a possible workaround you can do right now is to make the library calls all internal, and expose any needed external call within the main smart contract itself.
