### ISSUE TITLE
CORS issue for /auth/logout

### ISSUE THREAD

**Issue by dimonkov** [thirdweb-dev/js#762]
Every other auth hook uses `credentials: "include"` (to account for CORS) in requests to the backend, except for logout hook.
This leads to a situation, where the server's attempt to clear cookie on logout is completely ignored by the browser.

`./packages/react-core/src/evm/hooks/auth/useUser.ts` should use the same approach to requests, just like every other hook in that folder.

**Comment by subasshrestha** [comment]
I am having the same issue. Please fix it as soon as possible.
