### ISSUE TITLE
[SDK] - Add ability to view and update owner of a contract

### ISSUE THREAD

**Issue by jarrodwatts** [thirdweb-dev/js#81]
## Feature Description

We have the [Ownable](https://portal.thirdweb.com/extensions/features/ownable) functionality on contract extensions and also in many of our prebuilt contracts.

Currently, there is no way to utilize this feature from the SDK.

## Goal

The user should be able to call 

`contract.getOwner` => Get the wallet address of the current owner.
`contract.setOwner` => Attempt to transfer ownership (requires the user be the owner of the smart contract0

**Comment by jnsdls** [comment]
fixed in #194 thx @aeither!

will be released when #227 is merged
