### ISSUE TITLE
[React] - Support 3D File Formats in NFT Media Renderer UI Component

### ISSUE THREAD

**Issue by jarrodwatts** [thirdweb-dev/js#82]
## Feature Request

We have the [NFT Media Renderer](https://portal.thirdweb.com/sdk/ui-components/nft-renderer) component which renders the relevant HTML tag after determining the file type provided by the metadata prop.

This currently only supports image and video files. We would like to add support for common 3D formats such as `.glb`.

## Goal

Be able to provide an NFT that has a `.glb` or other 3D file format file as it's `image` property and have it rendered on the UI.

**Comment by JustinTime42** [comment]
Hi @jarrodwatts,
If this is still a desired feature, I wouldn't mind having a go at it.

**Comment by jarrodwatts** [comment]
That would be awesome @JustinTime42 ! Definitely still something we want to support
