### ISSUE TITLE
How to create custom WalletConnector?

### ISSUE THREAD

**Issue by The-Lion-King** [thirdweb-dev/js#826]
Now only these.

`export type WalletConnector = InjectedConnectorType | WalletConnectConnectorType | WalletLinkConnectorType | GnosisSafeConnector | MagicConnector;`

**Comment by joaquim-verges** [comment]
@The-Lion-King we just released a new package `@thirdweb-dev/wallets` which now contains all our wallet implementations. You can create a custom one by extending `AbstractClientWallet`.

**Comment by MananTank** [comment]
@The-Lion-King We have also added docs for creating a custom connector/wallet and integrating with the Connect Wallet button 
https://portal.thirdweb.com/wallet/build-a-wallet
