### ISSUE TITLE
[CLI] - Fix "Invalid Project name" when a project with a capital letter is entered

### ISSUE THREAD

**Issue by jarrodwatts** [thirdweb-dev/js#83]
## Feature Description

When you enter a name for a project on the CLI when you run `npx thirdweb create`, you currently cannot type any capital letters. We shouldn't show this error, we should just automatically convert it to all lowercase.

![image](https://user-images.githubusercontent.com/35651410/189067778-91253057-58c4-402d-8437-34c5dd6893e9.png)

## Goal

The project name should be automatically all lowercase and not show this error.

**Comment by b4s36t4** [comment]
@jarrodwatts Raised a PR for this issue.

**Comment by jnsdls** [comment]
fixed as part #184, which will be released as part of #157
