### ISSUE TITLE
[CLI] - Set the name of the project in package.json file

### ISSUE THREAD

**Issue by jarrodwatts** [thirdweb-dev/js#84]
## Feature Description

When you create a new project running the `npx thirdweb create --app` command, you get set up with a project that has the name of the starter kit that gets cloned in the `package.json` file.

```
  "name": "next-javascript-starter",
```

We should change this to be the name that the user enters when they create the project.

## Goal

The `name` field in the `package.json` file should be the name the user enters when they create the app.

**Comment by b4s36t4** [comment]
@jarrodwatts Raised a PR. Please have a look at it when you can. Thanks.
