### ISSUE TITLE
[React] - ConnectWallet component incorrect border radius

### ISSUE THREAD

**Issue by jarrodwatts** [thirdweb-dev/js#85]
## Feature Description

The ConnectWallet component has incorrect border radius / rounding in some cases.

![image](https://user-images.githubusercontent.com/35651410/189068904-79b98071-b666-45a8-a026-51121c961581.png)

## Goal

The colored border around the edges should be rounded to match the shape of the inner section.

**Comment by b4s36t4** [comment]
@jarrodwatts any way to reproduce this?

**Comment by mykcryptodev** [comment]
I think this has been fixed. I created a project with thirdweb's next/ts template and this issue does not exist

<img width="787" alt="Screen Shot 2022-11-05 at 9 42 29 AM" src="https://user-images.githubusercontent.com/89474773/200122849-d7766bc4-045d-4236-ac59-a28975715a3e.png">

**Comment by nachoiacovino** [comment]
the bug only happens in Safari afaik @mykcryptodev

**Comment by jarrodwatts** [comment]
Yeah I noticed in on Safari on mobile today
