### ISSUE TITLE
ContractDeployer.deployMarketplaceV3 throws "Passed the wrong number of constructor arguments"

### ISSUE THREAD

**Issue by system32uwu** [thirdweb-dev/js#850]
Repro:

```ts
import {
  MarketplaceV3ContractDeployMetadata,
  ThirdwebSDK,
} from "@thirdweb-dev/sdk";

const args = process.argv.splice(2);
const pk = process.env.PK;

const setup = async () => {
  const network = args.at(0) || process.env.NETWORK || "localhost";

  const sdk = ThirdwebSDK.fromPrivateKey(
    pk,
    network
  );

  const addr = await sdk.wallet.getAddress();

  return {
    sdk,
    addr,
  };
}

const main = async () => {
  const { sdk, addr } = await setup();

  const params: MarketplaceV3ContractDeployMetadata = {
    name: "test marketplace",
  };

  const marketplaceAddress = await sdk.deployer.deployMarketplaceV3(params);
}
```

I'm trying this with a local ganache node, which works fine with deployments of your other contracts. The same happens when trying to deploy it with the web UI.

![image](https://user-images.githubusercontent.com/29718978/229177100-13cc8654-712a-4423-81e8-d7aa66fe7e4e.png)

**Comment by joaquim-verges** [comment]
@system32uwu thanks for reporting this! we're aware of the issue and are actively working on it.

Marketplace v3 is deployable on 14 main chains right now (mainnets/testnets) but not on other chains (including localhost). This is because the contract architecture for marketplace v3 requires some extra onchain infrastructure to be deployed.

We're working on a new deploy flow that enables this seamlessly for all chains. Will keep you updated! cc @kumaryash90

**Comment by system32uwu** [comment]
Thank you for checking this out, we'd work on the testnets but we need to run a lot of tps against the marketplace contract, we don't want to screw them live networks. Thanks again, we'll be waiting for this !

**Comment by joaquim-verges** [comment]
@system32uwu this PR enables deployment of marketplace v3 on all EVM chains `@thirdweb-dev/sdk@0.0.0-dev-7298d5a-20230407214153`

Feel free to give it a run. We'll be releasing this next week

**Comment by system32uwu** [comment]
Great! I've just subscribed to PR notifications on that one, thank you guys for your work.

**Comment by system32uwu** [comment]
@joaquim-verges we can close this issue right? #885

**Comment by joaquim-verges** [comment]
@system32uwu thank you for reminding me! The pr is merged on main, so it's available from `@thirdweb-dev/sdk@nightly`.

still need to publish a new stable release though 🙂
