### ISSUE TITLE
[React] - useNFTSupply throws invariant failed with token ID:

### ISSUE THREAD

**Issue by jarrodwatts** [thirdweb-dev/js#86]
## Feature Description

Incorrectly, the `useNFTBalance` throws an error when the third parameter (token ID) is a number.

For example, the below code errors:

```jsx
  const editionDrop = useEditionDrop(
    "0x1fCbA150F05Bbe1C9D21d3ab08E35D682a4c41bF"
  );
 
 const { data: balance, isLoading } = useNFTBalance(editionDrop, address, 0);
```

## Goal

Allow the third parameter to be of type number

**Comment by b4s36t4** [comment]
@jarrodwatts third parameter will accept number as well.
<img width="809" alt="Screenshot 2022-09-10 at 10 58 45 PM" src="https://user-images.githubusercontent.com/59088937/189494956-be0df1ab-ec99-4159-bfcd-8f6c2076a4f7.png">
