### ISSUE TITLE
[SDK] - Add "getMinimumBidValue" to marketplace

### ISSUE THREAD

**Issue by jarrodwatts** [thirdweb-dev/js#87]
## Feature Description

Currently with the marketplace prebuilt contract there is no way to get the minimum bid a user must place to outbid the previous highest bid.

Let's add it!

## Goal

Add a function to the marketplace smart contract called `getMinimumNextBid`

The logic needs to be something like this:
```
if (auction has current highest bid) {
  return currentHighestBid + (bid buffer * highest bid)
}
else {
  return minimum bid value
}
```

This must take into account [Bid Buffers](https://portal.thirdweb.com/sdk/interacting-with-contracts/marketplace#auction-bid-buffers); i.e. the next bid must be a certain amount higher than the current highest bid.

**Comment by jnebab** [comment]
Hi @jarrodwatts, I made a PR for this issue [here](https://github.com/thirdweb-dev/js/pull/181)
