### ISSUE TITLE
sdk.deployer.addDeployListener

### ISSUE THREAD

**Issue by styleai-luke** [thirdweb-dev/js#875]
Hello, i am doing some stuff that listening deploy events using thirdweb library. 

Currently, i can listen with status === 'completed' but not status === 'submitted'.
and my version is below.

```
"@thirdweb-dev/react": "^3.10.3",
"@thirdweb-dev/sdk": "^3.10.3",
"@typechain/ethers-v5": "^10.2.0",
```

My code is below

```

const bytecode = "";

export default function Home() {
  const sdk = useSDK();
  const handleDeploy = () => {
    sdk?.deployer.deployContractWithAbi([], bytecode, []);
  };

  const handleListen = (e: DeployEvent) => {
    console.info("[Listening event] : ", e);
  };

  useEffect(() => {
    if (sdk) {
      console.info("[Listen started]");
      sdk.deployer.addDeployListener(handleListen);
    }

    return () => sdk?.deployer.removeDeployListener(handleListen);
  }, [sdk]);

  return (
    <>
      <button onClick={handleDeploy}>Deploy</button>
    </>
  );
}

```

is there any my fault?

Thank you,

**Comment by joaquim-verges** [comment]
@styleai-luke we actually introduced a new API to get low level control on any transaction done with the SDK, including deploys. On any transaction, you can call `.prepare` which will return a transaction builder that you can configure, estimate gas, simulate, submit to the blockchain and wait for transactions. See documentation here: https://portal.thirdweb.com/typescript/sdk.smartcontract.prepare

for your use case it would look like this:

```ts
const tx = sdk?.deployer.deployContractWithAbi.prepare([], bytecode, []);
// submit the transaction and get the tx hash back
const sentTx = await tx.send();
// wait for confirmations
await sentTx.wait();
```

let me know if that helps!

**Comment by styleai-luke** [comment]
Oh it is perfectly working, thank you:)
