### ISSUE TITLE
[ConnectWallet] - MetaMask - RPC Error: networkConfigurationId undefined does not match a configured networkConfiguration

### ISSUE THREAD

**Issue by 1001Josias** [thirdweb-dev/js#888]
Hey guys!
I'm using the Connect Wallet component of the `thirdweb-dev/react` lib version `3.11.7` and I'm getting the `networkConfigurationId undefined does not match a configured networkConfiguration` error on some blockchains I've tried to use (see the example in the attached video). Before i was using version `3.9.5` which worked perfectly.

```
import { ThirdwebProvider } from '@thirdweb-dev/react'
import { Arbitrum, Polygon, Ethereum, EthereumClassic } from '@thirdweb-dev/chains'

export default function App({ Component, pageProps }: AppProps) {
  return (
      <ThirdwebProvider supportedChains={[Arbitrum, Polygon, EthereumClassic, Ethereum]} activeChain={EthereumClassic}>
          <Component {...pageProps} />
      </ThirdwebProvider>
  )
}
```

https://user-images.githubusercontent.com/81600458/230785946-bde5594a-f441-4d65-b762-0b3771c9ba7a.mp4

![image](https://user-images.githubusercontent.com/81600458/230785538-6c85b22c-9cca-43ad-8d7f-cfdb101fd942.png)
![image](https://user-images.githubusercontent.com/81600458/230785469-2cdbae00-ac26-46a8-ad84-9a6917af4255.png)

**Comment by 0xLeoDev** [comment]
I'm having the same issue. Let me know please, if you will find the solution

**Comment by 1001Josias** [comment]
@0xLeoDev, the issue was caused by a bug in the metamask and was fixed by https://github.com/MetaMask/metamask-extension/pull/18513.
