### ISSUE TITLE
[NextAuth] Broken since  @thirdweb-dev/react@3.7.0

### ISSUE THREAD

**Issue by tadasgedgaudas** [thirdweb-dev/js#889]
Hey guys,

NextAuth is completely broken since the removal of `useAuth` on this release: https://github.com/thirdweb-dev/js/releases/tag/%40thirdweb-dev%2Freact%403.7.0

Since `useLogin` now is hardcoded to call `${authUrl}/login` while NextAuth default path is `/signin`

Of course, we could rewrite our sign in endpoint to be at `/login` for nextAuth as well but it seems too much work. Would it be possible to bring back useAuth or maybe extend the `authUrl` to accept more parameters for each page?

**Comment by adam-maj** [comment]
@tadasgedgaudas Good find - we're working on fixing it asap. Will get back to you when it's fixed.

**Comment by tadasgedgaudas** [comment]
awesome, thx

**Comment by adam-maj** [comment]
@tadasgedgaudas The `useAuth` hook should be available now on `@thirdweb-dev/react@nightly` now, and will be merged into the next version soon! Lmk if you have any other issues.

**Comment by tadasgedgaudas** [comment]
you're the best, thank you!
