### ISSUE TITLE
Unable to override styles on Web3Button

### ISSUE THREAD

**Issue by calebpdx** [thirdweb-dev/js#934]
A user is unable to override styles on the new web3button (I upgraded from v3.6.9)

I would suspect it could be one of two reasons, but most likely the second..

There are two instances of the code here:
https://github.com/thirdweb-dev/js/blob/bf6df2671131d7ed38650e2bed806081b32dc244/packages/react/src/evm/components/Web3Button/index.tsx#L165

1.) the className prop needs to always come last in the style array so it can override ALL previous styles. 
2.) It looks as if this button is also using tailwind, in which case a tiny component using tailwind-merge and classNames or clsx, or something pretty basic not using a package, can merge and dedupe the tailwind string.

I use this little function to do it in projects of all levels. (hobby -> enterprise)

```
import { twMerge } from "tailwind-merge";
import { clsx } from "clsx";

export function cn(...args) {
  return twMerge(clsx(...args));
}
```
then just wrap that in the core components

```
<Web3Button className={cn("your core styles", className)} />
```

**Comment by jarrodwatts** [comment]
Thanks for raising this @calebpdx! We're looking into this now

**Comment by ashifa454** [comment]
@jarrodwatts I was planning to open a PR for this, Let me know if it has not been assigned?

**Comment by MananTank** [comment]
@calebpdx Can you verify if you are still having this issue in the latest version?

**Comment by mykcryptodev** [comment]
@calebpdx 
![image](https://github.com/thirdweb-dev/js/assets/89474773/ec8ba468-08d5-4828-b52e-b3a82f4df184)
You may need to add !important to your classes for them to work
