### ISSUE TITLE
[SDK]-I want to fix or on/off this feature. Should not be re-try if the signer explicitly cancels

### ISSUE THREAD

**Issue by legiarung** [thirdweb-dev/js#95]
### Difficult
When I deploy contract or transfer, mint, ....

I explicitly reject but a backup signer is called and I have to press reject twice, it's annoying, I don't think this feature is very good.

I suggest is it possible to turn this feature on or off.

### Describe

https://github.com/thirdweb-dev/js/blob/a5cdd85c77510872d32a4d38e9ce44aa07e8b88f/packages/sdk/src/core/classes/factory.ts#L74-L87

### Request

`DEPLOY PROXY DETERMINISTIC`Turn this feature on or off or delete

<img width="365" alt="Screen Shot 2022-09-09 at 3 51 00 PM" src="https://user-images.githubusercontent.com/28915036/189311871-d8d3fd44-0597-4c37-a801-01b6306f6dc0.png">

**Comment by jnsdls** [comment]
thx for calling this out @legiarung, we're working on a fix in #99

**Comment by legiarung** [comment]
thank you
